Repository discord-jda/JDA, pull requests merged in 2018-04, with the labels that each got.

#658 Clear expected member chunks on guild delete
  src/main/java/net/dv8tion/jda/core/handle/GuildDeleteHandler.java
  src/main/java/net/dv8tion/jda/core/handle/GuildMembersChunkHandler.java
Labels: version: revision

#665 Permission#VOICE_MOVE_OTHERS does not grant access to a voice channel
  src/main/java/net/dv8tion/jda/core/managers/impl/AudioManagerImpl.java
Labels: bug, version: revision

#664 Fixed issues with permission management in RoleManager
  src/main/java/net/dv8tion/jda/core/managers/RoleManager.java
Labels: bug, status: completed, version: revision

#676 Added possibility to sync Permissions between channels
  src/main/java/net/dv8tion/jda/core/managers/ChannelManager.java
Labels: status: completed, type: feature

#655 Added enum to represent the flags set on a RichPresence
  src/main/java/net/dv8tion/jda/core/entities/ActivityFlag.java
  src/main/java/net/dv8tion/jda/core/entities/RichPresence.java
Labels: type: feature, version: revision
