Repository discord-jda/JDA, pull requests merged in 2018-11, with the labels that each got.

#820 Close socket on malformed zip data
  src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
Labels: status: completed, type: jre issue

#819 Add ChannelAction#setPosition(Integer)
  src/main/java/net/dv8tion/jda/core/requests/restaction/ChannelAction.java
Labels: type: feature

#814 Added appendCodeLine(CharSequence text)
  src/main/java/net/dv8tion/jda/core/MessageBuilder.java
Labels: status: completed, type: enhancement

#825 Added copying of the slowmode when cloning a channel
  src/main/java/net/dv8tion/jda/core/entities/Channel.java
  src/main/java/net/dv8tion/jda/core/entities/impl/TextChannelImpl.java
Labels: bug

#827 Don't check admin on permission overrides
  src/main/java/net/dv8tion/jda/core/exceptions/ErrorResponseException.java
  src/main/java/net/dv8tion/jda/core/utils/PermissionUtil.java
Labels: bug

#826 Hacktoberfest Changes
  src/main/java/net/dv8tion/jda/bot/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/core/events/guild/GuildJoinEvent.java
  src/main/java/net/dv8tion/jda/core/events/message/MessageBulkDeleteEvent.java
Labels: Hacktoberfest
