Repository discord-jda/JDA, pull requests merged in 2018-03, with the labels that each got.

#637 Restructure GenericMessageEvent
  src/main/java/net/dv8tion/jda/core/events/message/GenericMessageEvent.java
  src/main/java/net/dv8tion/jda/core/events/message/MessageDeleteEvent.java
  src/main/java/net/dv8tion/jda/core/events/message/MessageEmbedEvent.java
  src/main/java/net/dv8tion/jda/core/events/message/MessageReceivedEvent.java
  src/main/java/net/dv8tion/jda/core/events/message/MessageUpdateEvent.java
  src/main/java/net/dv8tion/jda/core/events/message/react/GenericMessageReactionEvent.java
  src/main/java/net/dv8tion/jda/core/events/message/react/MessageReactionRemoveAllEvent.java
Labels: type: enhancement, version: patch

#611 Store color with raw RGB value
  src/main/java/net/dv8tion/jda/core/EmbedBuilder.java
  src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/core/entities/Member.java
  src/main/java/net/dv8tion/jda/core/entities/MessageEmbed.java
  src/main/java/net/dv8tion/jda/core/entities/Role.java
  src/main/java/net/dv8tion/jda/core/entities/impl/MemberImpl.java
  src/main/java/net/dv8tion/jda/core/entities/impl/RoleImpl.java
  src/main/java/net/dv8tion/jda/core/events/role/update/RoleUpdateColorEvent.java
  src/main/java/net/dv8tion/jda/core/handle/GuildRoleUpdateHandler.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/GuildAction.java
Labels: type: enhancement, version: revision

#634 Make mentions distinct
  src/main/java/net/dv8tion/jda/core/entities/impl/ReceivedMessage.java
Labels: bug, type: enhancement, version: patch

#613 Support for parsing more presences
  src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/core/entities/Game.java
  src/main/java/net/dv8tion/jda/core/entities/RichPresence.java
Labels: status: completed, type: enhancement, version: patch

#595 Add sharded listener provider
  src/main/java/net/dv8tion/jda/bot/sharding/DefaultShardManager.java
  src/main/java/net/dv8tion/jda/bot/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/bot/sharding/ShardManager.java
Labels: status: completed, type: enhancement, version: revision

#633 Enhancements for Permissions/CacheView/ErrorResponseException
  build.gradle
  src/main/java/net/dv8tion/jda/bot/utils/cache/impl/ShardCacheViewImpl.java
  src/main/java/net/dv8tion/jda/client/entities/impl/GroupImpl.java
  src/main/java/net/dv8tion/jda/client/entities/impl/JDAClientImpl.java
  src/main/java/net/dv8tion/jda/core/Permission.java
  src/main/java/net/dv8tion/jda/core/audio/AudioConnection.java
  src/main/java/net/dv8tion/jda/core/audio/AudioWebSocket.java
  src/main/java/net/dv8tion/jda/core/audio/Decoder.java
  src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java
  src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java
  src/main/java/net/dv8tion/jda/core/entities/impl/MemberImpl.java
  src/main/java/net/dv8tion/jda/core/entities/impl/RoleImpl.java
  src/main/java/net/dv8tion/jda/core/exceptions/ErrorResponseException.java
  src/main/java/net/dv8tion/jda/core/handle/MessageBulkDeleteHandler.java
  src/main/java/net/dv8tion/jda/core/requests/RestAction.java
  src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/AuditableRestAction.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/PermissionOverrideAction.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/RoleAction.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/order/OrderAction.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/pagination/PaginationAction.java
  src/main/java/net/dv8tion/jda/core/utils/cache/CacheView.java
  src/main/java/net/dv8tion/jda/core/utils/cache/impl/AbstractCacheView.java
  src/main/java/net/dv8tion/jda/core/utils/cache/impl/MemberCacheViewImpl.java
  src/main/java/net/dv8tion/jda/core/utils/cache/impl/SnowflakeCacheViewImpl.java
  src/main/java/net/dv8tion/jda/core/utils/cache/impl/SortedSnowflakeCacheView.java
  src/main/java/net/dv8tion/jda/core/utils/cache/impl/UnifiedCacheViewImpl.java
  src/main/java/net/dv8tion/jda/webhook/WebhookClient.java
Labels: status: completed, type: enhancement, version: patch

#644 Return RequestFuture for PaginationAction async iterations
  src/main/java/net/dv8tion/jda/core/requests/restaction/pagination/PaginationAction.java
Labels: status: completed, type: enhancement, version: revision

#646 Added support for bulk updating permission overrides
  src/main/java/net/dv8tion/jda/core/managers/ChannelManager.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/PermOverrideData.java
Labels: status: completed, type: feature, version: minor

#645 WebSocketClient optimization/enhancements
  src/main/java/net/dv8tion/jda/bot/sharding/DefaultShardManager.java
  src/main/java/net/dv8tion/jda/bot/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/core/JDABuilder.java
  src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java
  src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
Labels: status: completed, type: enhancement, version: revision
