Repository discord-jda/JDA, pull requests merged in 2018-06, with the labels that each got.

#692 Add proper boundaries to methods
  src/main/java/net/dv8tion/jda/core/exceptions/ContextException.java
  src/main/java/net/dv8tion/jda/core/managers/impl/ManagerBase.java
  src/main/java/net/dv8tion/jda/core/requests/Request.java
  src/main/java/net/dv8tion/jda/core/requests/RestAction.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/AuditableRestAction.java
Labels: status: completed, type: enhancement, version: revision

#694 Don't call toString() eagerly on arguments to format()
  src/main/java/net/dv8tion/jda/core/utils/PermissionUtil.java
Labels: status: completed, type: enhancement, version: patch

#659 Externalize opus binaries
  .editorconfig
  .gitattributes
  README.md
  build.gradle
  src/main/java/net/dv8tion/jda/core/audio/AudioConnection.java
  src/main/java/net/dv8tion/jda/core/audio/AudioNatives.java
  src/main/java/net/dv8tion/jda/core/managers/impl/AudioManagerImpl.java
  src/main/java/net/dv8tion/jda/core/utils/NativeUtil.java
  src/main/java/net/dv8tion/jda/core/utils/package-info.java
  src/main/java/tomp2p/opuswrapper/Opus.java
  src/main/resources/natives/darwin/libopus.dylib
  src/main/resources/natives/linux-aarch64/libopus.so
  src/main/resources/natives/linux-arm/libopus.so
  src/main/resources/natives/linux-x86-64/libopus.so
  src/main/resources/natives/linux-x86/libopus.so
  src/main/resources/natives/win32-x86-64/libopus.dll
  src/main/resources/natives/win32-x86/libopus.dll
Labels: status: completed, type: proposal, version: patch

#687 Improve snowflake checks for rest requests
  src/main/java/net/dv8tion/jda/core/entities/MessageChannel.java
  src/main/java/net/dv8tion/jda/core/entities/MessageHistory.java
  src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java
  src/main/java/net/dv8tion/jda/core/entities/impl/TextChannelImpl.java
  src/main/java/net/dv8tion/jda/core/managers/GuildController.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/pagination/AuditLogPaginationAction.java
  src/main/java/net/dv8tion/jda/core/utils/Checks.java
  src/main/java/net/dv8tion/jda/core/utils/Helpers.java
Labels: status: completed, type: enhancement, version: patch

#683 Fix of typo - MessageChannel.java
  src/main/java/net/dv8tion/jda/core/entities/MessageChannel.java
Labels: status: completed, version: patch

#681 Add support for sending multiple files with a webhook
  src/main/java/net/dv8tion/jda/core/requests/Requester.java
  src/main/java/net/dv8tion/jda/core/requests/ratelimit/BotRateLimiter.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/MessageAction.java
  src/main/java/net/dv8tion/jda/webhook/MessageAttachment.java
  src/main/java/net/dv8tion/jda/webhook/WebhookClient.java
  src/main/java/net/dv8tion/jda/webhook/WebhookCluster.java
  src/main/java/net/dv8tion/jda/webhook/WebhookMessage.java
  src/main/java/net/dv8tion/jda/webhook/WebhookMessageBuilder.java
Labels: status: completed, type: feature, version: minor

#678 Additional invite info
  src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/core/entities/Invite.java
  src/main/java/net/dv8tion/jda/core/entities/impl/InviteImpl.java
Labels: status: completed, type: feature, version: minor
