Repository discord-jda/JDA, pull requests merged in 2018-08, with the labels that each got.

#731 Add Permission.PRIORITY_SPEAKER
  src/main/java/net/dv8tion/jda/core/Permission.java
Labels: type: enhancement, version: patch

#721 Improve use of MDC
  src/main/java/net/dv8tion/jda/core/audio/AudioConnection.java
  src/main/java/net/dv8tion/jda/core/audio/AudioWebSocket.java
  src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java
  src/main/java/net/dv8tion/jda/core/requests/Requester.java
  src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/core/requests/ratelimit/BotRateLimiter.java
  src/main/java/net/dv8tion/jda/core/requests/ratelimit/ClientRateLimiter.java
Labels: bug, status: completed, type: enhancement, version: patch

#735 Add support for getting webhooks by id
  src/main/java/net/dv8tion/jda/core/JDA.java
  src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java
Labels: type: feature, version: minor

#732 Add support for new sending modes
  README.md
  src/main/java/net/dv8tion/jda/core/audio/AudioConnection.java
  src/main/java/net/dv8tion/jda/core/audio/SpeakingMode.java
  src/main/java/net/dv8tion/jda/core/managers/AudioManager.java
  src/main/java/net/dv8tion/jda/core/managers/impl/AudioManagerImpl.java
Labels: type: feature, version: patch

#738 Change minimum channel name length to 1
  src/main/java/net/dv8tion/jda/core/entities/Category.java
  src/main/java/net/dv8tion/jda/core/managers/ChannelManager.java
  src/main/java/net/dv8tion/jda/core/managers/GuildController.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/ChannelAction.java
Labels: bug, version: patch

#730 Change jcenter link for okhttp3 dependency
  README.md
Labels: priority: low

#734 Support getting ban by user id
  src/main/java/net/dv8tion/jda/core/entities/Guild.java
  src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java
  src/main/java/net/dv8tion/jda/core/requests/ErrorResponse.java
  src/main/java/net/dv8tion/jda/core/requests/Route.java
Labels: type: feature, version: minor

#740 Add support to retrieve emotes via RestAction access
  src/main/java/net/dv8tion/jda/client/managers/EmoteManager.java
  src/main/java/net/dv8tion/jda/core/entities/Emote.java
  src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/core/entities/Guild.java
  src/main/java/net/dv8tion/jda/core/entities/ListedEmote.java
  src/main/java/net/dv8tion/jda/core/entities/impl/EmoteImpl.java
  src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java
  src/main/java/net/dv8tion/jda/core/requests/Route.java
Labels: status: completed, type: feature, version: minor

#741 Added retrieveUserById to ShardManager
  src/main/java/net/dv8tion/jda/bot/sharding/ShardManager.java
Labels: type: feature, version: minor

#747 Fix IllegalArgumentException on TextChannel#canTalk()
  src/main/java/net/dv8tion/jda/core/entities/impl/TextChannelImpl.java
Labels: bug, version: patch

#748 Patch upstream reference
  src/main/java/net/dv8tion/jda/core/audio/AudioConnection.java
  src/main/java/net/dv8tion/jda/core/entities/impl/GuildVoiceStateImpl.java
  src/main/java/net/dv8tion/jda/core/entities/impl/MemberImpl.java
  src/main/java/net/dv8tion/jda/core/entities/impl/PermissionOverrideImpl.java
  src/main/java/net/dv8tion/jda/core/entities/impl/PrivateChannelImpl.java
  src/main/java/net/dv8tion/jda/core/managers/impl/AudioManagerImpl.java
  src/main/java/net/dv8tion/jda/core/utils/cache/UpstreamReference.java
Labels: bug, version: patch

#745 Add new annotations for common documentation concerns
  README.md
  build.gradle
  src/main/java/net/dv8tion/jda/annotations/DeprecatedSince.java
  src/main/java/net/dv8tion/jda/annotations/ForRemoval.java
  src/main/java/net/dv8tion/jda/annotations/Incubating.java
  src/main/java/net/dv8tion/jda/annotations/ReplaceWith.java
  src/main/java/net/dv8tion/jda/core/JDABuilder.java
  src/main/java/net/dv8tion/jda/core/audio/AudioConnection.java
  src/main/java/net/dv8tion/jda/core/audio/Decoder.java
  src/main/java/net/dv8tion/jda/core/audio/SpeakingMode.java
  src/main/java/net/dv8tion/jda/core/entities/Game.java
  src/main/java/net/dv8tion/jda/core/entities/RichPresence.java
  src/main/java/net/dv8tion/jda/core/managers/AudioManager.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/MessageAction.java
  src/main/java/net/dv8tion/jda/webhook/WebhookClient.java
  src/main/java/net/dv8tion/jda/webhook/WebhookMessage.java
  src/main/java/net/dv8tion/jda/webhook/WebhookMessageBuilder.java
Labels: type: enhancement, type: proposal, version: patch

#700 Add jump-to URL for Messages
  src/main/java/net/dv8tion/jda/core/entities/Message.java
  src/main/java/net/dv8tion/jda/core/entities/impl/AbstractMessage.java
  src/main/java/net/dv8tion/jda/core/entities/impl/ReceivedMessage.java
Labels: type: feature, version: revision

#749 Add request exceptions to cause of ErrorResponseException
  src/main/java/net/dv8tion/jda/core/exceptions/ErrorResponseException.java
  src/main/java/net/dv8tion/jda/core/requests/RestAction.java
Labels: status: completed, type: enhancement, version: revision

#751 Allow titles without TLD
  src/main/java/net/dv8tion/jda/core/EmbedBuilder.java
Labels: bug, version: patch
