Repository discord-jda/JDA, pull requests merged in 2018-05, with the labels that each got.

#680 Ability to add members to guilds
  src/main/java/net/dv8tion/jda/core/entities/Guild.java
  src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java
  src/main/java/net/dv8tion/jda/core/requests/Route.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/MemberAction.java
Labels: status: completed, version: minor

#684 Fixing Role#getAsMention() for public Role
  src/main/java/net/dv8tion/jda/core/entities/IMentionable.java
  src/main/java/net/dv8tion/jda/core/entities/impl/RoleImpl.java
Labels: p: low-priority, status: completed, type: enhancement

#675 Allow null user_id and provide partial Webhooks
  src/main/java/net/dv8tion/jda/core/audit/AuditLogEntry.java
  src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/core/entities/Webhook.java
  src/main/java/net/dv8tion/jda/core/entities/impl/WebhookImpl.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/pagination/AuditLogPaginationAction.java
Labels: bug, status: completed, type: feature, version: revision

#671 Add unicode flag emoji for each Region
  src/main/java/net/dv8tion/jda/core/Region.java
Labels: status: completed, type: feature, version: minor

#685 Add option to exclude deprecated voice regions
  src/main/java/net/dv8tion/jda/core/entities/Guild.java
  src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java
Labels: status: completed, version: revision

#670 Cleaned up BotRateLimiter for better handling of partial/missing headers
  src/main/java/net/dv8tion/jda/core/requests/RateLimiter.java
  src/main/java/net/dv8tion/jda/core/requests/Route.java
  src/main/java/net/dv8tion/jda/core/requests/ratelimit/BotRateLimiter.java
Labels: status: completed, type: enhancement, version: revision
