Repository discord-jda/JDA, pull requests merged in 2018-09, with the labels that each got.

#752 Fix NullPointerException in EmoteImpl#getGuild()
  src/main/java/net/dv8tion/jda/core/entities/impl/EmoteImpl.java
Labels: bug, version: patch

#750 Add purgeMessages methods for convenient message deletions
  build.gradle
  src/main/java/net/dv8tion/jda/client/entities/impl/GroupImpl.java
  src/main/java/net/dv8tion/jda/core/entities/Message.java
  src/main/java/net/dv8tion/jda/core/entities/MessageChannel.java
  src/main/java/net/dv8tion/jda/core/entities/TextChannel.java
  src/main/java/net/dv8tion/jda/core/entities/impl/PrivateChannelImpl.java
  src/main/java/net/dv8tion/jda/core/entities/impl/TextChannelImpl.java
  src/main/java/net/dv8tion/jda/core/requests/Route.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/pagination/PaginationAction.java
Labels: status: completed, type: feature, type: proposal, version: minor

#756 Prevent creation of audio managers for uncached guilds
  src/main/java/net/dv8tion/jda/core/audio/AudioWebSocket.java
  src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java
  src/main/java/net/dv8tion/jda/core/handle/GuildDeleteHandler.java
  src/main/java/net/dv8tion/jda/core/handle/GuildSetupNode.java
  src/main/java/net/dv8tion/jda/core/managers/impl/AudioManagerImpl.java
  src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
Labels: bug, version: revision

#709 Better group invite support
  src/main/java/net/dv8tion/jda/client/entities/impl/ApplicationImpl.java
  src/main/java/net/dv8tion/jda/client/entities/impl/GroupImpl.java
  src/main/java/net/dv8tion/jda/client/events/group/update/GroupUpdateIconEvent.java
  src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/core/entities/Invite.java
  src/main/java/net/dv8tion/jda/core/entities/RichPresence.java
  src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java
  src/main/java/net/dv8tion/jda/core/entities/impl/InviteImpl.java
  src/main/java/net/dv8tion/jda/core/events/guild/update/GuildUpdateSplashEvent.java
Labels: status: completed, type: feature, version: minor

#757 Replace Emote#hasRoles to avoid ambiguity
  src/main/java/net/dv8tion/jda/core/entities/Emote.java
  src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/core/entities/impl/EmoteImpl.java
  src/main/java/net/dv8tion/jda/core/handle/GuildEmojisUpdateHandler.java
  src/main/java/net/dv8tion/jda/core/handle/GuildRoleDeleteHandler.java
  src/main/java/net/dv8tion/jda/core/utils/PermissionUtil.java
Labels: bug, status: completed, type: enhancement, version: revision

#754 Add ThreadLocalReason
  src/main/java/net/dv8tion/jda/core/audit/ThreadLocalReason.java
  src/main/java/net/dv8tion/jda/core/requests/Request.java
  src/main/java/net/dv8tion/jda/core/requests/RestAction.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/AuditableRestAction.java
Labels: status: completed, type: feature, type: proposal, version: minor

#761 Fix ShardManager#getGuildById
  src/main/java/net/dv8tion/jda/bot/sharding/DefaultShardManager.java
  src/main/java/net/dv8tion/jda/bot/sharding/ShardManager.java
Labels: bug, priority: high, status: completed, version: revision

#758 Update documentation of JDABuilder and add new constructor overloads
  README.md
  build.gradle
  src/examples/java/MessageListenerExample.java
  src/main/java/net/dv8tion/jda/annotations/Incubating.java
  src/main/java/net/dv8tion/jda/core/JDABuilder.java
Labels: status: completed, version: patch

#764 Cleanup RTP handling
  src/main/java/net/dv8tion/jda/core/audio/AudioPacket.java
  src/main/java/net/dv8tion/jda/core/audio/Decoder.java
Labels: bug, priority: high, status: completed

#766 Make AudioWebSocket a subordinate class
  src/main/java/net/dv8tion/jda/core/JDAInfo.java
  src/main/java/net/dv8tion/jda/core/audio/AudioConnection.java
  src/main/java/net/dv8tion/jda/core/audio/AudioPacket.java
  src/main/java/net/dv8tion/jda/core/audio/AudioWebSocket.java
  src/main/java/net/dv8tion/jda/core/audio/KeepAliveThreadFactory.java
  src/main/java/net/dv8tion/jda/core/audio/hooks/ConnectionStatus.java
  src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java
  src/main/java/net/dv8tion/jda/core/handle/VoiceServerUpdateHandler.java
  src/main/java/net/dv8tion/jda/core/managers/impl/AudioManagerImpl.java
  src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
Labels: bug, priority: high, status: completed

#769 Fix granting / denying permissions
  src/main/java/net/dv8tion/jda/core/managers/PermOverrideManager.java
Labels: bug, status: completed

#770 Only update lastFrameSent when actually sending something
  src/main/java/net/dv8tion/jda/core/audio/factory/DefaultSendSystem.java
Labels: bug, priority: high, version: patch

#762 Prevent using complete() in callbacks
  src/main/java/net/dv8tion/jda/core/requests/CallbackContext.java
  src/main/java/net/dv8tion/jda/core/requests/Request.java
  src/main/java/net/dv8tion/jda/core/requests/RestAction.java
Labels: status: completed, type: enhancement, type: proposal

#780 Fire UnavailableGuildJoinedEvent again
  src/main/java/net/dv8tion/jda/core/handle/GuildSetupNode.java
Labels: bug

#782 Replace ignored NPEs with null checks
  src/main/java/net/dv8tion/jda/core/handle/EventCache.java
Labels: status: completed, type: enhancement

#776 Configuration for mainWs sending pools
  README.md
  build.gradle
  src/main/java/net/dv8tion/jda/bot/sharding/DefaultShardManager.java
  src/main/java/net/dv8tion/jda/bot/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/core/JDABuilder.java
  src/main/java/net/dv8tion/jda/core/audio/AudioConnection.java
  src/main/java/net/dv8tion/jda/core/audio/AudioWebSocket.java
  src/main/java/net/dv8tion/jda/core/audio/KeepAliveThreadFactory.java
  src/main/java/net/dv8tion/jda/core/audio/factory/DefaultSendSystem.java
  src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java
  src/main/java/net/dv8tion/jda/core/managers/impl/AudioManagerImpl.java
  src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/core/requests/WebSocketSendingThread.java
  src/main/java/net/dv8tion/jda/core/utils/concurrent/CountingThreadFactory.java
Labels: status: completed, type: enhancement, type: proposal

#771 Cleanup logs
  src/main/java/net/dv8tion/jda/core/audio/AudioWebSocket.java
  src/main/java/net/dv8tion/jda/core/handle/GuildDeleteHandler.java
  src/main/java/net/dv8tion/jda/core/requests/RateLimiter.java
  src/main/java/net/dv8tion/jda/core/requests/Route.java
  src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/core/requests/ratelimit/BotRateLimiter.java
  src/main/java/net/dv8tion/jda/core/requests/ratelimit/ClientRateLimiter.java
  src/main/java/net/dv8tion/jda/core/requests/ratelimit/IBucket.java
Labels: priority: low, status: completed, type: enhancement
