Repository discord-jda/JDA, pull requests merged in 2018-02, with the labels that each got.

#618 Lazy evaluation of HTTP responses
  src/main/java/net/dv8tion/jda/core/requests/Response.java
Labels: status: completed, type: enhancement, version: patch

#614 Fixed Message#getMentionedX() methods returning non-mentioned entities
  src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/core/entities/Message.java
  src/main/java/net/dv8tion/jda/core/entities/impl/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/core/entities/impl/SystemMessage.java
Labels: type: enhancement, version: revision

#622 Fixed a few issues with session startup and close
  src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/core/utils/SessionControllerAdapter.java
Labels: bug, version: patch

#620 Release 3.5.1
  .gitattributes
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
  src/main/java/net/dv8tion/jda/bot/sharding/DefaultShardManager.java
  src/main/java/net/dv8tion/jda/bot/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/client/managers/EmoteManager.java
  src/main/java/net/dv8tion/jda/client/managers/EmoteManagerUpdatable.java
  src/main/java/net/dv8tion/jda/client/requests/restaction/ApplicationAction.java
  src/main/java/net/dv8tion/jda/core/JDA.java
  src/main/java/net/dv8tion/jda/core/JDABuilder.java
  src/main/java/net/dv8tion/jda/core/ShardedRateLimiter.java
  src/main/java/net/dv8tion/jda/core/audio/AudioWebSocket.java
  src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/core/entities/Guild.java
  src/main/java/net/dv8tion/jda/core/entities/Message.java
  src/main/java/net/dv8tion/jda/core/entities/RichPresence.java
  src/main/java/net/dv8tion/jda/core/entities/impl/DataMessage.java
  src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java
  src/main/java/net/dv8tion/jda/core/entities/impl/PrivateChannelImpl.java
  src/main/java/net/dv8tion/jda/core/entities/impl/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/core/entities/impl/SystemMessage.java
  src/main/java/net/dv8tion/jda/core/exceptions/ContextException.java
  src/main/java/net/dv8tion/jda/core/handle/ChannelDeleteHandler.java
  src/main/java/net/dv8tion/jda/core/handle/GuildCreateHandler.java
  src/main/java/net/dv8tion/jda/core/handle/GuildDeleteHandler.java
  src/main/java/net/dv8tion/jda/core/handle/GuildRoleDeleteHandler.java
  src/main/java/net/dv8tion/jda/core/handle/PresenceUpdateHandler.java
  src/main/java/net/dv8tion/jda/core/managers/GuildController.java
  src/main/java/net/dv8tion/jda/core/managers/impl/AudioManagerImpl.java
  src/main/java/net/dv8tion/jda/core/requests/RateLimiter.java
  src/main/java/net/dv8tion/jda/core/requests/Request.java
  src/main/java/net/dv8tion/jda/core/requests/RequestFuture.java
  src/main/java/net/dv8tion/jda/core/requests/Requester.java
  src/main/java/net/dv8tion/jda/core/requests/Response.java
  src/main/java/net/dv8tion/jda/core/requests/RestAction.java
  src/main/java/net/dv8tion/jda/core/requests/RestFuture.java
  src/main/java/net/dv8tion/jda/core/requests/SessionReconnectQueue.java
  src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/core/requests/ratelimit/BotRateLimiter.java
  src/main/java/net/dv8tion/jda/core/requests/ratelimit/ClientRateLimiter.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/AuditableRestAction.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/ChannelAction.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/GuildAction.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/InviteAction.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/PermissionOverrideAction.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/RoleAction.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/WebhookAction.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/order/OrderAction.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/pagination/PaginationAction.java
  src/main/java/net/dv8tion/jda/core/utils/PermissionUtil.java
  src/main/java/net/dv8tion/jda/core/utils/ProvidingSessionController.java
  src/main/java/net/dv8tion/jda/core/utils/SessionControllerAdapter.java
  src/main/resources/natives/linux-aarch64/libopus.so
Labels: release

#628 Add Japan region
  src/main/java/net/dv8tion/jda/core/Region.java
Labels: type: enhancement, version: patch

#627 Fallback body parsing for http response
  src/main/java/net/dv8tion/jda/core/entities/Channel.java
  src/main/java/net/dv8tion/jda/core/entities/impl/AbstractChannelImpl.java
  src/main/java/net/dv8tion/jda/core/events/http/HttpRequestEvent.java
  src/main/java/net/dv8tion/jda/core/exceptions/ErrorResponseException.java
  src/main/java/net/dv8tion/jda/core/requests/Request.java
  src/main/java/net/dv8tion/jda/core/requests/Response.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/PermissionOverrideAction.java
  src/main/java/net/dv8tion/jda/core/utils/IOFunction.java
Labels: bug

#630 Added Guild#retrieveRegions
  src/main/java/net/dv8tion/jda/core/entities/Guild.java
  src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java
  src/main/java/net/dv8tion/jda/core/requests/Route.java
Labels: type: feature, version: revision
