Repository discord-jda/JDA, pull requests merged in 2018-10, with the labels that each got.

#785 Add DefaultShardManager#setEventManagerProvider and JDA#getEventManager
  src/main/java/net/dv8tion/jda/bot/sharding/DefaultShardManager.java
  src/main/java/net/dv8tion/jda/bot/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/core/JDA.java
  src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java
Labels: status: completed, type: feature

#788 Add timeout mechanic for chunk requests
  src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java
  src/main/java/net/dv8tion/jda/core/handle/GuildSetupController.java
Labels: status: completed, type: enhancement, type: proposal

#798 Fix idle issues for DefaultSendSystem
  src/main/java/net/dv8tion/jda/core/audio/factory/DefaultSendSystem.java
Labels: bug, priority: high

#800 Fix issue with audio region change
  src/main/java/net/dv8tion/jda/core/audio/AudioWebSocket.java
  src/main/java/net/dv8tion/jda/core/handle/GuildDeleteHandler.java
  src/main/java/net/dv8tion/jda/core/managers/impl/AudioManagerImpl.java
Labels: bug, priority: high

#801 Cleanup shutdown() and fix race-condition
  src/main/java/net/dv8tion/jda/core/audio/hooks/ConnectionStatus.java
  src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java
Labels: bug, priority: high

#795 Add Guild#getChannels for convenience
  src/main/java/net/dv8tion/jda/core/entities/Guild.java
  src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java
Labels: status: completed, type: feature

#810 Reordered VoiceState changes. Fixes #805
  src/main/java/net/dv8tion/jda/core/handle/VoiceStateUpdateHandler.java
Labels: bug
