Repository discord-jda/JDA, pull requests merged in 2019-06, with the labels that each got.

#1010 Remove usages of _trace
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/events/DisconnectEvent.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
Labels: size: small, type: breaking, type: discord issue

#1015 Add new message types
  src/main/java/net/dv8tion/jda/api/entities/MessageType.java
Labels: size: small, type: feature

#1002 Add RawGatewayEvent
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/JDABuilder.java
  src/main/java/net/dv8tion/jda/api/events/RawGatewayEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/internal/utils/config/MetaConfig.java
  src/main/java/net/dv8tion/jda/internal/utils/config/SessionConfig.java
  src/main/java/net/dv8tion/jda/internal/utils/config/flags/ConfigFlag.java
  src/main/java/net/dv8tion/jda/internal/utils/config/flags/ShardingConfigFlag.java
  src/main/java/net/dv8tion/jda/internal/utils/config/sharding/ShardingMetaConfig.java
  src/main/java/net/dv8tion/jda/internal/utils/config/sharding/ShardingSessionConfig.java
Labels: size: small, type: breaking, type: feature

#955 Add guild and channel context to InsufficientPermissionException
  src/main/java/net/dv8tion/jda/api/MessageBuilder.java
  src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java
  src/main/java/net/dv8tion/jda/api/entities/MessageHistory.java
  src/main/java/net/dv8tion/jda/api/entities/MessageReaction.java
  src/main/java/net/dv8tion/jda/api/exceptions/InsufficientPermissionException.java
  src/main/java/net/dv8tion/jda/internal/entities/AbstractChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/EmoteImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/InviteImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/PermissionOverrideImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/RoleImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/AudioManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/ChannelManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/EmoteManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/GuildManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/PermOverrideManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/RoleManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/WebhookManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/PermissionOverrideActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/RoleActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/order/ChannelOrderActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/order/RoleOrderActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/AuditLogPaginationActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/MessagePaginationActionImpl.java
Labels: size: small, type: breaking, type: feature

#1014 Add shortcuts for common actions on Members
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/Member.java
Labels: size: small, type: feature

#1016 Restructure handling of unavailable events during setup
  src/main/java/net/dv8tion/jda/internal/handle/GuildSetupController.java
Labels: bug

#1001 Opus Interceptor
  src/examples/java/AudioEchoExample.java
  src/main/java/net/dv8tion/jda/api/audio/AudioReceiveHandler.java
  src/main/java/net/dv8tion/jda/api/audio/CombinedAudio.java
  src/main/java/net/dv8tion/jda/api/audio/OpusPacket.java
  src/main/java/net/dv8tion/jda/api/audio/UserAudio.java
  src/main/java/net/dv8tion/jda/api/audio/factory/DefaultSendSystem.java
  src/main/java/net/dv8tion/jda/internal/audio/AudioConnection.java
  src/main/java/net/dv8tion/jda/internal/audio/AudioPacket.java
  src/main/java/net/dv8tion/jda/internal/audio/Decoder.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/internal/utils/IOUtil.java
Labels: priority: low, size: medium

#1019 Handle split zlib messages with Z_SYNC_FLUSH suffix
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/internal/utils/IOUtil.java
  src/main/java/net/dv8tion/jda/internal/utils/compress/Decompressor.java
  src/main/java/net/dv8tion/jda/internal/utils/compress/ZlibDecompressor.java
Labels: size: small, type: enhancement

#1017 Javadoc Updates
  build.gradle.kts
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/JDABuilder.java
  src/main/java/net/dv8tion/jda/api/entities/Category.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java
  src/main/java/net/dv8tion/jda/api/entities/Member.java
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
  src/main/java/net/dv8tion/jda/api/entities/MessageEmbed.java
  src/main/java/net/dv8tion/jda/api/entities/MessageHistory.java
  src/main/java/net/dv8tion/jda/api/entities/StoreChannel.java
  src/main/java/net/dv8tion/jda/api/entities/TextChannel.java
  src/main/java/net/dv8tion/jda/api/entities/User.java
  src/main/java/net/dv8tion/jda/api/exceptions/InsufficientPermissionException.java
  src/main/java/net/dv8tion/jda/api/hooks/VoiceDispatchInterceptor.java
  src/main/java/net/dv8tion/jda/api/requests/RestAction.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/api/utils/ClosableIterator.java
  src/main/java/net/dv8tion/jda/api/utils/LockIterator.java
  src/main/java/net/dv8tion/jda/api/utils/MarkdownSanitizer.java
  src/main/java/net/dv8tion/jda/api/utils/cache/CacheView.java
  src/main/java/net/dv8tion/jda/api/utils/cache/SnowflakeCacheView.java
  src/main/java/net/dv8tion/jda/api/utils/cache/SortedSnowflakeCacheView.java
  src/main/java/net/dv8tion/jda/api/utils/concurrent/DelayedCompletableFuture.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/PrivateChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/EmptyRestAction.java
  src/main/java/net/dv8tion/jda/internal/requests/RestActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/AuditableRestActionImpl.java
Labels: size: small, status: in progress

#1022 Bump version to 4.BETA.0
  build.gradle.kts
Labels: release

#1020 Fix rate-limits for reactions (undocumented behavior)
  src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
  src/main/java/net/dv8tion/jda/internal/requests/Route.java
Labels: bug, size: small, type: discord issue

#981 Add bag accessors for mentions
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
Labels: priority: low, type: proposal

#1026 Use EnumMap where applicable
  src/main/java/net/dv8tion/jda/internal/entities/MemberImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/EventCache.java
Labels: size: small, type: enhancement

#1018 Add IconType enum to support more mime types in Icon
  src/main/java/net/dv8tion/jda/api/entities/Icon.java
Labels: size: small, type: enhancement

#1025 Deprecate Invite#getCreationTime in favor of Invite#getTimeCreated
  src/main/java/net/dv8tion/jda/api/entities/Invite.java
  src/main/java/net/dv8tion/jda/internal/entities/InviteImpl.java
Labels: size: small, type: enhancement

#1029 Remove the overriden "GuildImpl#getIconUrl()" implementation
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Labels: bug, size: small

#1027 Deprecate ShardManager#setGame
  src/main/java/net/dv8tion/jda/api/entities/Invite.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
Labels: size: small, type: enhancement

#1036 Ignore unknown message types
  src/main/java/net/dv8tion/jda/internal/handle/MessageCreateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/MessagePaginationActionImpl.java
Labels: bug, size: small

#1037 Backport bug fixes from v4
  src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/core/handle/MessageCreateHandler.java
  src/main/java/net/dv8tion/jda/core/handle/MessageUpdateHandler.java
  src/main/java/net/dv8tion/jda/core/managers/GuildController.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/pagination/MessagePaginationAction.java
Labels: bug, priority: high, size: small

#1033 Update ErrorResponse enum and references
  src/main/java/net/dv8tion/jda/api/entities/Category.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java
  src/main/java/net/dv8tion/jda/api/entities/Member.java
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/Role.java
  src/main/java/net/dv8tion/jda/api/entities/TextChannel.java
  src/main/java/net/dv8tion/jda/api/requests/ErrorResponse.java
Labels: size: small, type: enhancement

#1032 Mark getShardInfo() nonnull
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
  src/main/java/net/dv8tion/jda/api/utils/SessionController.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
Labels: size: small, type: enhancement

#1024 Add implementation for teams
  src/main/java/net/dv8tion/jda/api/entities/ApplicationInfo.java
  src/main/java/net/dv8tion/jda/api/entities/ApplicationTeam.java
  src/main/java/net/dv8tion/jda/api/entities/TeamMember.java
  src/main/java/net/dv8tion/jda/internal/entities/ApplicationInfoImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/ApplicationTeamImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/TeamMemberImpl.java
Labels: size: small, type: feature

#1035 Synchronize WebSocketFactory and use setServerName
  src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/internal/utils/IOUtil.java
Labels: size: small, type: enhancement
