Repository discord-jda/JDA, pull requests merged in 2019-11, with the labels that each got.

#1122 Add India and Europe regions
  src/main/java/net/dv8tion/jda/api/Region.java
Labels: size: small, type: feature

#1131 Improve documentation for reaction pagination
  src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/ReactionPaginationAction.java
Labels: size: small, type: enhancement

#1130 Add some documentation
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/entities/Activity.java
  src/main/java/net/dv8tion/jda/api/entities/ApplicationTeam.java
  src/main/java/net/dv8tion/jda/api/entities/Category.java
  src/main/java/net/dv8tion/jda/api/entities/Emote.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java
  src/main/java/net/dv8tion/jda/api/entities/GuildVoiceState.java
  src/main/java/net/dv8tion/jda/api/entities/IPermissionHolder.java
  src/main/java/net/dv8tion/jda/api/entities/Icon.java
  src/main/java/net/dv8tion/jda/api/entities/Invite.java
  src/main/java/net/dv8tion/jda/api/entities/ListedEmote.java
  src/main/java/net/dv8tion/jda/api/entities/Member.java
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/MessageActivity.java
  src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
  src/main/java/net/dv8tion/jda/api/entities/MessageEmbed.java
  src/main/java/net/dv8tion/jda/api/entities/MessageHistory.java
  src/main/java/net/dv8tion/jda/api/entities/MessageReaction.java
  src/main/java/net/dv8tion/jda/api/entities/PermissionOverride.java
  src/main/java/net/dv8tion/jda/api/entities/PrivateChannel.java
  src/main/java/net/dv8tion/jda/api/entities/RichPresence.java
  src/main/java/net/dv8tion/jda/api/entities/Role.java
  src/main/java/net/dv8tion/jda/api/entities/SelfUser.java
  src/main/java/net/dv8tion/jda/api/entities/StoreChannel.java
  src/main/java/net/dv8tion/jda/api/entities/TeamMember.java
  src/main/java/net/dv8tion/jda/api/entities/TextChannel.java
  src/main/java/net/dv8tion/jda/api/entities/User.java
  src/main/java/net/dv8tion/jda/api/entities/VoiceChannel.java
  src/main/java/net/dv8tion/jda/api/entities/Webhook.java
  src/main/java/net/dv8tion/jda/api/managers/ChannelManager.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/ChannelAction.java
Labels: size: small, type: enhancement

#1116 Add Member#getActiveClients()
  src/main/java/net/dv8tion/jda/api/entities/Member.java
  src/main/java/net/dv8tion/jda/internal/entities/MemberImpl.java
Labels: size: small, type: feature

#1128 Documentation Updates
  .github/CONTRIBUTING.md
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/JDABuilder.java
  src/main/java/net/dv8tion/jda/api/entities/Activity.java
  src/main/java/net/dv8tion/jda/api/entities/ApplicationTeam.java
  src/main/java/net/dv8tion/jda/api/entities/Category.java
  src/main/java/net/dv8tion/jda/api/entities/Emote.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java
  src/main/java/net/dv8tion/jda/api/entities/GuildVoiceState.java
  src/main/java/net/dv8tion/jda/api/entities/IPermissionHolder.java
  src/main/java/net/dv8tion/jda/api/entities/Icon.java
  src/main/java/net/dv8tion/jda/api/entities/Invite.java
  src/main/java/net/dv8tion/jda/api/entities/ListedEmote.java
  src/main/java/net/dv8tion/jda/api/entities/Member.java
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/MessageActivity.java
  src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
  src/main/java/net/dv8tion/jda/api/entities/MessageEmbed.java
  src/main/java/net/dv8tion/jda/api/entities/MessageHistory.java
  src/main/java/net/dv8tion/jda/api/entities/MessageReaction.java
  src/main/java/net/dv8tion/jda/api/entities/PermissionOverride.java
  src/main/java/net/dv8tion/jda/api/entities/PrivateChannel.java
  src/main/java/net/dv8tion/jda/api/entities/RichPresence.java
  src/main/java/net/dv8tion/jda/api/entities/Role.java
  src/main/java/net/dv8tion/jda/api/entities/SelfUser.java
  src/main/java/net/dv8tion/jda/api/entities/StoreChannel.java
  src/main/java/net/dv8tion/jda/api/entities/TeamMember.java
  src/main/java/net/dv8tion/jda/api/entities/TextChannel.java
  src/main/java/net/dv8tion/jda/api/entities/User.java
  src/main/java/net/dv8tion/jda/api/entities/VoiceChannel.java
  src/main/java/net/dv8tion/jda/api/entities/Webhook.java
  src/main/java/net/dv8tion/jda/api/events/ExceptionEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/EventListener.java
  src/main/java/net/dv8tion/jda/api/managers/ChannelManager.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/ChannelAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/ReactionPaginationAction.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/ChannelManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/ChannelActionImpl.java
Labels: Hacktoberfest

#1129 Add ErrorResponseException.ignore(...)
  src/main/java/net/dv8tion/jda/api/exceptions/ErrorResponseException.java
Labels: size: small, type: feature

#1143 EmoteManagerImpl#finalizeData resets the role list before serializing
  src/main/java/net/dv8tion/jda/internal/managers/EmoteManagerImpl.java
Labels: bug, size: small

#1140 Add support for webhook types
  src/main/java/net/dv8tion/jda/api/entities/Webhook.java
  src/main/java/net/dv8tion/jda/api/entities/WebhookType.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/WebhookImpl.java
Labels: size: small, type: feature

#1142 Add new audit log options
  src/main/java/net/dv8tion/jda/api/audit/ActionType.java
  src/main/java/net/dv8tion/jda/api/audit/AuditLogEntry.java
  src/main/java/net/dv8tion/jda/api/audit/AuditLogKey.java
  src/main/java/net/dv8tion/jda/api/audit/AuditLogOption.java
  src/main/java/net/dv8tion/jda/api/audit/TargetType.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
Labels: size: small, type: enhancement

#1126 Add readonly support for custom status
  src/main/java/net/dv8tion/jda/api/entities/Activity.java
  src/main/java/net/dv8tion/jda/internal/entities/ActivityImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/RichPresenceImpl.java
Labels: size: small, type: feature
