Repository discord-jda/JDA, pull requests merged in 2019-05, with the labels that each got.

#998 Use concurrent collections in AnnotatedEventManager
  src/main/java/net/dv8tion/jda/api/hooks/AnnotatedEventManager.java
Labels: bug, size: small

#996 Use enum for compression algorithm
  src/main/java/net/dv8tion/jda/api/JDABuilder.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/api/utils/Compression.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/internal/utils/compress/Decompressor.java
  src/main/java/net/dv8tion/jda/internal/utils/compress/ZlibDecompressor.java
  src/main/java/net/dv8tion/jda/internal/utils/config/sharding/ShardingMetaConfig.java
Labels: size: small, type: breaking, type: enhancement

#979 Modified JDALogger SLF4J detection to be able to detect both pre-1.8.x and 1.8.x+ providers
  src/main/java/net/dv8tion/jda/internal/utils/JDALogger.java
Labels: size: small, type: enhancement

#1003 Update embed album links
  src/main/java/net/dv8tion/jda/api/EmbedBuilder.java
  src/main/java/net/dv8tion/jda/api/entities/MessageEmbed.java
Labels: size: small, type: enhancement

#1000 Add voice kick handling that stops JDA from reconnecting
  src/main/java/net/dv8tion/jda/api/audio/hooks/ConnectionStatus.java
  src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java
  src/main/java/net/dv8tion/jda/internal/handle/ChannelDeleteHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/VoiceStateUpdateHandler.java
Labels: size: small, type: enhancement

#964 Add support for StoreChannel
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/entities/Category.java
  src/main/java/net/dv8tion/jda/api/entities/ChannelType.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java
  src/main/java/net/dv8tion/jda/api/entities/StoreChannel.java
  src/main/java/net/dv8tion/jda/api/entities/TextChannel.java
  src/main/java/net/dv8tion/jda/api/entities/VoiceChannel.java
  src/main/java/net/dv8tion/jda/api/events/channel/store/GenericStoreChannelEvent.java
  src/main/java/net/dv8tion/jda/api/events/channel/store/StoreChannelCreateEvent.java
  src/main/java/net/dv8tion/jda/api/events/channel/store/StoreChannelDeleteEvent.java
  src/main/java/net/dv8tion/jda/api/events/channel/store/update/GenericStoreChannelUpdateEvent.java
  src/main/java/net/dv8tion/jda/api/events/channel/store/update/StoreChannelUpdateNameEvent.java
  src/main/java/net/dv8tion/jda/api/events/channel/store/update/StoreChannelUpdatePermissionsEvent.java
  src/main/java/net/dv8tion/jda/api/events/channel/store/update/StoreChannelUpdatePositionEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/api/managers/GuildController.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/order/CategoryOrderAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/order/ChannelOrderAction.java
  src/main/java/net/dv8tion/jda/api/utils/cache/SortedSnowflakeCacheView.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/AbstractChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/CategoryImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/StoreChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/VoiceChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/ChannelCreateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/ChannelDeleteHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/ChannelUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildDeleteHandler.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/order/CategoryOrderActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/order/ChannelOrderActionImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/cache/SortedSnowflakeCacheViewImpl.java
Labels: priority: high, size: medium, type: breaking, type: discord issue

#1007 Add getGuildChannelById methods
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
Labels: size: small, type: feature

#966 Remove GuildController
  build.gradle.kts
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/Member.java
  src/main/java/net/dv8tion/jda/api/managers/ChannelManager.java
  src/main/java/net/dv8tion/jda/api/managers/GuildController.java
  src/main/java/net/dv8tion/jda/api/requests/ErrorResponse.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/AuditableRestAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/ChannelAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/RoleAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/order/ChannelOrderAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/order/RoleOrderAction.java
  src/main/java/net/dv8tion/jda/internal/entities/CategoryImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/RoleImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/VoiceChannelImpl.java
Labels: size: large, type: breaking, type: enhancement
