Repository discord-jda/JDA, pull requests merged in 2019-07, with the labels that each got.

#1031 Add EventManagerProxy
  src/main/java/net/dv8tion/jda/api/hooks/IEventManager.java
  src/main/java/net/dv8tion/jda/api/requests/Request.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/audio/AudioConnection.java
  src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java
  src/main/java/net/dv8tion/jda/internal/handle/ChannelCreateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/ChannelDeleteHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/ChannelUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildBanHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildCreateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildDeleteHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildEmojisUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildMemberAddHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildMemberRemoveHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildMemberUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildRoleCreateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildRoleDeleteHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildRoleUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildSetupNode.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageBulkDeleteHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageCreateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageDeleteHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageReactionBulkRemoveHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageReactionHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/PresenceUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/TypingStartHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/UserUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/VoiceStateUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/hooks/EventManagerProxy.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/internal/requests/ratelimit/BotRateLimiter.java
  src/main/java/net/dv8tion/jda/internal/requests/ratelimit/ClientRateLimiter.java
Labels: size: small, type: enhancement

#1028 Add GatewayPingEvent
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/events/GatewayPingEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
Labels: size: small, type: feature

#1045 Cleanup Helpers utility
  src/main/java/net/dv8tion/jda/internal/utils/Helpers.java
  src/test/java/HelpersTest.java
Labels: size: small

#1044 Update .editorconfig with intellij settings
  .editorconfig
  build.gradle.kts
Labels: size: small

#1040 Use enqueue instead of execute for HTTP requests
  src/main/java/net/dv8tion/jda/internal/requests/FunctionalCallback.java
  src/main/java/net/dv8tion/jda/internal/requests/Requester.java
  src/main/java/net/dv8tion/jda/internal/requests/ratelimit/BotRateLimiter.java
  src/main/java/net/dv8tion/jda/internal/requests/ratelimit/ClientRateLimiter.java
Labels: size: small, type: enhancement

#1052 Add javadoc desc for the INVISIBLE const of the OnlineStatus enum
  src/main/java/net/dv8tion/jda/api/OnlineStatus.java
Labels: size: small, type: enhancement

#1059 Fix check for downloadToFile and add trace logging for requests
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/utils/IOBiConsumer.java
  src/main/java/net/dv8tion/jda/internal/requests/FunctionalCallback.java
  src/main/java/net/dv8tion/jda/internal/requests/Requester.java
Labels: bug, size: small

#1051 Cleanup udp discovery code
  src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java
  src/main/java/net/dv8tion/jda/internal/utils/IOUtil.java
Labels: size: small, type: enhancement

#1063 Remove two redundant checks
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
Labels: size: small, type: enhancement

#1060 Adding StoreChannel cache access methods to ShardManager
  src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
Labels: size: small, type: enhancement

#1057 Update documentation to remove references to internals
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/OnlineStatus.java
  src/main/java/net/dv8tion/jda/api/Permission.java
  src/main/java/net/dv8tion/jda/api/audio/hooks/package-info.java
  src/main/java/net/dv8tion/jda/api/entities/Emote.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/Icon.java
  src/main/java/net/dv8tion/jda/api/entities/Member.java
  src/main/java/net/dv8tion/jda/api/entities/Role.java
  src/main/java/net/dv8tion/jda/api/exceptions/RateLimitedException.java
  src/main/java/net/dv8tion/jda/api/requests/CloseCode.java
  src/main/java/net/dv8tion/jda/api/requests/RestAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/AuditLogPaginationAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/MessagePaginationAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/ReactionPaginationAction.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java
  src/main/java/net/dv8tion/jda/api/utils/SessionController.java
  src/main/java/net/dv8tion/jda/api/utils/SessionControllerAdapter.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
Labels: size: small, type: enhancement

#1034 Update README
  README.md
Labels: size: small, type: enhancement

#1067 Fix xsalsa20_poly1305 encryption
  src/main/java/net/dv8tion/jda/internal/audio/AudioPacket.java
Labels: bug, size: small
