Repository discord-jda/JDA, pull requests merged in 2019-01, with the labels that each got.

#859 Add methods to use stream in secured environment
  src/main/java/net/dv8tion/jda/api/utils/cache/CacheView.java
Labels: status: completed, type: feature

#849 [Feature] Create User#getAsTag
  src/main/java/net/dv8tion/jda/core/entities/User.java
  src/main/java/net/dv8tion/jda/core/entities/impl/UserImpl.java
Labels: type: feature

#793 Read-only MessageActivity support.
  src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/core/entities/Message.java
  src/main/java/net/dv8tion/jda/core/entities/MessageActivity.java
  src/main/java/net/dv8tion/jda/core/entities/impl/DataMessage.java
  src/main/java/net/dv8tion/jda/core/entities/impl/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/core/entities/impl/SystemMessage.java
Labels: type: feature

#871 Rename getter to be consistent with setter
  src/main/java/net/dv8tion/jda/api/managers/AudioManager.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildSetupNode.java
  src/main/java/net/dv8tion/jda/internal/managers/AudioManagerImpl.java
Labels: type: breaking, type: enhancement

#862 Add getRestPing and rename getPing to getGatewayPing
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
Labels: type: breaking, type: feature

#877 Fixed a refactoring issue with PermissionOverride not being Auditable.
  src/main/java/net/dv8tion/jda/api/requests/restaction/PermissionOverrideAction.java
Labels: bug

#882 Add Automatic-Module-Name for jigsaw
  build.gradle
Labels: type: enhancement, type: jre issue

#887 Add MESSAGE_ADD_REACTION to text only permissions
  src/main/java/net/dv8tion/jda/core/Permission.java
Labels: bug

#888 Invert dependencies of text/voice only property
  src/main/java/net/dv8tion/jda/api/Permission.java
Labels: type: enhancement

#894 Improve equality contracts of JDA entities
  src/main/java/net/dv8tion/jda/internal/entities/AbstractChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/ActivityImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/EmoteImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildVoiceStateImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/InviteImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/MemberImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/PermissionOverrideImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/PrivateChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/RoleImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/UserImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/WebhookImpl.java
Labels: size: small, type: enhancement

#896 Ignore alpha when comparing colors in MessageEmbed
  src/main/java/net/dv8tion/jda/core/entities/MessageEmbed.java
Labels: size: small, type: enhancement

#898 Use the same route for removing own reaction
  src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
  src/main/java/net/dv8tion/jda/api/entities/MessageReaction.java
  src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/Route.java
Labels: bug, size: small, type: discord issue

#895 Consistent handling of isEmpty logic in embeds
  src/main/java/net/dv8tion/jda/api/EmbedBuilder.java
  src/main/java/net/dv8tion/jda/api/entities/MessageEmbed.java
Labels: bug, size: small

#900 Convert to Kotlin-DSL
  build.gradle
  build.gradle.kts
  javadoc-options.txt
  settings.gradle
  settings.gradle.kts
Labels: size: medium, type: enhancement, type: proposal
