Repository discord-jda/JDA, pull requests merged in 2019-04, with the labels that each got.

#950 Avoid losing entities skipped by forEachAsync iteration
  src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/AuditLogPaginationAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/MessagePaginationAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/PaginationAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/ReactionPaginationAction.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/AuditLogPaginationActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/MessagePaginationActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/PaginationActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/ReactionPaginationActionImpl.java
Labels: size: small, type: enhancement

#972 Add method to easily get the beginning history of a MessageChannel
  src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
  src/main/java/net/dv8tion/jda/api/entities/MessageHistory.java
Labels: size: small, type: feature

#980 Added EmbedBuilder#setFooter for convenience
  src/main/java/net/dv8tion/jda/api/EmbedBuilder.java
Labels: size: small, type: enhancement

#983 Use mark to get correct content of http response in getBody
  src/main/java/net/dv8tion/jda/internal/requests/Requester.java
Labels: size: small, type: enhancement

#987 Change delta for escaped sequences
  src/main/java/net/dv8tion/jda/api/utils/MarkdownSanitizer.java
Labels: bug

#988 Slowmode update
  src/main/java/net/dv8tion/jda/core/entities/TextChannel.java
  src/main/java/net/dv8tion/jda/core/managers/ChannelManager.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/ChannelAction.java
Labels: size: small, type: enhancement

#989 Update slowmode limit to 6 hours
  src/main/java/net/dv8tion/jda/api/entities/TextChannel.java
  src/main/java/net/dv8tion/jda/api/managers/ChannelManager.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/ChannelAction.java
  src/main/java/net/dv8tion/jda/internal/managers/ChannelManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/ChannelActionImpl.java
Labels: size: small, type: enhancement

#991 Use buffer for file uploads to fix duplicated requests
  src/main/java/net/dv8tion/jda/api/utils/MiscUtil.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/BufferedRequestBody.java
  src/main/java/net/dv8tion/jda/internal/utils/IOUtil.java
Labels: bug, size: small, type: breaking

#992 Create GuildMemberUpdateEvent hierarchy
  src/main/java/net/dv8tion/jda/api/events/guild/member/update/GenericGuildMemberUpdateEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/member/update/GuildMemberUpdateNicknameEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildMemberUpdateHandler.java
Labels: size: small, type: breaking, type: enhancement

#913 Add attachment options to apply to files
  src/main/java/net/dv8tion/jda/api/EmbedBuilder.java
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/MessageAction.java
  src/main/java/net/dv8tion/jda/api/utils/AttachmentOption.java
  src/main/java/net/dv8tion/jda/internal/entities/PrivateChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java
Labels: size: small, type: breaking, type: feature

#971 AudioReceiveHandler#includeUserInCombinedAudio
  src/main/java/net/dv8tion/jda/api/audio/AudioReceiveHandler.java
  src/main/java/net/dv8tion/jda/internal/audio/AudioConnection.java
Labels: size: small, type: feature

#997 Retry requests on SocketException
  src/main/java/net/dv8tion/jda/internal/requests/Requester.java
Labels: size: small, type: enhancement
