Repository discord-jda/JDA, pull requests merged in 2019-02, with the labels that each got.

#876 Use configs for JDA constructor
  src/main/java/net/dv8tion/jda/api/JDABuilder.java
  src/main/java/net/dv8tion/jda/api/requests/RestAction.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/Requester.java
  src/main/java/net/dv8tion/jda/internal/utils/config/AuthorizationConfig.java
  src/main/java/net/dv8tion/jda/internal/utils/config/MetaConfig.java
  src/main/java/net/dv8tion/jda/internal/utils/config/SessionConfig.java
  src/main/java/net/dv8tion/jda/internal/utils/config/ThreadingConfig.java
  src/main/java/net/dv8tion/jda/internal/utils/config/sharding/EventConfig.java
  src/main/java/net/dv8tion/jda/internal/utils/config/sharding/PresenceProviderConfig.java
  src/main/java/net/dv8tion/jda/internal/utils/config/sharding/ShardingConfig.java
  src/main/java/net/dv8tion/jda/internal/utils/config/sharding/ShardingMetaConfig.java
  src/main/java/net/dv8tion/jda/internal/utils/config/sharding/ShardingSessionConfig.java
  src/main/java/net/dv8tion/jda/internal/utils/config/sharding/ThreadingProviderConfig.java
Labels: priority: high, size: medium, status: completed, type: breaking, type: enhancement

#905 Add correct boundaries to api methods in CacheView
  src/main/java/net/dv8tion/jda/api/utils/cache/CacheView.java
  src/main/java/net/dv8tion/jda/internal/utils/cache/ShardCacheViewImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/cache/UnifiedCacheViewImpl.java
Labels: size: small, type: enhancement

#880 Improve submitAfter to not depend on complete
  src/main/java/net/dv8tion/jda/api/requests/RestAction.java
  src/main/java/net/dv8tion/jda/api/utils/concurrent/DelayedCompletableFuture.java
Labels: size: small, status: completed, type: enhancement

#903 Add takeUntilAsync
  src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/PaginationAction.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/PaginationActionImpl.java
Labels: size: small, status: completed, type: feature

#899 Use OkHTTP3 snapshot
  README.md
  build.gradle
Labels: size: small, type: proposal

#867 Release 3.8.2
  README.md
  build.gradle
  src/main/java/net/dv8tion/jda/bot/sharding/DefaultShardManager.java
  src/main/java/net/dv8tion/jda/bot/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/bot/sharding/ShardManager.java
  src/main/java/net/dv8tion/jda/core/MessageBuilder.java
  src/main/java/net/dv8tion/jda/core/Permission.java
  src/main/java/net/dv8tion/jda/core/audio/AudioPacket.java
  src/main/java/net/dv8tion/jda/core/audio/AudioWebSocket.java
  src/main/java/net/dv8tion/jda/core/entities/Channel.java
  src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/core/entities/Guild.java
  src/main/java/net/dv8tion/jda/core/entities/Message.java
  src/main/java/net/dv8tion/jda/core/entities/MessageActivity.java
  src/main/java/net/dv8tion/jda/core/entities/MessageEmbed.java
  src/main/java/net/dv8tion/jda/core/entities/User.java
  src/main/java/net/dv8tion/jda/core/entities/impl/DataMessage.java
  src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java
  src/main/java/net/dv8tion/jda/core/entities/impl/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/core/entities/impl/SystemMessage.java
  src/main/java/net/dv8tion/jda/core/entities/impl/TextChannelImpl.java
  src/main/java/net/dv8tion/jda/core/entities/impl/UserImpl.java
  src/main/java/net/dv8tion/jda/core/events/guild/GuildJoinEvent.java
  src/main/java/net/dv8tion/jda/core/events/message/MessageBulkDeleteEvent.java
  src/main/java/net/dv8tion/jda/core/exceptions/ErrorResponseException.java
  src/main/java/net/dv8tion/jda/core/handle/VoiceStateUpdateHandler.java
  src/main/java/net/dv8tion/jda/core/managers/GuildController.java
  src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/core/requests/restaction/ChannelAction.java
  src/main/java/net/dv8tion/jda/core/utils/PermissionUtil.java
Labels: release

#863 Improve IPermissionHolder and PermissionOverrideAction
  src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java
  src/main/java/net/dv8tion/jda/api/entities/IPermissionHolder.java
  src/main/java/net/dv8tion/jda/api/entities/Member.java
  src/main/java/net/dv8tion/jda/api/managers/ChannelManager.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/PermissionOverrideAction.java
  src/main/java/net/dv8tion/jda/internal/entities/AbstractChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/MemberImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/PermOverrideData.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/PermissionOverrideActionImpl.java
Labels: size: small, type: enhancement

#860 Add VoiceDispatchInterceptor
  build.gradle.kts
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/JDABuilder.java
  src/main/java/net/dv8tion/jda/api/hooks/VoiceDispatchInterceptor.java
  src/main/java/net/dv8tion/jda/api/managers/AudioManager.java
  src/main/java/net/dv8tion/jda/api/managers/DirectAudioController.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java
  src/main/java/net/dv8tion/jda/internal/handle/VoiceServerUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/VoiceStateUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/managers/AudioManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/DirectAudioControllerImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/config/SessionConfig.java
  src/main/java/net/dv8tion/jda/internal/utils/config/sharding/ShardingConfig.java
  src/main/java/net/dv8tion/jda/internal/utils/config/sharding/ShardingSessionConfig.java
Labels: priority: low, size: medium, status: completed, type: feature

#918 Add links to external references in javadoc
  build.gradle.kts
  javadoc-options.txt
Labels: size: small, status: completed, type: enhancement

#914 Added spoilers to Message#getContentStripped
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
Labels: size: small, type: enhancement

#928 Add release flag to compiler arguments when available
  build.gradle.kts
Labels: size: small

#908 Don't catch rejection of worker schedule
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java
  src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
Labels: bug, size: small

#924 Throw AccountTypeException when attempting to get application of client
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
Labels: bug, size: small, type: enhancement

#922 Introduce GenericEvent interface for better abstraction
  src/main/java/net/dv8tion/jda/api/events/Event.java
  src/main/java/net/dv8tion/jda/api/events/GenericEvent.java
  src/main/java/net/dv8tion/jda/api/events/UpdateEvent.java
  src/main/java/net/dv8tion/jda/api/events/user/update/GenericUserPresenceEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/AnnotatedEventManager.java
  src/main/java/net/dv8tion/jda/api/hooks/EventListener.java
  src/main/java/net/dv8tion/jda/api/hooks/IEventManager.java
  src/main/java/net/dv8tion/jda/api/hooks/InterfacedEventManager.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
Labels: size: small, type: breaking, type: enhancement

#912 Make MemberCacheView extend SnowflakeCacheView
  src/main/java/net/dv8tion/jda/api/utils/cache/MemberCacheView.java
  src/main/java/net/dv8tion/jda/internal/utils/cache/MemberCacheViewImpl.java
Labels: size: small, type: enhancement

#929 Make IMentionable extend ISnowflake
  src/main/java/net/dv8tion/jda/api/entities/Emote.java
  src/main/java/net/dv8tion/jda/api/entities/IMentionable.java
  src/main/java/net/dv8tion/jda/api/entities/Member.java
  src/main/java/net/dv8tion/jda/api/entities/Role.java
  src/main/java/net/dv8tion/jda/api/entities/User.java
  src/main/java/net/dv8tion/jda/api/utils/WidgetUtil.java
Labels: size: small, type: enhancement

#891 Rename methods used to retrieve entities
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/audit/package-info.java
  src/main/java/net/dv8tion/jda/api/entities/ApplicationInfo.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java
  src/main/java/net/dv8tion/jda/api/entities/Invite.java
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
  src/main/java/net/dv8tion/jda/api/entities/MessageHistory.java
  src/main/java/net/dv8tion/jda/api/entities/MessageReaction.java
  src/main/java/net/dv8tion/jda/api/entities/TextChannel.java
  src/main/java/net/dv8tion/jda/api/managers/GuildController.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/AuditableRestAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/AuditLogPaginationAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/ReactionPaginationAction.java
  src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/AbstractChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/CategoryImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
Labels: size: small, type: breaking, type: enhancement

#915 Ensure the ChainedClosableIterator does not produce duplicates
  src/main/java/net/dv8tion/jda/internal/utils/ChainedClosableIterator.java
  src/main/java/net/dv8tion/jda/internal/utils/cache/UnifiedCacheViewImpl.java
Labels: bug, priority: high, size: small, status: completed

#921 Use ByteBuffer for sending audio
  src/examples/java/AudioEchoExample.java
  src/main/java/net/dv8tion/jda/api/audio/AudioSendHandler.java
  src/main/java/net/dv8tion/jda/api/audio/factory/IPacketProvider.java
  src/main/java/net/dv8tion/jda/internal/audio/AudioConnection.java
  src/main/java/net/dv8tion/jda/internal/audio/AudioPacket.java
  src/main/java/net/dv8tion/jda/internal/audio/Decoder.java
Labels: size: small, type: breaking, type: enhancement

#933 Enforce non-null attachment urls
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
Labels: size: small, status: completed, type: enhancement

#917 Replace PermOverrideManager with PermissionOverrideAction
  src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java
  src/main/java/net/dv8tion/jda/api/entities/PermissionOverride.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/PermissionOverrideAction.java
  src/main/java/net/dv8tion/jda/internal/entities/PermissionOverrideImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/PermissionOverrideActionImpl.java
Labels: size: small, status: completed, type: breaking, type: enhancement

#944 Trim field value and name
  src/main/java/net/dv8tion/jda/api/entities/MessageEmbed.java
Labels: size: small, type: enhancement

#942 Check whether content-length is long enough for gzip data
  src/main/java/net/dv8tion/jda/internal/requests/Requester.java
Labels: size: small, type: enhancement

#943 Add getUserByTag
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/User.java
  src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Labels: size: small, status: completed, type: feature
