Repository discord-jda/JDA, pull requests merged in 2019-08, with the labels that each got.

#1061 Improve handling of webhooks without tokens
  src/main/java/net/dv8tion/jda/api/entities/Webhook.java
  src/main/java/net/dv8tion/jda/api/requests/ErrorResponse.java
  src/main/java/net/dv8tion/jda/internal/entities/WebhookImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/ratelimit/BotRateLimiter.java
Labels: size: small, type: enhancement

#1073 Improve some documentation
  src/main/java/net/dv8tion/jda/api/AccountType.java
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/entities/Emote.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/events/DisconnectEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/GuildAvailableEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/GuildReadyEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/GuildUnavailableEvent.java
  src/main/java/net/dv8tion/jda/api/events/user/update/UserUpdateActivityOrderEvent.java
  src/main/java/net/dv8tion/jda/api/events/user/update/UserUpdateOnlineStatusEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/InterfacedEventManager.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/api/requests/ErrorResponse.java
  src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
Labels: size: small, type: enhancement

#1062 Add quote handling and MarkdownUtil
  src/main/java/net/dv8tion/jda/api/utils/MarkdownSanitizer.java
  src/main/java/net/dv8tion/jda/api/utils/MarkdownUtil.java
  src/test/java/MarkdownTest.java
  src/test/java/MarkdownUtilTest.java
Labels: size: small, type: feature

#1048 Add a minimized jar
  build.gradle.kts
Labels: requires testing, size: small

#1076 Add Guild#getMaxEmotes and BoostTier#getMaxEmotes
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
Labels: size: small, type: feature

#1084 Add VOICE_STREAM permission
  src/main/java/net/dv8tion/jda/api/Permission.java
Labels: size: small, type: feature

#1085 Add Lavalink to recommendations
  README.md
Labels: size: small

#1080 Improve handling of Guild#getMaxEmotes
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
Labels: size: small, type: enhancement

#1081 Implement X-RateLimit-Precision handling
  src/main/java/net/dv8tion/jda/api/JDABuilder.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/Requester.java
  src/main/java/net/dv8tion/jda/internal/requests/Route.java
  src/main/java/net/dv8tion/jda/internal/requests/ratelimit/BotRateLimiter.java
  src/main/java/net/dv8tion/jda/internal/requests/ratelimit/ClientRateLimiter.java
  src/main/java/net/dv8tion/jda/internal/requests/ratelimit/IBucket.java
  src/main/java/net/dv8tion/jda/internal/utils/config/SessionConfig.java
  src/main/java/net/dv8tion/jda/internal/utils/config/flags/ConfigFlag.java
Labels: size: small, type: enhancement

#1087 Fix BOLD | ITALICS_A not getting escaped properly in MarkdownSanitizer (#1086)
  build.gradle.kts
  src/main/java/net/dv8tion/jda/api/utils/MarkdownSanitizer.java
  src/test/java/MarkdownTest.java
  src/test/java/MarkdownUtilTest.java
Labels: requires testing, size: small
