Repository discord-jda/JDA, pull requests merged in 2019-10, with the labels that each got.

#1111 Fix store channel cache invalidation
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
Labels: bug, size: small

#1112 Remove Voice channel from JDA cache on deletion
  src/main/java/net/dv8tion/jda/internal/handle/ChannelDeleteHandler.java
Labels: bug, size: small

#1121 Promote commons-collections4 to an API dependency (#1120)
  build.gradle.kts
Labels: bug

#1113 isImage fix, addition of hasImage (fixes #1071)
  src/main/java/net/dv8tion/jda/api/entities/Message.java
Labels: bug, size: small

#1115 Rename LURKABLE feature and fix usage of VIP_REGIONS
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
Labels: bug, size: small

#1118 Add an upper limit to prune and retrievePrunableMemberCount
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Labels: size: small, type: enhancement

#1114 Fix for removing an emoji reaction in codepoint style
  src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
  src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/EncodingUtil.java
Labels: bug, size: small

#1108 Create constant for max slowmode
  src/main/java/net/dv8tion/jda/api/entities/TextChannel.java
  src/main/java/net/dv8tion/jda/api/managers/ChannelManager.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/ChannelAction.java
  src/main/java/net/dv8tion/jda/internal/managers/ChannelManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/ChannelActionImpl.java
Labels: size: small, type: enhancement
