Repository discord-jda/JDA, pull requests merged in 2019-03, with the labels that each got.

#911 Remove old sendFile overloads in favor of better maintainability
  src/main/java/net/dv8tion/jda/api/EmbedBuilder.java
  src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/MessageAction.java
  src/main/java/net/dv8tion/jda/internal/entities/PrivateChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
Labels: size: small, status: completed, type: breaking, type: enhancement

#930 Add MarkdownSanitizer
  build.gradle.kts
  src/main/java/net/dv8tion/jda/api/utils/MarkdownSanitizer.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
  src/test/java/MarkdownTest.java
Labels: size: medium, status: completed, type: feature

#938 Add ability to set speaking delay in audio manager
  src/main/java/net/dv8tion/jda/api/managers/AudioManager.java
  src/main/java/net/dv8tion/jda/internal/audio/AudioConnection.java
  src/main/java/net/dv8tion/jda/internal/managers/AudioManagerImpl.java
Labels: size: small, status: completed, type: feature

#951 Forcibly request chunks again when caching too many events
  src/main/java/net/dv8tion/jda/internal/handle/GuildSetupController.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildSetupNode.java
Labels: size: small

#956 Add news channel type, just handle like text for now
  src/main/java/net/dv8tion/jda/core/entities/ChannelType.java
  src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/core/handle/ChannelCreateHandler.java
  src/main/java/net/dv8tion/jda/core/handle/ChannelDeleteHandler.java
  src/main/java/net/dv8tion/jda/core/handle/ChannelUpdateHandler.java
  src/main/java/net/dv8tion/jda/core/handle/MessageCreateHandler.java
  src/main/java/net/dv8tion/jda/core/handle/MessageReactionBulkRemoveHandler.java
  src/main/java/net/dv8tion/jda/core/handle/MessageReactionHandler.java
  src/main/java/net/dv8tion/jda/core/handle/MessageUpdateHandler.java
Labels: bug, priority: high, size: small, type: discord issue

#916 Make reactions more intuitive
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
  src/main/java/net/dv8tion/jda/api/entities/MessageReaction.java
  src/main/java/net/dv8tion/jda/api/managers/GuildController.java
  src/main/java/net/dv8tion/jda/api/utils/MiscUtil.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageReactionHandler.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/AuditableRestActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/ReactionPaginationActionImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/EncodingUtil.java
Labels: size: small, status: completed, type: enhancement

#962 Handle immediately closed regions and properly supply afterIndex
  src/main/java/net/dv8tion/jda/api/utils/MarkdownSanitizer.java
  src/test/java/MarkdownTest.java
Labels: bug

#940 Make cover_image nullable in MessageApplication
  src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/core/entities/MessageActivity.java
Labels: bug, size: small, type: discord issue

#954 Change limit for role names to 100
  src/main/java/net/dv8tion/jda/api/managers/RoleManager.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/RoleAction.java
  src/main/java/net/dv8tion/jda/internal/managers/RoleManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/RoleActionImpl.java
Labels: size: small, type: enhancement

#936 Improve attachment retrieval by only offering async variants
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/utils/MiscUtil.java
  src/main/java/net/dv8tion/jda/api/utils/WidgetUtil.java
  src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java
  src/main/java/net/dv8tion/jda/internal/requests/Requester.java
  src/main/java/net/dv8tion/jda/internal/requests/ratelimit/BotRateLimiter.java
  src/main/java/net/dv8tion/jda/internal/requests/ratelimit/ClientRateLimiter.java
  src/main/java/net/dv8tion/jda/internal/utils/IOUtil.java
Labels: size: small, type: breaking

#960 Handle news channels
  src/main/java/net/dv8tion/jda/api/entities/ChannelType.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/handle/ChannelUpdateHandler.java
Labels: priority: high, size: small

#952 Add PermissionOverrideAction#clear
  src/main/java/net/dv8tion/jda/api/requests/restaction/PermissionOverrideAction.java
Labels: size: small, type: feature

#902 Add ClientType enum for client_status support
  src/main/java/net/dv8tion/jda/api/entities/ClientType.java
  src/main/java/net/dv8tion/jda/api/entities/Member.java
  src/main/java/net/dv8tion/jda/api/utils/cache/CacheFlag.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/MemberImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/PresenceUpdateHandler.java
Labels: priority: low, size: small

#970 Rename GuildMemberNickChangeEvent to GuildMemberUpdateNicknameEvent
  src/main/java/net/dv8tion/jda/api/events/guild/member/GuildMemberUpdateNicknameEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildMemberUpdateHandler.java
Labels: size: small, type: breaking

#958 Add message activity/application
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/MessageActivity.java
  src/main/java/net/dv8tion/jda/internal/entities/DataMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/SystemMessage.java
Labels: size: small, type: feature
