Repository discord-jda/JDA, pull requests merged in 2020-04, with the labels that each got.

#1216 Adding a check in reaction methods before calling getTextChannel()
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
Labels: size: small, type: enhancement

#1223 Add JDA#cancelRequests
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/requests/Request.java
  src/main/java/net/dv8tion/jda/api/requests/RestFuture.java
  src/main/java/net/dv8tion/jda/api/utils/SessionControllerAdapter.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/RateLimiter.java
  src/main/java/net/dv8tion/jda/internal/requests/Requester.java
  src/main/java/net/dv8tion/jda/internal/requests/RestActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/ratelimit/BotRateLimiter.java
  src/main/java/net/dv8tion/jda/internal/requests/ratelimit/ClientRateLimiter.java
Labels: size: small, type: feature

#1247 Add GuildVoiceStreamEvent
  src/main/java/net/dv8tion/jda/api/entities/GuildVoiceState.java
  src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceStreamEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildVoiceStateImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/VoiceStateUpdateHandler.java
Labels: size: small, type: feature

#1250 Change reconnect code to 4900 to avoid confusion
  src/main/java/net/dv8tion/jda/api/requests/CloseCode.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketSendingThread.java
Labels: size: small, type: enhancement

#1236 Add MessageChannel#retrieveReactionUsersById and update reaction related docs
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
  src/main/java/net/dv8tion/jda/api/entities/TextChannel.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/ReactionPaginationAction.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/ReactionPaginationActionImpl.java
Labels: size: small, type: enhancement

#1244 Add Guild#getMaxFileSize and Guild.BoostTier#getMaxFileSize
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
  src/main/java/net/dv8tion/jda/internal/entities/PrivateChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java
Labels: size: small, type: feature

#1219 Add fallback operators onErrorMap and onErrorFlatMap to RestAction
  src/main/java/net/dv8tion/jda/api/exceptions/ContextException.java
  src/main/java/net/dv8tion/jda/api/requests/ErrorResponse.java
  src/main/java/net/dv8tion/jda/api/requests/RestAction.java
  src/main/java/net/dv8tion/jda/internal/requests/RestActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/operator/FlatMapErrorRestAction.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/operator/FlatMapRestAction.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/operator/MapErrorRestAction.java
  src/main/java/net/dv8tion/jda/internal/utils/Checks.java
  src/main/java/net/dv8tion/jda/internal/utils/Helpers.java
Labels: size: small, type: feature

#1260 Fix incorrect size check for MessageChannel#sendFile
  src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
  src/main/java/net/dv8tion/jda/internal/entities/PrivateChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
Labels: bug, size: small

#1267 Json Parsing Optimizations
  src/main/java/net/dv8tion/jda/api/utils/data/DataArray.java
  src/main/java/net/dv8tion/jda/api/utils/data/DataObject.java
  src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java
  src/main/java/net/dv8tion/jda/internal/requests/RestActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/compress/Decompressor.java
  src/main/java/net/dv8tion/jda/internal/utils/compress/ZlibDecompressor.java
Labels: size: small, type: enhancement

#1278 Remove initial reconnect delay for resumes
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
Labels: size: small, type: enhancement

#1279 Add prune overload to disable wait parameter
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Labels: size: small, type: feature
