Repository discord-jda/JDA, pull requests merged in 2020-08, with the labels that each got.

#1334 Add UserById wrapper
  src/main/java/net/dv8tion/jda/api/entities/User.java
  src/main/java/net/dv8tion/jda/internal/entities/UserById.java
  src/main/java/net/dv8tion/jda/internal/entities/UserImpl.java
Labels: size: small, type: feature

#1358 Make StoreChannel implement IMentionable
  src/main/java/net/dv8tion/jda/api/entities/StoreChannel.java
  src/main/java/net/dv8tion/jda/internal/entities/StoreChannelImpl.java
Labels: size: small, type: feature

#1355 Handle cloudflare rate limits
  src/main/java/net/dv8tion/jda/internal/requests/ratelimit/BotRateLimiter.java
Labels: size: small, type: enhancement

#1359 Add support for guild locale
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateLocaleEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildUpdateHandler.java
Labels: size: small, type: feature

#1364 Add some convenience methods to GenericGuildMessageReactionEvent
  src/main/java/net/dv8tion/jda/api/events/message/guild/react/GenericGuildMessageReactionEvent.java
  src/main/java/net/dv8tion/jda/api/events/message/priv/react/GenericPrivateMessageReactionEvent.java
  src/main/java/net/dv8tion/jda/api/events/message/priv/react/PrivateMessageReactionAddEvent.java
  src/main/java/net/dv8tion/jda/api/events/message/priv/react/PrivateMessageReactionRemoveEvent.java
  src/main/java/net/dv8tion/jda/api/events/message/react/GenericMessageReactionEvent.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageReactionHandler.java
Labels: size: small, type: feature

#1344 Replace SnowflakeReference
  src/main/java/net/dv8tion/jda/internal/entities/AbstractChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/EmoteImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildVoiceStateImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/MemberImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/PermissionOverrideImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/RoleImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/ChannelManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/GuildManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/PermOverrideManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/RoleManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/cache/SnowflakeReference.java
Labels: size: small, type: enhancement

#1320 Implement RestAction#and operator
  src/main/java/net/dv8tion/jda/api/requests/RestAction.java
  src/main/java/net/dv8tion/jda/api/utils/Result.java
  src/main/java/net/dv8tion/jda/internal/requests/DeferredRestAction.java
  src/main/java/net/dv8tion/jda/internal/requests/RestActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/operator/CombineRestAction.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/operator/RestActionOperator.java
Labels: size: medium, type: feature

#1362 Implement support for news channels
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/TextChannel.java
  src/main/java/net/dv8tion/jda/api/events/channel/text/update/TextChannelUpdateNewsEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/api/requests/ErrorResponse.java
  src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/ChannelUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/requests/Route.java
Labels: size: small, status: freezer, type: feature
