Repository discord-jda/JDA, pull requests merged in 2020-06, with the labels that each got.

#1308 Only use interrupts when we recover zombie connections
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
Labels: size: small, type: enhancement

#1293 Implement max_concurrency in SessionController
  src/main/java/net/dv8tion/jda/api/JDABuilder.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java
  src/main/java/net/dv8tion/jda/api/utils/ConcurrentSessionController.java
  src/main/java/net/dv8tion/jda/api/utils/SessionController.java
  src/main/java/net/dv8tion/jda/api/utils/SessionControllerAdapter.java
  src/main/java/net/dv8tion/jda/internal/utils/config/SessionConfig.java
Labels: size: small, type: feature

#1307 Add some convenience methods to reaction events
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/events/message/react/GenericMessageReactionEvent.java
Labels: size: small, type: feature

#1263 Add ReactionEmote#getAsReactionCode method
  src/main/java/net/dv8tion/jda/api/entities/MessageReaction.java
Labels: size: small, type: feature

#1314 Remove duplicate roles when using "Guild.modifyMemberRoles(...)"
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Labels: bug, size: small

#1225 Feature: Mention Parsing
  src/main/java/net/dv8tion/jda/api/MessageBuilder.java
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/MessageAction.java
  src/main/java/net/dv8tion/jda/internal/entities/DataMessage.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/Helpers.java
Labels: size: small, type: feature

#1311 Use FormBody for prune post request
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Labels: size: small, type: breaking, type: discord issue

#1324 Properly apply socket timeouts where appropriate
  src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/internal/utils/config/SessionConfig.java
Labels: size: small, type: enhancement

#1327 Introduce better methods to load members
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildMembersChunkHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildSetupNode.java
  src/main/java/net/dv8tion/jda/internal/requests/MemberChunkManager.java
Labels: size: small, type: enhancement, type: feature

#1321 Deprecate MessageBuilder#sendTo
  src/main/java/net/dv8tion/jda/api/MessageBuilder.java
Labels: bug, size: small
