Repository discord-jda/JDA, pull requests merged in 2020-07, with the labels that each got.

#1309 Add ETF support
  src/main/java/net/dv8tion/jda/api/GatewayEncoding.java
  src/main/java/net/dv8tion/jda/api/JDABuilder.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/api/utils/data/DataArray.java
  src/main/java/net/dv8tion/jda/api/utils/data/DataObject.java
  src/main/java/net/dv8tion/jda/api/utils/data/etf/ExTermDecoder.java
  src/main/java/net/dv8tion/jda/api/utils/data/etf/ExTermEncoder.java
  src/main/java/net/dv8tion/jda/api/utils/data/etf/ExTermTag.java
  src/main/java/net/dv8tion/jda/api/utils/data/etf/package-info.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageBulkDeleteHandler.java
  src/main/java/net/dv8tion/jda/internal/managers/PresenceImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketSendingThread.java
  src/main/java/net/dv8tion/jda/internal/utils/config/sharding/ShardingMetaConfig.java
Labels: size: medium, type: feature

#1323 Make GuildMessageReactionRemoveEmoteEvent extend GenericGuildMessageEvent
  src/main/java/net/dv8tion/jda/api/events/message/guild/react/GuildMessageReactionRemoveEmoteEvent.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageReactionClearEmoteHandler.java
Labels: size: small, type: enhancement

#1338 Fix issues with duplicate overrides in ChannelAction
  src/main/java/net/dv8tion/jda/internal/requests/restaction/ChannelActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/PermOverrideData.java
Labels: bug, size: small

#1273 Add check for voice connect permission
  src/main/java/net/dv8tion/jda/api/MessageBuilder.java
  src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java
  src/main/java/net/dv8tion/jda/api/entities/IPermissionHolder.java
  src/main/java/net/dv8tion/jda/api/entities/MessageHistory.java
  src/main/java/net/dv8tion/jda/api/exceptions/InsufficientPermissionException.java
  src/main/java/net/dv8tion/jda/api/exceptions/MissingAccessException.java
  src/main/java/net/dv8tion/jda/internal/entities/AbstractChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/PermissionOverrideImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/ChannelManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/PermOverrideManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/WebhookManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/PermissionOverrideActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/MessagePaginationActionImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/PermissionUtil.java
Labels: bug, size: small, type: discord issue

#1303 Add Emote#isAvailable() method
  src/main/java/net/dv8tion/jda/api/entities/Emote.java
  src/main/java/net/dv8tion/jda/internal/entities/EmoteImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
Labels: size: small, type: feature

#1291 Deprecate IFakeable
  README.md
  src/main/java/net/dv8tion/jda/annotations/ForRemoval.java
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/MessageBuilder.java
  src/main/java/net/dv8tion/jda/api/entities/ApplicationInfo.java
  src/main/java/net/dv8tion/jda/api/entities/Emote.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/IFakeable.java
  src/main/java/net/dv8tion/jda/api/entities/Invite.java
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/TeamMember.java
  src/main/java/net/dv8tion/jda/api/entities/Webhook.java
  src/main/java/net/dv8tion/jda/api/events/guild/GuildBanEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/GuildUnbanEvent.java
  src/main/java/net/dv8tion/jda/api/events/message/MessageReceivedEvent.java
  src/main/java/net/dv8tion/jda/api/events/message/guild/GuildMessageReceivedEvent.java
  src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java
  src/main/java/net/dv8tion/jda/internal/entities/EmoteImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/MemberImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/PrivateChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/UserImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/ChannelCreateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/ChannelDeleteHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildBanHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildDeleteHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildMemberRemoveHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/InviteCreateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageDeleteHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageReactionHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/TypingStartHandler.java
  src/main/java/net/dv8tion/jda/internal/managers/EmoteManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/ReactionPaginationActionImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/PermissionUtil.java
Labels: size: small, type: enhancement

#1348 Update WebSocket library to 2.10
  build.gradle.kts
  src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/internal/utils/IOUtil.java
Labels: size: small

#1354 Switch to new permission key
  src/main/java/net/dv8tion/jda/api/utils/data/etf/ExTermDecoder.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/handle/ChannelUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildRoleUpdateHandler.java
Labels: size: small, type: discord issue
