Repository discord-jda/JDA, pull requests merged in 2020-10, with the labels that each got.

#1401 add a dot to getEffectiveAvatarUrl docs
  src/main/java/net/dv8tion/jda/api/entities/User.java
Labels: size: small

#1407 Allow using reactions on system messages
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/internal/entities/SystemMessage.java
Labels: bug, size: small

#1382 rename some userflags to match their new name
  src/main/java/net/dv8tion/jda/api/entities/User.java
Labels: size: small

#1422 Add watered-down GuildMemberUpdateEvent
  src/main/java/net/dv8tion/jda/api/events/guild/member/GuildMemberRemoveEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/member/GuildMemberUpdateEvent.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildMemberUpdateHandler.java
Labels: size: small, type: feature
