Repository discord-jda/JDA, pull requests merged in 2020-11, with the labels that each got.

#1430 Improve handling of exceptions during login process
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/api/utils/SessionControllerAdapter.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
Labels: size: small, type: enhancement

#1447 Uncomment GUILD_WEBHOOKS intent
  src/main/java/net/dv8tion/jda/api/requests/GatewayIntent.java
Labels: size: small, type: feature

#1343 Implement Role#getTags and add CacheFlag#ROLE_TAGS
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/Role.java
  src/main/java/net/dv8tion/jda/api/utils/cache/CacheFlag.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/RoleImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildMemberRemoveHandler.java
  src/main/java/net/dv8tion/jda/internal/hooks/EventManagerProxy.java
Labels: size: small, type: feature

#1408 Implement inline replies feature
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/MessageType.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/MessageAction.java
  src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/SystemMessage.java
  src/main/java/net/dv8tion/jda/internal/requests/RestActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java
Labels: size: small, type: feature

#1452 Improve reconnect logic for voice sessions after invalidate
  src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
Labels: size: small, type: discord issue, type: enhancement

#1409 Adding isSynced() method
  src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java
  src/main/java/net/dv8tion/jda/internal/entities/AbstractChannelImpl.java
Labels: size: small, type: feature
