Repository discord-jda/JDA, pull requests merged in 2020-05, with the labels that each got.

#1171 Add Guild#retrieveMetaData
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildUpdateHandler.java
Labels: size: small, type: enhancement, type: feature

#1282 Add check for heartbeats in WebSocketClient
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
Labels: size: small, type: enhancement

#1276 Add retrieveMembersByPrefix
  src/main/java/net/dv8tion/jda/api/JDABuilder.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/api/utils/concurrent/Task.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildMembersChunkHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildSetupController.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildSetupNode.java
  src/main/java/net/dv8tion/jda/internal/hooks/EventManagerProxy.java
  src/main/java/net/dv8tion/jda/internal/requests/MemberChunkManager.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketSendingThread.java
  src/main/java/net/dv8tion/jda/internal/utils/concurrent/task/GatewayTask.java
  src/main/java/net/dv8tion/jda/internal/utils/config/ThreadingConfig.java
  src/main/java/net/dv8tion/jda/internal/utils/config/sharding/ThreadingProviderConfig.java
Labels: priority: high, size: medium, type: feature

#1286 Create file if it doesn't exist in downloadToFile
  src/main/java/net/dv8tion/jda/api/entities/Message.java
Labels: size: small, type: enhancement

#1283 Improve handling of join times for members
  src/main/java/net/dv8tion/jda/api/entities/Member.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/MemberImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageReactionHandler.java
Labels: bug, size: small, type: enhancement

#1284 Add Message.JUMP_URL_PATTERN
  src/main/java/net/dv8tion/jda/api/entities/Message.java
Labels: size: small, type: feature

#1295 Replace disconnect handling to recover from strange thread states
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
Labels: size: small, type: enhancement

#1292 Add methods to bulk retrieve members
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/utils/concurrent/Task.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/MemberChunkManager.java
  src/main/java/net/dv8tion/jda/internal/utils/concurrent/task/GatewayTask.java
Labels: size: small, type: feature

#1285 Improvements to handling of Error
  src/main/java/net/dv8tion/jda/api/audio/hooks/ListenerProxy.java
  src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java
  src/main/java/net/dv8tion/jda/api/entities/Role.java
  src/main/java/net/dv8tion/jda/api/hooks/AnnotatedEventManager.java
  src/main/java/net/dv8tion/jda/api/hooks/InterfacedEventManager.java
  src/main/java/net/dv8tion/jda/api/requests/Request.java
  src/main/java/net/dv8tion/jda/internal/entities/CategoryImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/RoleImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/StoreChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/VoiceChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/RestActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/operator/RestActionOperator.java
Labels: bug, size: small, type: enhancement

#1288 Change domain to discord.com
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/JDABuilder.java
  src/main/java/net/dv8tion/jda/api/OnlineStatus.java
  src/main/java/net/dv8tion/jda/api/entities/Activity.java
  src/main/java/net/dv8tion/jda/api/entities/ApplicationInfo.java
  src/main/java/net/dv8tion/jda/api/entities/Emote.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/MessageActivity.java
  src/main/java/net/dv8tion/jda/api/entities/RichPresence.java
  src/main/java/net/dv8tion/jda/api/entities/Webhook.java
  src/main/java/net/dv8tion/jda/api/events/RawGatewayEvent.java
  src/main/java/net/dv8tion/jda/api/exceptions/ErrorResponseException.java
  src/main/java/net/dv8tion/jda/api/hooks/VoiceDispatchInterceptor.java
  src/main/java/net/dv8tion/jda/api/managers/ChannelManager.java
  src/main/java/net/dv8tion/jda/api/requests/CloseCode.java
  src/main/java/net/dv8tion/jda/api/requests/ErrorResponse.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/MemberAction.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/api/utils/MiscUtil.java
  src/main/java/net/dv8tion/jda/api/utils/WidgetUtil.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/ApplicationInfoImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/internal/requests/Requester.java
  src/main/java/net/dv8tion/jda/internal/utils/IOUtil.java
Labels: type: discord issue

#1271 Add User#getFlags
  src/main/java/net/dv8tion/jda/api/entities/User.java
  src/main/java/net/dv8tion/jda/api/events/user/update/UserUpdateFlagsEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/UserImpl.java
Labels: size: small, type: feature

#1297 Automatically adjust settings based on intents
  src/main/java/net/dv8tion/jda/api/JDABuilder.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java
  src/main/java/net/dv8tion/jda/api/entities/Member.java
  src/main/java/net/dv8tion/jda/api/requests/GatewayIntent.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
Labels: size: small, type: enhancement, type: semi-breaking

#1302 Improve handling of VOICE_SERVER_UPDATE
  src/main/java/net/dv8tion/jda/api/managers/AudioManager.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/audio/AudioConnection.java
  src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildSetupNode.java
  src/main/java/net/dv8tion/jda/internal/handle/VoiceServerUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/VoiceStateUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/managers/AudioManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketSendingThread.java
Labels: bug, size: small
