Repository discord-jda/JDA, pull requests merged in 2020-09, with the labels that each got.

#1388 Apply MANAGE_CHANNEL context to categories
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/internal/entities/CategoryImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/ChannelActionImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/PermissionUtil.java
Labels: bug, size: small

#1398 Make audio thread pool configurable by users
  src/main/java/net/dv8tion/jda/api/JDABuilder.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java
  src/main/java/net/dv8tion/jda/internal/utils/config/ThreadingConfig.java
  src/main/java/net/dv8tion/jda/internal/utils/config/sharding/ThreadingProviderConfig.java
Labels: size: small, type: feature

#1404 Add length check to Activity#playing and similar methods
  src/main/java/net/dv8tion/jda/api/entities/Activity.java
Labels: size: small, type: enhancement
