Repository discord-jda/JDA, pull requests merged in 2021-07, with the labels that each got.

#1698 Replace isEmpty check with isBlank in StageInstanceActionImpl#setTopic
  src/main/java/net/dv8tion/jda/internal/requests/restaction/StageInstanceActionImpl.java
Labels: bug, size: small

#1732 Fix outdated sticker field name
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
Labels: bug

#1711 Update Lavlink Links in README.md
  README.md
Labels: type: documentation

#1690 Removed false @Nonnull
  src/main/java/net/dv8tion/jda/api/Region.java
Labels: type: documentation

#1659 Fix documentation in Message interface
  src/main/java/net/dv8tion/jda/api/entities/Message.java
Labels: type: documentation

#1742 Add thread permissions
  src/main/java/net/dv8tion/jda/api/Permission.java
Labels: size: small, type: feature

#1686 Implement access and retrieval of message_reference
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/MessageReference.java
  src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/SystemMessage.java
Labels: size: small, type: feature
