Repository discord-jda/JDA, pull requests merged in 2021-04, with the labels that each got.

#1405 Switch to API version 8 (gateway and REST)
  src/main/java/net/dv8tion/jda/api/AccountType.java
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/JDABuilder.java
  src/main/java/net/dv8tion/jda/api/JDAInfo.java
  src/main/java/net/dv8tion/jda/api/entities/Member.java
  src/main/java/net/dv8tion/jda/api/entities/MessageEmbed.java
  src/main/java/net/dv8tion/jda/api/entities/MessageType.java
  src/main/java/net/dv8tion/jda/api/events/channel/priv/PrivateChannelCreateEvent.java
  src/main/java/net/dv8tion/jda/api/events/channel/priv/PrivateChannelDeleteEvent.java
  src/main/java/net/dv8tion/jda/api/events/user/UserTypingEvent.java
  src/main/java/net/dv8tion/jda/api/exceptions/ErrorResponseException.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/api/utils/MemberCachePolicy.java
  src/main/java/net/dv8tion/jda/api/utils/cache/CacheFlag.java
  src/main/java/net/dv8tion/jda/api/utils/data/etf/ExTermEncoder.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/MemberImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/MemberPresenceImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/ChannelCreateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/ChannelDeleteHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/ChannelUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildMemberRemoveHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildRoleUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageReactionHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/PresenceUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/TypingStartHandler.java
  src/main/java/net/dv8tion/jda/internal/managers/PresenceImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/Requester.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/internal/requests/ratelimit/BotRateLimiter.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/PermissionOverrideActionImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/Helpers.java
Labels: size: small, type: discord issue, type: semi-breaking

#1579 Changed getUserByTag(String username, String discriminator) to use codepoints when checking username length
  src/main/java/net/dv8tion/jda/api/JDA.java
Labels: size: small, type: enhancement

#1597 Hotfix some issues introduced by v8
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageCreateHandler.java
  src/main/java/net/dv8tion/jda/internal/requests/ratelimit/BotRateLimiter.java
Labels: bug, size: small, type: discord issue

#1586 Allow all guild channels to be mentioned
  src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java
  src/main/java/net/dv8tion/jda/api/entities/StoreChannel.java
  src/main/java/net/dv8tion/jda/api/entities/TextChannel.java
  src/main/java/net/dv8tion/jda/internal/entities/AbstractChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/StoreChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
Labels: size: small, type: feature

#1585 Deprecate UserFlag#SYSTEM and add User#isSystem
  src/main/java/net/dv8tion/jda/api/entities/User.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/UserById.java
  src/main/java/net/dv8tion/jda/internal/entities/UserImpl.java
Labels: size: small, type: discord issue

#1474 add support for stickers
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/MessageSticker.java
  src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/SystemMessage.java
Labels: priority: low, size: small, type: feature

#1576 Add Message.Attachment#getContentType
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
Labels: size: small, type: feature

#1569 add checks for the reason length in Guild#kick and Guild#ban and remove some invalid docs
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/Member.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Labels: size: small, type: enhancement

#1562 remove nullability note for GuildChannel#getName
  src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java
Labels: size: small, type: documentation

#1577 Fix spelling mistake in ErrorHandler
  src/main/java/net/dv8tion/jda/api/exceptions/ErrorHandler.java
Labels: type: documentation
