Repository discord-jda/JDA, pull requests merged in 2021-12, with the labels that each got.

#1927 fix wrong check in GenericMessageEvent#getGuildChannel
  src/main/java/net/dv8tion/jda/api/events/message/GenericMessageEvent.java
Labels: bug

#1924 Add GenericMessageEvent#getThreadChannel()
  src/main/java/net/dv8tion/jda/api/events/message/GenericMessageEvent.java
Labels: type: enhancement

#1922 Make SelectionMenu#getOptions return an unmodifiable list
  src/main/java/net/dv8tion/jda/api/interactions/components/selections/SelectionMenu.java
  src/main/java/net/dv8tion/jda/internal/interactions/SelectionMenuImpl.java
Labels: type: enhancement

#1928 Make Guild#moveVoiceMember support AudioChannel instead
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Labels: type: enhancement

#1925 Implement parent channel fetching when checking thread permissions
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
Labels: bug

#1930 add Message.Attachment#getDescription
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
Labels: type: feature

#1935 Add GenericChannelEvent#isFromGuild and GenericChannelEvent#getGuild
  src/main/java/net/dv8tion/jda/api/events/channel/GenericChannelEvent.java
Labels: type: feature

#1944 transform SelectionMenu magic values into constants
  src/main/java/net/dv8tion/jda/api/interactions/components/selections/SelectionMenu.java
Labels: type: enhancement

#1951 Fix NPE when cloning guild role with null icon
  src/main/java/net/dv8tion/jda/internal/entities/RoleImpl.java
Labels: bug

#1953 Use bitshifts instead of hexcodes in managers
  src/main/java/net/dv8tion/jda/api/managers/AccountManager.java
  src/main/java/net/dv8tion/jda/api/managers/EmoteManager.java
  src/main/java/net/dv8tion/jda/api/managers/PermOverrideManager.java
  src/main/java/net/dv8tion/jda/api/managers/RoleManager.java
  src/main/java/net/dv8tion/jda/api/managers/StageInstanceManager.java
  src/main/java/net/dv8tion/jda/api/managers/TemplateManager.java
  src/main/java/net/dv8tion/jda/api/managers/WebhookManager.java
Labels: type: enhancement

#1897 Add support for animated guild banners
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateBannerEvent.java
Labels: type: feature

#1964 Fix IllegalStateException for OptionType.MENTIONABLE
  src/main/java/net/dv8tion/jda/api/interactions/commands/OptionMapping.java
Labels: bug

#1956 Move canTalk() from GuildMessageChannel to MessageChannel
  src/main/java/net/dv8tion/jda/api/entities/GuildMessageChannel.java
  src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
  src/main/java/net/dv8tion/jda/internal/entities/PrivateChannelImpl.java
Labels: type: enhancement

#1957 Hardcode gateway url
  src/main/java/net/dv8tion/jda/api/utils/SessionController.java
  src/main/java/net/dv8tion/jda/api/utils/SessionControllerAdapter.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
Labels: type: enhancement, type: breaking

#1919 Implement retrieveThreadMember
  src/main/java/net/dv8tion/jda/api/entities/ThreadChannel.java
  src/main/java/net/dv8tion/jda/internal/entities/ThreadChannelImpl.java
Labels: type: feature

#1963 Only update CommandData limiting booleans for non-empty additions
  src/main/java/net/dv8tion/jda/api/interactions/commands/build/CommandData.java
Labels: type: enhancement

#1902 Add support for member timeouts
  src/main/java/net/dv8tion/jda/api/EmbedBuilder.java
  src/main/java/net/dv8tion/jda/api/Permission.java
  src/main/java/net/dv8tion/jda/api/audit/AuditLogKey.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/Member.java
  src/main/java/net/dv8tion/jda/api/events/guild/member/update/GuildMemberUpdateTimeOutEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/MemberImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/Helpers.java
  src/main/java/net/dv8tion/jda/internal/utils/PermissionUtil.java
Labels: type: feature
