Repository discord-jda/JDA, pull requests merged in 2021-09, with the labels that each got.

#1783 Enable unmuting suppressed users
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Labels: type: enhancement

#1749 Fix embed length checks
  src/main/java/net/dv8tion/jda/api/EmbedBuilder.java
  src/main/java/net/dv8tion/jda/api/entities/MessageEmbed.java
Labels: type: enhancement

#1793 Add NSFWLevel
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateNSFWLevelEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildUpdateHandler.java
Labels: type: feature

#1790 Add interaction related message flags
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/events/interaction/GenericComponentInteractionCreateEvent.java
  src/main/java/net/dv8tion/jda/api/interactions/components/ButtonInteraction.java
  src/main/java/net/dv8tion/jda/api/interactions/components/ComponentInteraction.java
  src/main/java/net/dv8tion/jda/api/interactions/components/selections/SelectionMenuInteraction.java
  src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/internal/interactions/ComponentInteractionImpl.java
Labels: type: enhancement

#1785 Fix a typo in Invite
  src/main/java/net/dv8tion/jda/api/entities/Invite.java
Labels: type: documentation

#1779 Fix minor link typo in retrieveBanById(long)
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
Labels: type: documentation

#1778 Adding external sticker permission and adding external emoji to text channel overrides
  src/main/java/net/dv8tion/jda/api/Permission.java
Labels: type: enhancement

#1747 add Interaction Object for Messages
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/SystemMessage.java
Labels: type: feature

#1741 Add Command#getVersion
  src/main/java/net/dv8tion/jda/api/interactions/commands/Command.java
Labels: type: feature

#1762 Create ID alternatives to permission override methods in ChannelManager
  src/main/java/net/dv8tion/jda/api/managers/ChannelManager.java
  src/main/java/net/dv8tion/jda/internal/managers/ChannelManagerImpl.java
Labels: type: enhancement

#1798 Update Activity(Type)
  src/main/java/net/dv8tion/jda/api/entities/Activity.java
  src/main/java/net/dv8tion/jda/internal/entities/ActivityImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
Labels: v5

#1826 add ephemeral field to attachment
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
Labels: type: enhancement, v4 LTS

#1810 Add Missing Varargs and Methods Accepting Collection Arguments
  src/main/java/net/dv8tion/jda/api/requests/restaction/CommandCreateAction.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/CommandCreateActionImpl.java
Labels: v5

#1797 Update Permissions for JDA5
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/Permission.java
  src/main/java/net/dv8tion/jda/api/entities/Emote.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/GuildMessageChannel.java
  src/main/java/net/dv8tion/jda/api/entities/IMemberContainer.java
  src/main/java/net/dv8tion/jda/api/entities/ListedEmote.java
  src/main/java/net/dv8tion/jda/api/entities/Member.java
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
  src/main/java/net/dv8tion/jda/api/entities/MessageReference.java
  src/main/java/net/dv8tion/jda/api/entities/NewsChannel.java
  src/main/java/net/dv8tion/jda/api/managers/ChannelManager.java
  src/main/java/net/dv8tion/jda/api/managers/PermOverrideManager.java
  src/main/java/net/dv8tion/jda/api/requests/RestAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/ChannelAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/PermissionOverrideAction.java
  src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
  src/main/java/net/dv8tion/jda/internal/entities/EmoteImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/MemberImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/EmoteManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/RestActionImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/PermissionUtil.java
Labels: v5

#1672 Add check and recovery for missing self members
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Labels: bug, type: discord issue, size: small, Required for v4 LTS

#1816 Make OptionData#addChoice accept long instead of int
  src/main/java/net/dv8tion/jda/api/interactions/commands/build/OptionData.java
Labels: v5

#1813 Fix exception schema parsing if _errors array is top-level
  src/main/java/net/dv8tion/jda/api/exceptions/ErrorResponseException.java
Labels: bug, Required for v4 LTS

#1829 Added all thread relating routes
  src/main/java/net/dv8tion/jda/internal/requests/Route.java
Labels: v5

#1842 Mark every deprecation for removal at the latest in 5.0.0
  src/main/java/net/dv8tion/jda/api/JDABuilder.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/Invite.java
  src/main/java/net/dv8tion/jda/api/entities/MessageSticker.java
  src/main/java/net/dv8tion/jda/api/events/guild/member/GuildMemberLeaveEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateBannerEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateRegionEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/api/managers/AudioManager.java
  src/main/java/net/dv8tion/jda/api/managers/GuildManager.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/GuildAction.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
Labels: type: documentation, Required for v4 LTS

#1820 Add OptionData#setChannelTypes
  src/main/java/net/dv8tion/jda/api/interactions/commands/Command.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/build/OptionData.java
Labels: type: feature, Required for v4 LTS
