Repository discord-jda/JDA, pull requests merged in 2021-06, with the labels that each got.

#1543 Mention that CUSTOM_STATUS is read only
  src/main/java/net/dv8tion/jda/api/entities/Activity.java
Labels: size: small, type: documentation

#1609 Add implementation comment
  README.md
Labels: type: documentation

#1645 Increase audio request retry from 2 seconds to 10 seconds
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketSendingThread.java
Labels: size: small, type: enhancement

#1519 Allow building DefaultShardManager without starting it
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
Labels: size: small, type: feature

#1622 Add support for VoiceChannel region overrides
  src/main/java/net/dv8tion/jda/api/Region.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/VoiceChannel.java
  src/main/java/net/dv8tion/jda/api/events/channel/voice/update/VoiceChannelUpdateRegionEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateRegionEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/api/managers/ChannelManager.java
  src/main/java/net/dv8tion/jda/api/managers/GuildManager.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/GuildAction.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/VoiceChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/ChannelUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/managers/ChannelManagerImpl.java
Labels: size: small, type: feature

#1465 add support for guild templates
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java
  src/main/java/net/dv8tion/jda/api/entities/Invite.java
  src/main/java/net/dv8tion/jda/api/entities/templates/Template.java
  src/main/java/net/dv8tion/jda/api/entities/templates/TemplateChannel.java
  src/main/java/net/dv8tion/jda/api/entities/templates/TemplateGuild.java
  src/main/java/net/dv8tion/jda/api/entities/templates/TemplateRole.java
  src/main/java/net/dv8tion/jda/api/managers/TemplateManager.java
  src/main/java/net/dv8tion/jda/api/requests/ErrorResponse.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/TemplateManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/Route.java
Labels: size: medium, type: feature

#1655 Fix Message.editMessage(Message) only accepting Message of type DEFAULT
  src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java
Labels: bug, size: small

#1653 Implement Button.of(ButtonStyle, String, String, Emoji) to quickly get a button with a label and emoji.
  src/main/java/net/dv8tion/jda/api/interactions/components/Button.java
Labels: size: small, type: feature

#1652 Support multi-embeds in MessageAction
  src/main/java/net/dv8tion/jda/api/EmbedBuilder.java
  src/main/java/net/dv8tion/jda/api/MessageBuilder.java
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
  src/main/java/net/dv8tion/jda/api/entities/MessageEmbed.java
  src/main/java/net/dv8tion/jda/api/interactions/InteractionHook.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/MessageAction.java
  src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/DataMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/interactions/InteractionHookImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/WebhookMessageActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/WebhookMessageUpdateActionImpl.java
Labels: size: small, type: feature

#1680 Fixed the issue with last character handling for cases when the length of the message is 4001 characters
  src/main/java/net/dv8tion/jda/api/MessageBuilder.java
Labels: bug, size: small

#1676 Add TimeFormat and Timestamp
  src/main/java/net/dv8tion/jda/api/interactions/components/Button.java
  src/main/java/net/dv8tion/jda/api/utils/TimeFormat.java
  src/main/java/net/dv8tion/jda/api/utils/Timestamp.java
Labels: size: small, type: feature
