Repository discord-jda/JDA, pull requests merged in 2021-03, with the labels that each got.

#1522 Add Permission.USE_SLASH_COMMANDS
  src/main/java/net/dv8tion/jda/api/Permission.java
Labels: size: small, type: feature

#1516 Docs: Nullability in GuildMessageReactionAddEvent
  src/main/java/net/dv8tion/jda/api/events/message/guild/react/GuildMessageReactionAddEvent.java
Labels: type: documentation

#1493 clarify Guild#getLocale for guilds without the COMMUNITY feature
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
Labels: type: documentation

#1490 fix mismatched docs for GuildUpdateOwnerEvent getters
  src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateOwnerEvent.java
Labels: type: documentation

#1530 Update Features list for Guild#getFeatures()
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
Labels: type: documentation

#1524 Add fail_if_not_exists
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/MessageAction.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java
Labels: size: small, type: feature

#1497 Minor improvement in the Member#kick() docs
  src/main/java/net/dv8tion/jda/api/entities/Member.java
Labels: type: documentation

#1464 add Guild#getRulesChannel and Guild#getCommunityUpdatesChannel
  src/main/java/net/dv8tion/jda/api/audit/ActionType.java
  src/main/java/net/dv8tion/jda/api/audit/AuditLogKey.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateCommunityUpdatesChannelEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateRulesChannelEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/api/managers/GuildManager.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/managers/GuildManagerImpl.java
Labels: size: small, type: feature

#1481 [Docs] Mention that createDefault and createLight may override GatewayIntent#DEFAULT
  src/main/java/net/dv8tion/jda/api/JDABuilder.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
Labels: type: documentation

#1510 Fixed Documentation for MessageAction#reference
  src/main/java/net/dv8tion/jda/api/requests/restaction/MessageAction.java
Labels: type: documentation

#1482 [Wiki] updated setup guide for Eclipse
  assets/wiki/setup/eclipse/01-newProject.png
  assets/wiki/setup/eclipse/02-gradleProject.png
  assets/wiki/setup/eclipse/03-projectOverview.png
  assets/wiki/setup/eclipse/04-deleteFiles.png
  assets/wiki/setup/eclipse/05-gradleBuildFile.png
  assets/wiki/setup/eclipse/06-gradleRefresh.png
  assets/wiki/setup/eclipse/10-newProject.png
  assets/wiki/setup/eclipse/11-checkSimpleProject.png
  assets/wiki/setup/eclipse/12-nvmValues.png
  assets/wiki/setup/eclipse/13-mvnUpdate.png
  assets/wiki/setup/eclipse/20-newJavaProject.png
  assets/wiki/setup/eclipse/21-java8.png
  assets/wiki/setup/eclipse/22-addExternalJars.png
  assets/wiki/setup/eclipse/23-sourceAttachment.png
  assets/wiki/setup/eclipse/24-externalFile.png
  assets/wiki/setup/eclipse/25-javaDocs.png
Labels: type: documentation

#1532 Remove unnecessary checks for permission values
  src/main/java/net/dv8tion/jda/api/requests/restaction/GuildAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/PermissionOverrideAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/RoleAction.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/ChannelActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/PermissionOverrideActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/RoleActionImpl.java
Labels: size: small, type: enhancement

#1478 add Member#isPending
  src/main/java/net/dv8tion/jda/api/entities/Member.java
  src/main/java/net/dv8tion/jda/api/events/guild/member/update/GuildMemberUpdatePendingEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/api/utils/MemberCachePolicy.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/MemberImpl.java
Labels: size: small, type: feature

#1469 Implement a timeout for unavailable guilds
  src/main/java/net/dv8tion/jda/api/events/ReadyEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/GuildReadyEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/GuildTimeoutEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/UnavailableGuildJoinedEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildSetupController.java
Labels: size: small, type: enhancement

#1376 Add Guild#retrieveVanityInvite
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/VanityInvite.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Labels: size: small, type: feature

#1534 Add UserUpdateActivitiesEvent
  src/main/java/net/dv8tion/jda/api/events/user/update/UserUpdateActivitiesEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/internal/handle/PresenceUpdateHandler.java
Labels: size: small, type: feature

#1547 Set socket timeout before connecting websockets
  README.md
  build.gradle.kts
  src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
Labels: size: small, type: enhancement

#1536 Add error logging for callbacks in GatewayTask
  src/main/java/net/dv8tion/jda/internal/utils/concurrent/task/GatewayTask.java
Labels: size: small, type: enhancement

#1533 Improve some logging for large rate limits
  src/main/java/net/dv8tion/jda/internal/requests/ratelimit/BotRateLimiter.java
Labels: size: small, type: enhancement

#1349 Add findMembersWithRoles
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/MemberChunkManager.java
Labels: size: small, type: feature

#1549 Remove thread-safe acquisition of managers
  src/main/java/net/dv8tion/jda/api/entities/Emote.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java
  src/main/java/net/dv8tion/jda/api/entities/PermissionOverride.java
  src/main/java/net/dv8tion/jda/api/entities/Role.java
  src/main/java/net/dv8tion/jda/api/entities/SelfUser.java
  src/main/java/net/dv8tion/jda/api/entities/Webhook.java
  src/main/java/net/dv8tion/jda/internal/entities/AbstractChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/EmoteImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/PermissionOverrideImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/RoleImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/SelfUserImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/WebhookImpl.java
Labels: size: small, type: enhancement

#1418 Implement TextChannel#follow and add source references
  src/main/java/net/dv8tion/jda/api/entities/TextChannel.java
  src/main/java/net/dv8tion/jda/api/entities/Webhook.java
  src/main/java/net/dv8tion/jda/api/requests/ErrorResponse.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/WebhookImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/Route.java
Labels: size: small, type: feature

#1551 Use MethodHandle for ListenerAdapter
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
Labels: size: small, type: enhancement

#1560 Fix deny/grant on override action
  src/main/java/net/dv8tion/jda/api/requests/restaction/PermissionOverrideAction.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/PermissionOverrideActionImpl.java
Labels: bug, size: small
