Repository discord-jda/JDA, pull requests merged in 2022-05, with the labels that each got.

#1955 Add ImageProxy & FileProxy
  src/main/java/net/dv8tion/jda/api/entities/ApplicationInfo.java
  src/main/java/net/dv8tion/jda/api/entities/ApplicationTeam.java
  src/main/java/net/dv8tion/jda/api/entities/Emote.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/Invite.java
  src/main/java/net/dv8tion/jda/api/entities/Member.java
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/MessageActivity.java
  src/main/java/net/dv8tion/jda/api/entities/MessageEmbed.java
  src/main/java/net/dv8tion/jda/api/entities/MessageSticker.java
  src/main/java/net/dv8tion/jda/api/entities/RoleIcon.java
  src/main/java/net/dv8tion/jda/api/entities/User.java
  src/main/java/net/dv8tion/jda/api/entities/templates/TemplateGuild.java
  src/main/java/net/dv8tion/jda/api/events/guild/member/update/GuildMemberUpdateAvatarEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateBannerEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateIconEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateSplashEvent.java
  src/main/java/net/dv8tion/jda/api/events/self/SelfUpdateAvatarEvent.java
  src/main/java/net/dv8tion/jda/api/events/user/update/UserUpdateAvatarEvent.java
  src/main/java/net/dv8tion/jda/api/utils/AttachmentProxy.java
  src/main/java/net/dv8tion/jda/api/utils/FileProxy.java
  src/main/java/net/dv8tion/jda/api/utils/ImageProxy.java
  src/main/java/net/dv8tion/jda/api/utils/WidgetUtil.java
  src/main/java/net/dv8tion/jda/internal/entities/InviteImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/UserImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/FutureUtil.java
Labels: type: enhancement

#2015 Message interface declutter: Message#getMentions()
  src/examples/java/MessageListenerExample.java
  src/main/java/net/dv8tion/jda/api/entities/Mentions.java
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/OptionMapping.java
  src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/InteractionMentions.java
  src/main/java/net/dv8tion/jda/internal/entities/MessageMentionsImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/SystemMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/mentions/AbstractMentions.java
  src/main/java/net/dv8tion/jda/internal/interactions/command/CommandInteractionPayloadImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/AllowedMentionsImpl.java
Labels: type: enhancement, type: breaking

#2116 Add new message types for automod
  src/main/java/net/dv8tion/jda/api/entities/EmbedType.java
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
  src/main/java/net/dv8tion/jda/api/entities/MessageType.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
Labels: bug, type: discord issue

#2127 Remove checks for archive durations
  src/main/java/net/dv8tion/jda/api/managers/channel/concrete/ThreadChannelManager.java
  src/main/java/net/dv8tion/jda/internal/managers/channel/ChannelManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/ThreadChannelActionImpl.java
Labels: type: discord issue

#2099 Add Message#getStartedThread and ThreadChannel#retrieveParentMessage
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/ThreadChannel.java
  src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/SystemMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/ThreadChannelImpl.java
Labels: type: feature

#2124 Added getJumpUrl method to GenericMessageEvent
  src/main/java/net/dv8tion/jda/api/events/message/GenericMessageEvent.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
Labels: type: feature

#2120 Add FileUpload class
  src/main/java/net/dv8tion/jda/api/requests/restaction/interactions/InteractionCallbackAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/interactions/MessageEditCallbackAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/interactions/ReplyCallbackAction.java
  src/main/java/net/dv8tion/jda/api/utils/AttachedFile.java
  src/main/java/net/dv8tion/jda/api/utils/AttachmentUpdate.java
  src/main/java/net/dv8tion/jda/api/utils/FileUpload.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/WebhookMessageActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/interactions/InteractionCallbackImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/interactions/MessageEditCallbackActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/interactions/ReplyCallbackActionImpl.java
Labels: type: feature, type: semi-breaking

#2131 FileProxy: Fix parent folder exists check
  src/main/java/net/dv8tion/jda/api/utils/FileProxy.java
Labels: bug

#2115 [Bugfix] retrieving public archived threads
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildMembersChunkHandler.java
  src/main/java/net/dv8tion/jda/internal/requests/MemberChunkManager.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/PaginationActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/ThreadChannelPaginationActionImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/Helpers.java
Labels: bug

#2126 Add missing return value description
  src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
Labels: type: documentation

#2053 Do not ignore member cache policy when chunking is enabled
  src/main/java/net/dv8tion/jda/api/JDABuilder.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
Labels: type: enhancement, type: proposal, type: breaking

#2139 Fix Message.Attachment#getProxy()
  src/main/java/net/dv8tion/jda/api/entities/Message.java
Labels: bug
