Repository discord-jda/JDA, pull requests merged in 2022-12, with the labels that each got.

#2264 Add guild welcome screens
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/GuildWelcomeScreen.java
  src/main/java/net/dv8tion/jda/api/entities/Invite.java
  src/main/java/net/dv8tion/jda/api/managers/GuildWelcomeScreenManager.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildWelcomeScreenImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/InviteImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/GuildWelcomeScreenManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/Route.java
Labels: type: feature

#2349 Fix bug when updating a scheduled events location
  src/main/java/net/dv8tion/jda/internal/managers/ScheduledEventManagerImpl.java
Labels: bug

#2348 Add generic slowmode channel manager to slowmode channel interface
  src/main/java/net/dv8tion/jda/api/entities/channel/attribute/ISlowmodeChannel.java
Labels: type: enhancement

#2356 Fix welcome channel parsing when no emoji is used
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
Labels: bug

#2359 Replace lock code with atomic int
  src/main/java/net/dv8tion/jda/internal/requests/restaction/operator/CombineRestAction.java
Labels: type: enhancement

#2364 Fix issues with ChannelManager#setPinned and setTagRequired
  src/main/java/net/dv8tion/jda/internal/managers/ManagerBase.java
Labels: bug
