Repository discord-jda/JDA, pull requests merged in 2022-07, with the labels that each got.

#2090 Application command localization
  src/examples/java/LocalizationExample.java
  src/examples/resources/MyCommands_es_ES.properties
  src/examples/resources/MyCommands_fr.properties
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/interactions/DiscordLocale.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/Command.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/build/CommandData.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/build/OptionData.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/build/SlashCommandData.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/build/SubcommandData.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/build/SubcommandGroupData.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/localization/LocalizationFunction.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/localization/LocalizationMap.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/localization/ResourceBundleLocalizationFunction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/CommandCreateAction.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/interactions/CommandDataImpl.java
  src/main/java/net/dv8tion/jda/internal/interactions/command/CommandImpl.java
  src/main/java/net/dv8tion/jda/internal/interactions/command/localization/LocalizationMapper.java
  src/main/java/net/dv8tion/jda/internal/interactions/command/localization/UnmodifiableLocalizationMap.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/CommandCreateActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/interactions/AutoCompleteCallbackActionImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/localization/LocalizationUtils.java
Labels: type: feature

#2167 Add EmojiUnion
  src/main/java/net/dv8tion/jda/api/entities/Activity.java
  src/main/java/net/dv8tion/jda/api/entities/MessageReaction.java
  src/main/java/net/dv8tion/jda/api/entities/emoji/Emoji.java
  src/main/java/net/dv8tion/jda/api/entities/emoji/EmojiUnion.java
  src/main/java/net/dv8tion/jda/api/events/message/react/GenericMessageReactionEvent.java
  src/main/java/net/dv8tion/jda/api/events/message/react/MessageReactionRemoveEmojiEvent.java
  src/main/java/net/dv8tion/jda/api/interactions/components/buttons/Button.java
  src/main/java/net/dv8tion/jda/api/interactions/components/selections/SelectOption.java
  src/main/java/net/dv8tion/jda/internal/entities/ActivityImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/RichPresenceImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/emoji/CustomEmojiImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/emoji/RichCustomEmojiImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/emoji/UnicodeEmojiImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageReactionClearEmojiHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageReactionHandler.java
  src/main/java/net/dv8tion/jda/internal/interactions/component/ButtonImpl.java
Labels: type: feature, priority: high, type: semi-breaking

#2173 Replace occurrences of Locale with DiscordLocale
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/templates/TemplateGuild.java
  src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateLocaleEvent.java
  src/main/java/net/dv8tion/jda/api/events/interaction/GenericInteractionCreateEvent.java
  src/main/java/net/dv8tion/jda/api/interactions/Interaction.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/interactions/InteractionImpl.java
Labels: type: breaking

#2160 fix: Make MessageType#deletable return an accurate value.
  src/main/java/net/dv8tion/jda/api/entities/MessageType.java
Labels: bug, type: discord issue

#2072 Handle text in voice channels
  src/main/java/net/dv8tion/jda/api/audit/AuditLogKey.java
  src/main/java/net/dv8tion/jda/api/entities/ChannelType.java
  src/main/java/net/dv8tion/jda/api/entities/IPermissionHolder.java
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/MessageHistory.java
  src/main/java/net/dv8tion/jda/api/entities/MessageReaction.java
  src/main/java/net/dv8tion/jda/api/entities/MessageReference.java
  src/main/java/net/dv8tion/jda/api/entities/NewsChannel.java
  src/main/java/net/dv8tion/jda/api/entities/StandardGuildMessageChannel.java
  src/main/java/net/dv8tion/jda/api/entities/VoiceChannel.java
  src/main/java/net/dv8tion/jda/api/entities/channel/attribute/IAgeRestrictedChannel.java
  src/main/java/net/dv8tion/jda/api/entities/channel/unions/GuildMessageChannelUnion.java
  src/main/java/net/dv8tion/jda/api/entities/channel/unions/IWebhookContainerUnion.java
  src/main/java/net/dv8tion/jda/api/entities/channel/unions/MessageChannelUnion.java
  src/main/java/net/dv8tion/jda/api/exceptions/MissingAccessException.java
  src/main/java/net/dv8tion/jda/api/managers/channel/attribute/IAgeRestrictedChannelManager.java
  src/main/java/net/dv8tion/jda/api/managers/channel/concrete/VoiceChannelManager.java
  src/main/java/net/dv8tion/jda/api/managers/channel/middleman/StandardGuildMessageChannelManager.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/InviteImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/PermissionOverrideImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/VoiceChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/ChannelUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageBulkDeleteHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageCreateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageDeleteHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageReactionBulkRemoveHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageReactionClearEmojiHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageReactionHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/TypingStartHandler.java
  src/main/java/net/dv8tion/jda/internal/managers/PermOverrideManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/WebhookManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/channel/ChannelManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/PermissionOverrideActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/MessagePaginationActionImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/Checks.java
  src/main/java/net/dv8tion/jda/internal/utils/PermissionUtil.java
Labels: type: breaking

#2176 Fix handling of empty emoji names
  src/main/java/net/dv8tion/jda/api/interactions/components/selections/SelectOption.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageReactionClearEmojiHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageReactionHandler.java
  src/main/java/net/dv8tion/jda/internal/interactions/component/ButtonImpl.java
Labels: bug

#2177 Fix LocalizationMapper for context commands
  src/main/java/net/dv8tion/jda/internal/interactions/command/localization/LocalizationMapper.java
Labels: bug

#2165 Update to API version 10
  README.md
  src/examples/java/AudioEchoExample.java
  src/main/java/net/dv8tion/jda/api/JDAInfo.java
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/events/interaction/ModalInteractionEvent.java
  src/main/java/net/dv8tion/jda/api/interactions/ModalInteraction.java
  src/main/java/net/dv8tion/jda/api/interactions/components/ComponentInteraction.java
  src/main/java/net/dv8tion/jda/api/requests/CloseCode.java
  src/main/java/net/dv8tion/jda/api/requests/GatewayIntent.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/internal/interactions/ModalInteractionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/WebhookMessageUpdateActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/interactions/InteractionCallbackImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/interactions/MessageEditCallbackActionImpl.java
Labels: type: breaking

#2163 Replace MessageListenerExample with MessageLoggerExample
  README.md
  src/examples/java/MessageListenerExample.java
  src/examples/java/MessageLoggerExample.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/BanPaginationAction.java
Labels: type: documentation

#2195 Add some missing interaction features
  src/main/java/net/dv8tion/jda/api/events/interaction/ModalInteractionEvent.java
  src/main/java/net/dv8tion/jda/api/events/interaction/command/CommandAutoCompleteInteractionEvent.java
  src/main/java/net/dv8tion/jda/api/interactions/ModalInteraction.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/CommandAutoCompleteInteraction.java
  src/main/java/net/dv8tion/jda/internal/interactions/ModalInteractionImpl.java
  src/main/java/net/dv8tion/jda/internal/interactions/command/CommandAutoCompleteInteractionImpl.java
Labels: type: enhancement

#2181 Fix typo in MarkdownSanitizer
  src/main/java/net/dv8tion/jda/api/utils/MarkdownSanitizer.java
Labels: type: documentation
