Repository discord-jda/JDA, pull requests merged in 2022-01, with the labels that each got.

#1979 [Bugfix] DATE_TIME_TYPE_PARSE: Could not parse 859166905289539625. Should be ISO8601.
  src/main/java/net/dv8tion/jda/internal/entities/mixin/channel/attribute/IThreadContainerMixin.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/ThreadChannelPaginationActionImpl.java
Labels: bug

#1983 Add Interaction#getUserLocale and Interaction#getGuildLocale
  src/main/java/net/dv8tion/jda/api/events/interaction/GenericInteractionCreateEvent.java
  src/main/java/net/dv8tion/jda/api/interactions/Interaction.java
  src/main/java/net/dv8tion/jda/internal/interactions/InteractionImpl.java
Labels: type: feature

#1980 Limit new thread message count to 50
  src/main/java/net/dv8tion/jda/internal/handle/MessageCreateHandler.java
Labels: bug

#1838 Some documentation on //todo-v5: docs
  src/main/java/net/dv8tion/jda/api/entities/AudioChannel.java
  src/main/java/net/dv8tion/jda/api/entities/BaseGuildMessageChannel.java
  src/main/java/net/dv8tion/jda/api/entities/ChannelField.java
  src/main/java/net/dv8tion/jda/api/entities/GuildMessageChannel.java
  src/main/java/net/dv8tion/jda/api/entities/ICategorizableChannel.java
  src/main/java/net/dv8tion/jda/api/entities/ICopyableChannel.java
  src/main/java/net/dv8tion/jda/api/entities/IInviteContainer.java
  src/main/java/net/dv8tion/jda/api/entities/IMemberContainer.java
  src/main/java/net/dv8tion/jda/api/entities/IPermissionContainer.java
  src/main/java/net/dv8tion/jda/api/entities/IPositionableChannel.java
  src/main/java/net/dv8tion/jda/api/entities/IThreadContainer.java
  src/main/java/net/dv8tion/jda/api/entities/NewsChannel.java
  src/main/java/net/dv8tion/jda/api/entities/TextChannel.java
  src/main/java/net/dv8tion/jda/api/entities/ThreadChannel.java
  src/main/java/net/dv8tion/jda/api/entities/ThreadMember.java
  src/main/java/net/dv8tion/jda/api/events/thread/ThreadHiddenEvent.java
  src/main/java/net/dv8tion/jda/api/events/thread/ThreadRevealedEvent.java
  src/main/java/net/dv8tion/jda/api/managers/channel/ChannelManager.java
  src/main/java/net/dv8tion/jda/api/managers/channel/concrete/StageChannelManager.java
  src/main/java/net/dv8tion/jda/api/managers/channel/concrete/TextChannelManager.java
  src/main/java/net/dv8tion/jda/api/managers/channel/concrete/ThreadChannelManager.java
  src/main/java/net/dv8tion/jda/api/managers/channel/concrete/VoiceChannelManager.java
  src/main/java/net/dv8tion/jda/api/managers/channel/middleman/AudioChannelManager.java
  src/main/java/net/dv8tion/jda/api/managers/channel/middleman/BaseGuildMessageChannelManager.java
  src/main/java/net/dv8tion/jda/internal/entities/mixin/channel/attribute/IThreadContainerMixin.java
Labels: type: documentation, v5

#1978 Move requestToSpeak to StageChannel
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/StageChannel.java
  src/main/java/net/dv8tion/jda/api/entities/StageInstance.java
  src/main/java/net/dv8tion/jda/api/managers/StageInstanceManager.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/StageInstanceAction.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/StageChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/StageInstanceImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/StageInstanceManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/StageInstanceActionImpl.java
Labels: type: enhancement, type: breaking

#2000 Fixes setInvitable in ThreadChannelManager
  src/main/java/net/dv8tion/jda/internal/managers/channel/ChannelManagerImpl.java
Labels: bug

#1997 Restore behavior of zero being passed to find category rather than null
  src/main/java/net/dv8tion/jda/api/entities/ICategorizableChannel.java
Labels: bug
