Repository discord-jda/JDA, pull requests merged in 2022-10, with the labels that each got.

#2254 Handle newly_created gracefully
  src/main/java/net/dv8tion/jda/api/events/thread/ThreadRevealedEvent.java
  src/main/java/net/dv8tion/jda/internal/handle/ThreadCreateHandler.java
Labels: type: enhancement

#2271 Fix manager docs
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/PermissionOverride.java
  src/main/java/net/dv8tion/jda/api/entities/Role.java
  src/main/java/net/dv8tion/jda/api/entities/SelfUser.java
  src/main/java/net/dv8tion/jda/api/entities/Webhook.java
  src/main/java/net/dv8tion/jda/api/entities/channel/middleman/GuildChannel.java
  src/main/java/net/dv8tion/jda/api/entities/emoji/RichCustomEmoji.java
  src/main/java/net/dv8tion/jda/api/entities/templates/Template.java
  src/main/java/net/dv8tion/jda/api/managers/AccountManager.java
  src/main/java/net/dv8tion/jda/api/managers/CustomEmojiManager.java
  src/main/java/net/dv8tion/jda/api/managers/GuildManager.java
  src/main/java/net/dv8tion/jda/api/managers/GuildStickerManager.java
  src/main/java/net/dv8tion/jda/api/managers/PermOverrideManager.java
  src/main/java/net/dv8tion/jda/api/managers/RoleManager.java
  src/main/java/net/dv8tion/jda/api/managers/WebhookManager.java
Labels: type: documentation

#2276 Make ForumTag extend ForumTagSnowflake
  src/main/java/net/dv8tion/jda/api/entities/channel/forums/ForumTag.java
Labels: type: enhancement, hacktoberfest-accepted

#2278 Retain sort order for ThreadChannel#getAppliedTags
  src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/ThreadChannelImpl.java
Labels: bug, hacktoberfest-accepted

#2222 Add GuildManager#setFeatures
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/managers/GuildManager.java
  src/main/java/net/dv8tion/jda/internal/managers/GuildManagerImpl.java
Labels: type: feature

#2279 Handle emoji_id sometimes being 0 instead of null
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/ForumTagImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/ChannelUpdateHandler.java
Labels: bug, type: discord issue

#2293 FileProxy: additional checks on existing files
  src/main/java/net/dv8tion/jda/api/utils/AttachmentProxy.java
  src/main/java/net/dv8tion/jda/api/utils/FileProxy.java
  src/main/java/net/dv8tion/jda/api/utils/ImageProxy.java
Labels: type: enhancement

#2292 Update docs regarding deletion of ephemeral messages
  src/main/java/net/dv8tion/jda/api/interactions/InteractionHook.java
  src/main/java/net/dv8tion/jda/api/interactions/callbacks/IReplyCallback.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/WebhookMessageCreateAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/interactions/ReplyCallbackAction.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
Labels: type: documentation

#2288 Fixes the documentation for SelectMenu
  src/main/java/net/dv8tion/jda/api/interactions/components/selections/SelectMenu.java
Labels: hacktoberfest-accepted, type: documentation

#2286 Update the docs for setEphemeral
  src/main/java/net/dv8tion/jda/api/requests/restaction/WebhookMessageCreateAction.java
Labels: type: documentation

#2261 Put "options" between command path and options, same for choices
  src/main/java/net/dv8tion/jda/api/interactions/commands/localization/LocalizationFunction.java
  src/main/java/net/dv8tion/jda/internal/interactions/command/localization/LocalizationMapper.java
Labels: type: breaking

#2282 Move ModalInteraction into correct package
  src/main/java/net/dv8tion/jda/api/events/interaction/ModalInteractionEvent.java
  src/main/java/net/dv8tion/jda/api/events/interaction/command/GenericCommandInteractionEvent.java
  src/main/java/net/dv8tion/jda/api/events/interaction/component/GenericComponentInteractionCreateEvent.java
  src/main/java/net/dv8tion/jda/api/interactions/Interaction.java
  src/main/java/net/dv8tion/jda/api/interactions/callbacks/IModalCallback.java
  src/main/java/net/dv8tion/jda/api/interactions/components/Component.java
  src/main/java/net/dv8tion/jda/api/interactions/components/text/TextInput.java
  src/main/java/net/dv8tion/jda/api/interactions/components/text/TextInputStyle.java
  src/main/java/net/dv8tion/jda/api/interactions/modals/Modal.java
  src/main/java/net/dv8tion/jda/api/interactions/modals/ModalInteraction.java
  src/main/java/net/dv8tion/jda/internal/handle/InteractionCreateHandler.java
  src/main/java/net/dv8tion/jda/internal/interactions/command/CommandInteractionImpl.java
  src/main/java/net/dv8tion/jda/internal/interactions/component/ComponentInteractionImpl.java
  src/main/java/net/dv8tion/jda/internal/interactions/modal/ModalImpl.java
  src/main/java/net/dv8tion/jda/internal/interactions/modal/ModalInteractionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/interactions/ModalCallbackActionImpl.java
Labels: hacktoberfest-accepted, type: breaking

#2230 Check for empty token in AuthorizationConfig, instead of JDAImpl
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/config/AuthorizationConfig.java
Labels: type: enhancement

#2047 Add support for guild scheduled events v2
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/Permission.java
  src/main/java/net/dv8tion/jda/api/audit/ActionType.java
  src/main/java/net/dv8tion/jda/api/audit/TargetType.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/ScheduledEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/GenericScheduledEventGatewayEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/GenericScheduledEventUserEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/ScheduledEventCreateEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/ScheduledEventDeleteEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/ScheduledEventUserAddEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/ScheduledEventUserRemoveEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/package-info.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/update/GenericScheduledEventUpdateEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/update/ScheduledEventUpdateDescriptionEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/update/ScheduledEventUpdateEndTimeEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/update/ScheduledEventUpdateImageEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/update/ScheduledEventUpdateLocationEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/update/ScheduledEventUpdateNameEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/update/ScheduledEventUpdateStartTimeEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/update/ScheduledEventUpdateStatusEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/api/managers/ScheduledEventManager.java
  src/main/java/net/dv8tion/jda/api/requests/ErrorResponse.java
  src/main/java/net/dv8tion/jda/api/requests/GatewayIntent.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/ScheduledEventAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/ScheduledEventMembersPaginationAction.java
  src/main/java/net/dv8tion/jda/api/utils/cache/CacheFlag.java
  src/main/java/net/dv8tion/jda/api/utils/data/DataArray.java
  src/main/java/net/dv8tion/jda/api/utils/data/DataObject.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/ScheduledEventImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/ChannelDeleteHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/EventCache.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildDeleteHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/ScheduledEventCreateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/ScheduledEventDeleteHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/ScheduledEventUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/ScheduledEventUserHandler.java
  src/main/java/net/dv8tion/jda/internal/managers/ScheduledEventManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/Route.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/ScheduledEventActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/ScheduledEventMembersPaginationActionImpl.java
Labels: type: feature

#2255 Improve channel update handling
  src/main/java/net/dv8tion/jda/internal/entities/ForumChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/TextChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/ThreadChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/VoiceChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/mixin/attribute/IAgeRestrictedChannelMixin.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/mixin/attribute/ICategorizableChannelMixin.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/mixin/attribute/ISlowmodeChannelMixin.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/mixin/attribute/ITopicChannelMixin.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/mixin/middleman/StandardGuildMessageChannelMixin.java
  src/main/java/net/dv8tion/jda/internal/handle/ChannelUpdateHandler.java
Labels: type: enhancement

#2287 Implement new select menus
  src/main/java/net/dv8tion/jda/api/entities/channel/ChannelType.java
  src/main/java/net/dv8tion/jda/api/events/interaction/component/EntitySelectInteractionEvent.java
  src/main/java/net/dv8tion/jda/api/events/interaction/component/GenericSelectMenuInteractionEvent.java
  src/main/java/net/dv8tion/jda/api/events/interaction/component/StringSelectInteractionEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/api/interactions/components/ActionRow.java
  src/main/java/net/dv8tion/jda/api/interactions/components/Component.java
  src/main/java/net/dv8tion/jda/api/interactions/components/selections/EntitySelectInteraction.java
  src/main/java/net/dv8tion/jda/api/interactions/components/selections/EntitySelectMenu.java
  src/main/java/net/dv8tion/jda/api/interactions/components/selections/SelectMenu.java
  src/main/java/net/dv8tion/jda/api/interactions/components/selections/SelectMenuInteraction.java
  src/main/java/net/dv8tion/jda/api/interactions/components/selections/StringSelectInteraction.java
  src/main/java/net/dv8tion/jda/api/interactions/components/selections/StringSelectMenu.java
  src/main/java/net/dv8tion/jda/internal/entities/SelectMenuMentions.java
  src/main/java/net/dv8tion/jda/internal/handle/InteractionCreateHandler.java
  src/main/java/net/dv8tion/jda/internal/interactions/component/EntitySelectInteractionImpl.java
  src/main/java/net/dv8tion/jda/internal/interactions/component/EntitySelectMenuImpl.java
  src/main/java/net/dv8tion/jda/internal/interactions/component/SelectMenuImpl.java
  src/main/java/net/dv8tion/jda/internal/interactions/component/SelectMenuInteractionImpl.java
  src/main/java/net/dv8tion/jda/internal/interactions/component/StringSelectInteractionImpl.java
  src/main/java/net/dv8tion/jda/internal/interactions/component/StringSelectMenuImpl.java
Labels: type: feature, type: breaking

#2314 Fix NullPointerException in GuildManagerImpl#addFeatures and GuildManagerImpl#removeFeatures
  src/main/java/net/dv8tion/jda/internal/managers/GuildManagerImpl.java
Labels: bug

#2306 Add some missing documentation to clarify cache
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/GenericScheduledEventGatewayEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/GenericScheduledEventUserEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/ScheduledEventCreateEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/ScheduledEventDeleteEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/ScheduledEventUserAddEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/ScheduledEventUserRemoveEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/update/GenericScheduledEventUpdateEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/update/ScheduledEventUpdateDescriptionEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/update/ScheduledEventUpdateEndTimeEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/update/ScheduledEventUpdateImageEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/update/ScheduledEventUpdateLocationEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/update/ScheduledEventUpdateNameEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/update/ScheduledEventUpdateStartTimeEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/update/ScheduledEventUpdateStatusEvent.java
  src/main/java/net/dv8tion/jda/api/events/user/update/UserUpdateOnlineStatusEvent.java
Labels: type: documentation

#2316 Fix GuildSticker#retrieveOwner
  src/main/java/net/dv8tion/jda/api/entities/sticker/GuildSticker.java
  src/main/java/net/dv8tion/jda/internal/entities/sticker/GuildStickerImpl.java
Labels: bug

#2297 Fix MemberCacheViewImpl#getElementsWithRoles and Guild#findMembersWithRoles ignoring the public role
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/internal/utils/cache/MemberCacheViewImpl.java
Labels: bug, hacktoberfest-accepted, type: semi-breaking

#2251 Add slash command mentions
  src/main/java/net/dv8tion/jda/api/entities/Mentions.java
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/Command.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/CommandInteractionPayload.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/ICommandReference.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/SlashCommandReference.java
  src/main/java/net/dv8tion/jda/internal/entities/SelectMenuMentions.java
  src/main/java/net/dv8tion/jda/internal/entities/mentions/AbstractMentions.java
  src/main/java/net/dv8tion/jda/internal/interactions/command/CommandImpl.java
Labels: type: feature, type: breaking

#2317 [Bugfix] Mark ForumChannel as a TopicChannelMixin
  src/main/java/net/dv8tion/jda/api/entities/channel/ChannelField.java
  src/main/java/net/dv8tion/jda/internal/entities/ForumChannelImpl.java
Labels: bug

#2295 Make Widget an interface and move it to it's own file
  src/main/java/net/dv8tion/jda/api/entities/Widget.java
  src/main/java/net/dv8tion/jda/api/utils/WidgetUtil.java
  src/main/java/net/dv8tion/jda/api/utils/package-info.java
  src/main/java/net/dv8tion/jda/internal/entities/WidgetImpl.java
Labels: hacktoberfest-accepted, type: breaking
