Repository discord-jda/JDA, pull requests merged in 2022-06, with the labels that each got.

#2144 Fix missing guild id when deleting guild stickers
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Labels: bug

#2151 Fix filterHidden in GuildImpl#getChannels
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Labels: bug

#2128 Replaced occurrences of TextChannel with GuildMessageChannel
  src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
Labels: type: documentation

#2113 Add Support for Application-Command Permissions V2
  src/examples/java/SlashBotExample.java
  src/main/java/net/dv8tion/jda/api/audit/ActionType.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/events/interaction/command/ApplicationCommandUpdatePrivilegesEvent.java
  src/main/java/net/dv8tion/jda/api/events/interaction/command/ApplicationUpdatePrivilegesEvent.java
  src/main/java/net/dv8tion/jda/api/events/interaction/command/GenericPrivilegeUpdateEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/Command.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/DefaultMemberPermissions.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/PrivilegeConfig.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/build/CommandData.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/build/SlashCommandData.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/privileges/CommandPrivilege.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/privileges/IntegrationPrivilege.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/privileges/PrivilegeTargetType.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/CommandCreateAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/CommandEditAction.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/ApplicationCommandPermissionsUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/interactions/CommandDataImpl.java
  src/main/java/net/dv8tion/jda/internal/interactions/command/CommandImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/CommandCreateActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/CommandEditActionImpl.java
  src/test/java/CommandDataTest.java
Labels: type: feature, type: breaking

#2158 Make more use of CacheRestAction
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/ThreadChannel.java
  src/main/java/net/dv8tion/jda/api/entities/User.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/SelfUserImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/ThreadChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/UserImpl.java
Labels: type: enhancement, type: breaking
