Repository discord-jda/JDA, pull requests merged in 2022-04, with the labels that each got.

#2085 Improve handling of Role#getPosition and canInteract
  src/main/java/net/dv8tion/jda/internal/entities/RoleImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildRoleDeleteHandler.java
  src/main/java/net/dv8tion/jda/internal/utils/PermissionUtil.java
Labels: type: enhancement

#1936 Add Tags, Default Install Url, Scopes and Permissions to ApplicationInfo
  src/main/java/net/dv8tion/jda/api/entities/ApplicationInfo.java
  src/main/java/net/dv8tion/jda/internal/entities/ApplicationInfoImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
Labels: type: feature

#2065 Add UserSnowflake and improve User#fromId
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/Member.java
  src/main/java/net/dv8tion/jda/api/entities/User.java
  src/main/java/net/dv8tion/jda/api/entities/UserSnowflake.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/AuditableRestAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/MemberAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/AuditLogPaginationAction.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/UserById.java
  src/main/java/net/dv8tion/jda/internal/entities/UserImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/UserSnowflakeImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/AuditLogPaginationActionImpl.java
Labels: type: enhancement, type: breaking

#2076 Implement pagination for the guild ban list
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/BanPaginationAction.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/BanPaginationActionImpl.java
Labels: type: breaking

#2026 Return MessageReaction for getReactionX methods
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
Labels: type: enhancement, type: breaking

#2080 Fix rate limiter not shutting down if there is an empty bucket at shutdown
  src/main/java/net/dv8tion/jda/internal/requests/ratelimit/BotRateLimiter.java
Labels: bug

#2044 Add try/catch abstraction for RestAction operators
  src/main/java/net/dv8tion/jda/internal/requests/restaction/operator/DelayRestAction.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/operator/FlatMapRestAction.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/operator/MapRestAction.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/operator/RestActionOperator.java
Labels: type: enhancement

#1819 Dependency upgrades
  README.md
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: v5

#2067 Remove confusing permission override methods
  src/main/java/net/dv8tion/jda/api/entities/IPermissionContainer.java
  src/main/java/net/dv8tion/jda/api/entities/PermissionOverride.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/PermissionOverrideAction.java
  src/main/java/net/dv8tion/jda/internal/entities/mixin/channel/attribute/IPermissionContainerMixin.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/PermissionOverrideActionImpl.java
Labels: type: breaking

#2110 Fix broken context map config
  src/main/java/net/dv8tion/jda/internal/utils/config/MetaConfig.java
Labels: bug

#2112 Improve check for GuildVoiceState#declineSpeaker
  src/main/java/net/dv8tion/jda/api/entities/GuildVoiceState.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildVoiceStateImpl.java
Labels: bug
