Repository discord-jda/JDA, pull requests merged in 2022-09, with the labels that each got.

#2228 Update to gateway version 10
  src/main/java/net/dv8tion/jda/api/JDAInfo.java
Labels: type: breaking

#2239 Use toAbsolutePath in FileProxy#downloadToPath
  src/main/java/net/dv8tion/jda/api/utils/FileProxy.java
Labels: bug

#2241 Add support for component-only messages
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
  src/main/java/net/dv8tion/jda/api/entities/WebhookClient.java
  src/main/java/net/dv8tion/jda/api/interactions/callbacks/IReplyCallback.java
  src/main/java/net/dv8tion/jda/api/utils/messages/AbstractMessageBuilder.java
  src/main/java/net/dv8tion/jda/api/utils/messages/MessageCreateBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/AbstractWebhookClient.java
Labels: type: feature

#2169 add support for string option bounds
  src/main/java/net/dv8tion/jda/api/interactions/commands/Command.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/build/OptionData.java
Labels: type: feature

#2212 Add DataPath util
  src/main/java/net/dv8tion/jda/api/utils/data/DataArray.java
  src/main/java/net/dv8tion/jda/api/utils/data/DataPath.java
  src/main/java/net/dv8tion/jda/internal/handle/InteractionCreateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/ReadyHandler.java
  src/main/java/net/dv8tion/jda/internal/interactions/command/CommandImpl.java
  src/main/java/net/dv8tion/jda/internal/interactions/command/CommandInteractionImpl.java
  src/main/java/net/dv8tion/jda/internal/interactions/command/CommandInteractionPayloadImpl.java
  src/main/java/net/dv8tion/jda/internal/interactions/command/ContextInteractionImpl.java
  src/main/java/net/dv8tion/jda/internal/interactions/command/MessageContextInteractionImpl.java
  src/main/java/net/dv8tion/jda/internal/interactions/command/UserContextInteractionImpl.java
  src/test/java/DataPathTest.java
Labels: type: feature, type: proposal

#2235 Use String#intern for guild features and atoms
  src/main/java/net/dv8tion/jda/api/utils/data/etf/ExTermDecoder.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildUpdateHandler.java
Labels: type: proposal

#2237 Improve handling of server errors and fix some code duplication
  src/main/java/net/dv8tion/jda/internal/requests/Requester.java
Labels: type: enhancement

#2136 Add category feature to ChannelOrderAction
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/order/ChannelOrderAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/order/OrderAction.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/order/ChannelOrderActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/order/OrderActionImpl.java
Labels: type: feature, type: breaking

#2248 Change handling of query parameters for websocket connections
  src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/internal/utils/IOUtil.java
Labels: type: enhancement

#2252 Improve usability of AudioChannel
  src/main/java/net/dv8tion/jda/api/audio/factory/IPacketProvider.java
  src/main/java/net/dv8tion/jda/api/entities/GuildVoiceState.java
  src/main/java/net/dv8tion/jda/api/entities/channel/middleman/AudioChannel.java
  src/main/java/net/dv8tion/jda/api/entities/channel/middleman/StandardGuildChannel.java
  src/main/java/net/dv8tion/jda/api/entities/channel/unions/AudioChannelUnion.java
  src/main/java/net/dv8tion/jda/api/events/guild/voice/GenericGuildVoiceUpdateEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceJoinEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceLeaveEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceMoveEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceUpdateEvent.java
  src/main/java/net/dv8tion/jda/api/managers/AudioManager.java
  src/main/java/net/dv8tion/jda/api/managers/channel/middleman/AudioChannelManager.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildVoiceStateImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/mixin/middleman/AudioChannelMixin.java
  src/main/java/net/dv8tion/jda/internal/managers/AudioManagerImpl.java
Labels: type: enhancement

#2227 Added RestAction#onSuccess
  src/main/java/net/dv8tion/jda/api/requests/RestAction.java
Labels: type: feature

#2256 Remove default_sort_order
  src/main/java/net/dv8tion/jda/api/audit/AuditLogKey.java
  src/main/java/net/dv8tion/jda/api/entities/channel/ChannelField.java
  src/main/java/net/dv8tion/jda/api/entities/channel/concrete/ForumChannel.java
  src/main/java/net/dv8tion/jda/api/events/channel/update/ChannelUpdateDefaultSortOrderEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/ForumChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/ChannelUpdateHandler.java
Labels: type: breaking

#2249 Make annotation dependencies compileOnly
  build.gradle.kts
Labels: type: enhancement, type: semi-breaking

#2259 Fix check for ChannelAction#setCategory
  src/main/java/net/dv8tion/jda/internal/requests/restaction/ChannelActionImpl.java
Labels: bug

#2260 Fix some checks not throwing the intended exception
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/Member.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Labels: bug

#1952 Update event hierarchy
  src/main/java/net/dv8tion/jda/api/JDABuilder.java
  src/main/java/net/dv8tion/jda/api/events/guild/GuildReadyEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/GuildTimeoutEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/voice/GenericGuildVoiceUpdateEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceJoinEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceLeaveEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceMoveEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceUpdateEvent.java
  src/main/java/net/dv8tion/jda/api/events/package-info.java
  src/main/java/net/dv8tion/jda/api/events/session/GenericSessionEvent.java
  src/main/java/net/dv8tion/jda/api/events/session/ReadyEvent.java
  src/main/java/net/dv8tion/jda/api/events/session/SessionDisconnectEvent.java
  src/main/java/net/dv8tion/jda/api/events/session/SessionInvalidateEvent.java
  src/main/java/net/dv8tion/jda/api/events/session/SessionRecreateEvent.java
  src/main/java/net/dv8tion/jda/api/events/session/SessionResumeEvent.java
  src/main/java/net/dv8tion/jda/api/events/session/SessionState.java
  src/main/java/net/dv8tion/jda/api/events/session/ShutdownEvent.java
  src/main/java/net/dv8tion/jda/api/events/session/package-info.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildMemberRemoveHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/VoiceStateUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
Labels: type: enhancement, type: breaking

#2272 fix: Use correct "flags" field for message create action
  src/main/java/net/dv8tion/jda/api/utils/messages/MessageCreateBuilder.java
Labels: bug
