Repository discord-jda/JDA, pull requests merged in 2022-08, with the labels that each got.

#2198 Add sticker features for audit logs
  src/main/java/net/dv8tion/jda/api/audit/ActionType.java
  src/main/java/net/dv8tion/jda/api/audit/AuditLogKey.java
  src/main/java/net/dv8tion/jda/api/audit/TargetType.java
Labels: type: feature

#2201 Fix ban pagination
  src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/BanPaginationActionImpl.java
Labels: bug

#2200 Improve usage of cache in Guild#retrieveMemberById
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Labels: type: enhancement

#2202 Add ApplicationInfo#getFlags
  src/main/java/net/dv8tion/jda/api/entities/ApplicationInfo.java
  src/main/java/net/dv8tion/jda/internal/entities/ApplicationInfoImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
Labels: type: feature

#2211 Fix CommandAutoCompleteInteraction#getChannel
  src/main/java/net/dv8tion/jda/internal/interactions/command/CommandAutoCompleteInteractionImpl.java
Labels: bug, priority: high

#2204 Implement `GuildChannel#getJumpUrl`
  src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java
Labels: type: feature

#2102 unify method checks wording in docs
  src/main/java/net/dv8tion/jda/api/interactions/callbacks/IAutoCompleteCallback.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/build/OptionData.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/interactions/AutoCompleteCallbackAction.java
Labels: type: documentation

#2209 Add support for setting voice region on channel creation/copy
  src/main/java/net/dv8tion/jda/api/requests/restaction/ChannelAction.java
  src/main/java/net/dv8tion/jda/internal/entities/StageChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/VoiceChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/ChannelActionImpl.java
Labels: type: feature

#2218 Remove ChannelAction#setType
  src/main/java/net/dv8tion/jda/api/requests/restaction/ChannelAction.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/ChannelActionImpl.java
Labels: bug, type: breaking

#2220 Return immutable reconstructed interaction object lists
  src/main/java/net/dv8tion/jda/api/interactions/commands/build/SlashCommandData.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/build/SubcommandData.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/build/SubcommandGroupData.java
  src/main/java/net/dv8tion/jda/internal/interactions/CommandDataImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/Helpers.java
Labels: type: enhancement

#2225 Renamed MessageCreateBuilder#fromEdit() to fromEditData
  src/main/java/net/dv8tion/jda/api/utils/messages/MessageCreateBuilder.java
Labels: type: breaking

#2025 Invalid token exception
  README.md
  src/examples/java/AudioEchoExample.java
  src/examples/java/MessageLoggerExample.java
  src/examples/java/SlashBotExample.java
  src/main/java/net/dv8tion/jda/api/JDABuilder.java
  src/main/java/net/dv8tion/jda/api/exceptions/InvalidTokenException.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
  src/main/java/net/dv8tion/jda/api/utils/SessionControllerAdapter.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
Labels: type: breaking

#2229 Add support for ban deletion with seconds precision
  src/examples/java/SlashBotExample.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/Member.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/AuditableRestAction.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Labels: type: feature, type: breaking
