Repository discord-jda/JDA, pull requests merged in 2023-11, with the labels that each got.

#2581 Remove outdate todo comments and update outdated logic in thread channels
  src/main/java/net/dv8tion/jda/api/entities/channel/ChannelField.java
  src/main/java/net/dv8tion/jda/api/entities/channel/attribute/ICategorizableChannel.java
  src/main/java/net/dv8tion/jda/api/entities/channel/attribute/IPermissionContainer.java
  src/main/java/net/dv8tion/jda/api/entities/channel/attribute/IPositionableChannel.java
  src/main/java/net/dv8tion/jda/api/entities/channel/concrete/ThreadChannel.java
  src/main/java/net/dv8tion/jda/api/entities/channel/unions/DefaultGuildChannelUnion.java
  src/main/java/net/dv8tion/jda/api/events/guild/override/PermissionOverrideUpdateEvent.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/PermissionOverrideAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/WebhookMessageEditAction.java
  src/main/java/net/dv8tion/jda/internal/entities/ThreadMemberImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/ThreadChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/TypingStartHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/VoiceStateUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/PermissionOverrideActionImpl.java
Labels: type: enhancement

#2584 Add support for resetting min/max length in TextInput.Builder
  src/main/java/net/dv8tion/jda/api/interactions/components/text/TextInput.java
Labels: type: feature

#2585 Fix orphaned rate-limit buckets
  src/main/java/net/dv8tion/jda/api/requests/SequentialRestRateLimiter.java
Labels: bug

#2588 Fix incorrect index used in attachment update requests
  src/main/java/net/dv8tion/jda/api/utils/messages/MessageEditData.java
Labels: bug

#2463 Change thread model used for requests
  src/main/java/net/dv8tion/jda/api/JDABuilder.java
  src/main/java/net/dv8tion/jda/api/exceptions/InvalidTokenException.java
  src/main/java/net/dv8tion/jda/api/requests/RestRateLimiter.java
  src/main/java/net/dv8tion/jda/api/requests/SequentialRestRateLimiter.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/api/sharding/ThreadPoolProvider.java
  src/main/java/net/dv8tion/jda/api/utils/SessionControllerAdapter.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/config/ThreadingConfig.java
  src/main/java/net/dv8tion/jda/internal/utils/config/sharding/ThreadingProviderConfig.java
Labels: type: enhancement, type: semi-breaking
