Repository discord-jda/JDA, pull requests merged in 2023-02, with the labels that each got.

#2389 ")" was missing in README.md
  README.md
Labels: type: documentation

#2388 Add Modal.Builder#addComponents
  src/main/java/net/dv8tion/jda/api/interactions/modals/Modal.java
  src/main/java/net/dv8tion/jda/internal/interactions/modal/ModalImpl.java
Labels: type: enhancement, type: semi-breaking

#2393 Add `SUPPRESS_NOTIFICATIONS` flag for message
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/utils/messages/AbstractMessageBuilder.java
  src/main/java/net/dv8tion/jda/api/utils/messages/MessageCreateBuilder.java
  src/main/java/net/dv8tion/jda/api/utils/messages/MessageCreateData.java
  src/main/java/net/dv8tion/jda/api/utils/messages/MessageCreateRequest.java
  src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/internal/utils/message/MessageCreateBuilderMixin.java
Labels: type: feature

#2375 Necessary additions for role subscriptions
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/entities/Invite.java
  src/main/java/net/dv8tion/jda/api/entities/MessageType.java
  src/main/java/net/dv8tion/jda/api/entities/Role.java
  src/main/java/net/dv8tion/jda/api/entities/RoleConnectionMetadata.java
  src/main/java/net/dv8tion/jda/api/requests/ErrorResponse.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/RoleImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildRoleUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/requests/Route.java
  src/main/java/net/dv8tion/jda/internal/utils/Checks.java
Labels: type: feature

#2401 Catch parsing exception for scheduled events
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/handle/ScheduledEventUpdateHandler.java
Labels: bug

#2406 Catch errors thrown during login validation
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
Labels: bug

#2371 Add new message types
  src/main/java/net/dv8tion/jda/api/entities/MessageType.java
Labels: type: feature
