Repository discord-jda/JDA, pull requests merged in 2023-05, with the labels that each got.

#2458 Remove timeout for rate-limit pool
  src/main/java/net/dv8tion/jda/api/requests/SequentialRestRateLimiter.java
  src/main/java/net/dv8tion/jda/internal/utils/config/ThreadingConfig.java
Labels: bug

#2434 Update permissions
  src/main/java/net/dv8tion/jda/api/Permission.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/emoji/RichCustomEmoji.java
  src/main/java/net/dv8tion/jda/api/entities/sticker/GuildSticker.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/emoji/RichCustomEmojiImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/sticker/GuildStickerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/CustomEmojiManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/GuildStickerManagerImpl.java
Labels: type: semi-breaking

#2464 Fix slow shutdown during reconnects
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
Labels: type: enhancement

#2465 Improve handling of global rate-limit
  src/main/java/net/dv8tion/jda/api/requests/SequentialRestRateLimiter.java
Labels: type: enhancement

#2429 Add automod support
  src/main/java/net/dv8tion/jda/api/audit/ActionType.java
  src/main/java/net/dv8tion/jda/api/audit/AuditLogKey.java
  src/main/java/net/dv8tion/jda/api/audit/TargetType.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/WebhookClient.java
  src/main/java/net/dv8tion/jda/api/entities/automod/AutoModEventType.java
  src/main/java/net/dv8tion/jda/api/entities/automod/AutoModExecution.java
  src/main/java/net/dv8tion/jda/api/entities/automod/AutoModResponse.java
  src/main/java/net/dv8tion/jda/api/entities/automod/AutoModRule.java
  src/main/java/net/dv8tion/jda/api/entities/automod/AutoModTriggerType.java
  src/main/java/net/dv8tion/jda/api/entities/automod/build/AbstractKeywordTriggerConfig.java
  src/main/java/net/dv8tion/jda/api/entities/automod/build/AbstractTriggerConfig.java
  src/main/java/net/dv8tion/jda/api/entities/automod/build/AntiSpamTriggerConfig.java
  src/main/java/net/dv8tion/jda/api/entities/automod/build/AutoModRuleData.java
  src/main/java/net/dv8tion/jda/api/entities/automod/build/CustomKeywordTriggerConfig.java
  src/main/java/net/dv8tion/jda/api/entities/automod/build/MentionSpamTriggerConfig.java
  src/main/java/net/dv8tion/jda/api/entities/automod/build/PresetKeywordTriggerConfig.java
  src/main/java/net/dv8tion/jda/api/entities/automod/build/TriggerConfig.java
  src/main/java/net/dv8tion/jda/api/entities/channel/concrete/ForumChannel.java
  src/main/java/net/dv8tion/jda/api/entities/channel/middleman/MessageChannel.java
  src/main/java/net/dv8tion/jda/api/events/automod/AutoModExecutionEvent.java
  src/main/java/net/dv8tion/jda/api/events/automod/AutoModRuleCreateEvent.java
  src/main/java/net/dv8tion/jda/api/events/automod/AutoModRuleDeleteEvent.java
  src/main/java/net/dv8tion/jda/api/events/automod/AutoModRuleUpdateEvent.java
  src/main/java/net/dv8tion/jda/api/events/automod/GenericAutoModRuleEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/api/interactions/callbacks/IReplyCallback.java
  src/main/java/net/dv8tion/jda/api/managers/AutoModRuleManager.java
  src/main/java/net/dv8tion/jda/api/requests/ErrorResponse.java
  src/main/java/net/dv8tion/jda/api/requests/GatewayIntent.java
  src/main/java/net/dv8tion/jda/api/requests/Route.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/automod/AutoModExecutionImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/automod/AutoModResponseImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/automod/AutoModRuleImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/AutoModExecutionHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/AutoModRuleHandler.java
  src/main/java/net/dv8tion/jda/internal/managers/AutoModRuleManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/internal/utils/Helpers.java
Labels: type: feature

#2363 Properly escape quotes with leading spaces
  src/main/java/net/dv8tion/jda/api/utils/MarkdownSanitizer.java
  src/test/java/MarkdownTest.java
Labels: type: enhancement
