Repository discord-jda/JDA, pull requests merged in 2023-08, with the labels that each got.

#2514 Fix IllegalStateException in Message#getCategory
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
Labels: type: enhancement

#2508 Add supplier based FileUpload
  src/main/java/net/dv8tion/jda/api/utils/FileUpload.java
  src/main/java/net/dv8tion/jda/internal/utils/IOUtil.java
  src/main/java/net/dv8tion/jda/internal/utils/requestbody/BufferedRequestBody.java
  src/main/java/net/dv8tion/jda/internal/utils/requestbody/DataSupplierBody.java
  src/main/java/net/dv8tion/jda/internal/utils/requestbody/TypedBody.java
Labels: type: feature

#2485 Add DiscordLocale#toLocale
  src/main/java/net/dv8tion/jda/api/interactions/DiscordLocale.java
Labels: type: feature

#2521 Add custom status support for bots
  src/main/java/net/dv8tion/jda/api/entities/Activity.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/managers/PresenceImpl.java
Labels: type: feature, status: awaiting discord docs pr

#2524 Added support for custom statuses
  src/main/java/net/dv8tion/jda/api/entities/Activity.java
Labels: bug

#2523 Add Activity#withState
  src/main/java/net/dv8tion/jda/api/entities/Activity.java
  src/main/java/net/dv8tion/jda/api/entities/RichPresence.java
  src/main/java/net/dv8tion/jda/api/utils/data/DataObject.java
  src/main/java/net/dv8tion/jda/internal/entities/ActivityImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/RichPresenceImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/PresenceImpl.java
  src/test/java/net/dv8tion/jda/entities/ActivityTest.java
Labels: type: feature

#2519 fix symmetricity of CustomEmojiImpl/RichCustomEmojiImpl#equals
  src/main/java/net/dv8tion/jda/internal/entities/emoji/CustomEmojiImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/emoji/RichCustomEmojiImpl.java
Labels: bug
