Repository discord-jda/JDA, pull requests merged in 2023-07, with the labels that each got.

#2492 Update User#formatTo
  src/main/java/net/dv8tion/jda/internal/entities/UserImpl.java
Labels: type: enhancement

#2493 Add details about posts being threads in some more places
  src/main/java/net/dv8tion/jda/api/entities/channel/attribute/IGuildChannelContainer.java
  src/main/java/net/dv8tion/jda/api/entities/channel/attribute/IThreadContainer.java
  src/main/java/net/dv8tion/jda/api/entities/channel/concrete/ThreadChannel.java
  src/main/java/net/dv8tion/jda/api/entities/channel/forums/ForumPost.java
Labels: type: documentation

#2494 Fix handling of thread update for unknown parent
  src/main/java/net/dv8tion/jda/internal/handle/ThreadCreateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/ThreadUpdateHandler.java
Labels: bug

#2496 Deprecate and replace onUserSpeaking
  src/main/java/net/dv8tion/jda/api/audio/hooks/ConnectionListener.java
  src/main/java/net/dv8tion/jda/api/audio/hooks/ListenerProxy.java
  src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java
Labels: type: enhancement, beta-blocker

#2499 Add the message author id to message reaction events
  src/main/java/net/dv8tion/jda/api/events/message/react/MessageReactionAddEvent.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageReactionHandler.java
Labels: type: feature

#2490 Fix choices having an "options" prefix when automatically localizing
  src/main/java/net/dv8tion/jda/internal/interactions/command/localization/LocalizationMapper.java
  src/test/java/LocalizationTest.java
  src/test/resources/MyCommands_fr.properties
Labels: bug, type: semi-breaking, beta-blocker

#2513 Fix MessageCreateRequest#applyData not suppressing embeds
  src/main/java/net/dv8tion/jda/api/utils/messages/MessageCreateRequest.java
Labels: bug
