Repository discord-jda/JDA, pull requests merged in 2023-12, with the labels that each got.

#2589 Add more logging to request handling
  src/main/java/net/dv8tion/jda/api/requests/Request.java
  src/main/java/net/dv8tion/jda/api/requests/Response.java
  src/main/java/net/dv8tion/jda/internal/requests/Requester.java
Labels: type: enhancement

#2532 Add voice status feature
  src/main/java/net/dv8tion/jda/api/Permission.java
  src/main/java/net/dv8tion/jda/api/audit/ActionType.java
  src/main/java/net/dv8tion/jda/api/audit/AuditLogKey.java
  src/main/java/net/dv8tion/jda/api/entities/channel/ChannelField.java
  src/main/java/net/dv8tion/jda/api/entities/channel/attribute/IVoiceStatusChannel.java
  src/main/java/net/dv8tion/jda/api/entities/channel/concrete/VoiceChannel.java
  src/main/java/net/dv8tion/jda/api/events/channel/update/ChannelUpdateVoiceStatusEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/api/requests/Route.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/VoiceChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/VoiceChannelStatusUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
Labels: type: feature

#2531 Add missing message types
  src/main/java/net/dv8tion/jda/api/entities/MessageType.java
Labels: type: feature

#2593 Fix incorrect hook injection for message context commands
  src/main/java/net/dv8tion/jda/internal/interactions/command/MessageContextInteractionImpl.java
Labels: bug

#2591 Updating Dependencies
  build.gradle.kts
Labels: type: dependencies

#2592 Add check for max number of fields in EmbedBuilder
  src/main/java/net/dv8tion/jda/api/EmbedBuilder.java
  src/main/java/net/dv8tion/jda/api/entities/MessageEmbed.java
Labels: type: enhancement
