Repository discord-jda/JDA, pull requests merged in 2024-05, with the labels that each got.

#2675 Add more static analyzer annotations
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/audit/AuditLogEntry.java
  src/main/java/net/dv8tion/jda/api/entities/ApplicationInfo.java
  src/main/java/net/dv8tion/jda/api/entities/ApplicationTeam.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/Member.java
  src/main/java/net/dv8tion/jda/api/entities/Mentions.java
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/MessageEmbed.java
  src/main/java/net/dv8tion/jda/api/entities/MessageHistory.java
  src/main/java/net/dv8tion/jda/api/entities/StageInstance.java
  src/main/java/net/dv8tion/jda/api/entities/User.java
  src/main/java/net/dv8tion/jda/api/entities/channel/attribute/IGuildChannelContainer.java
  src/main/java/net/dv8tion/jda/api/entities/channel/attribute/IMemberContainer.java
  src/main/java/net/dv8tion/jda/api/entities/channel/attribute/IPermissionContainer.java
  src/main/java/net/dv8tion/jda/api/entities/channel/attribute/IPostContainer.java
  src/main/java/net/dv8tion/jda/api/entities/channel/attribute/IThreadContainer.java
  src/main/java/net/dv8tion/jda/api/entities/channel/attribute/IWebhookContainer.java
  src/main/java/net/dv8tion/jda/api/entities/channel/concrete/Category.java
  src/main/java/net/dv8tion/jda/api/entities/channel/concrete/ThreadChannel.java
  src/main/java/net/dv8tion/jda/api/entities/channel/middleman/MessageChannel.java
  src/main/java/net/dv8tion/jda/api/entities/emoji/RichCustomEmoji.java
  src/main/java/net/dv8tion/jda/api/entities/messages/MessagePoll.java
  src/main/java/net/dv8tion/jda/api/entities/sticker/StickerPack.java
  src/main/java/net/dv8tion/jda/api/entities/templates/TemplateChannel.java
  src/main/java/net/dv8tion/jda/api/entities/templates/TemplateGuild.java
  src/main/java/net/dv8tion/jda/api/hooks/AnnotatedEventManager.java
  src/main/java/net/dv8tion/jda/api/hooks/InterfacedEventManager.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/Command.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/PrivilegeConfig.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/build/OptionData.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/build/SlashCommandData.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/build/SubcommandData.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/build/SubcommandGroupData.java
  src/main/java/net/dv8tion/jda/api/interactions/components/LayoutComponent.java
  src/main/java/net/dv8tion/jda/api/interactions/components/selections/EntitySelectMenu.java
  src/main/java/net/dv8tion/jda/api/interactions/components/selections/StringSelectInteraction.java
  src/main/java/net/dv8tion/jda/api/interactions/modals/Modal.java
  src/main/java/net/dv8tion/jda/api/interactions/modals/ModalInteraction.java
  src/main/java/net/dv8tion/jda/api/managers/GuildWelcomeScreenManager.java
  src/main/java/net/dv8tion/jda/api/requests/RestAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/order/OrderAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/PaginationAction.java
  src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
  src/main/java/net/dv8tion/jda/api/utils/cache/CacheView.java
  src/main/java/net/dv8tion/jda/api/utils/cache/MemberCacheView.java
  src/main/java/net/dv8tion/jda/api/utils/cache/UnifiedMemberCacheView.java
  src/main/java/net/dv8tion/jda/api/utils/concurrent/Task.java
Labels: type: documentation

#2677 fix(docs): use useCache(false) if you want to make a request
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
Labels: type: documentation

#2674 Update SLF4J api and jackson
  settings.gradle.kts
  src/main/java/net/dv8tion/jda/internal/handle/GuildBanHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageReactionHandler.java
  src/main/java/net/dv8tion/jda/internal/utils/FallbackLogger.java
  src/main/java/net/dv8tion/jda/internal/utils/JDALogger.java
  src/main/java/net/dv8tion/jda/internal/utils/SimpleLogger.java
Labels: type: dependencies

#2679 Make channel access checks consistent
  src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/PrivateChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/VoiceChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/mixin/ChannelMixin.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/mixin/middleman/AudioChannelMixin.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/mixin/middleman/GuildChannelMixin.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/mixin/middleman/GuildMessageChannelMixin.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/mixin/middleman/MessageChannelMixin.java
Labels: type: enhancement
