Repository discord-jda/JDA, pull requests merged in 2024-11, with the labels that each got.

#2761 Fix links to LavaPlayer in AudioManager
  src/main/java/net/dv8tion/jda/api/managers/AudioManager.java
Labels: type: documentation

#2757 Fix typo in RoleManager
  src/main/java/net/dv8tion/jda/api/managers/RoleManager.java
Labels: type: documentation

#2758 Fix typo in JDA#isAutoReconnect javadocs
  src/main/java/net/dv8tion/jda/api/JDA.java
Labels: type: documentation

#2752 Add premium buttons
  src/main/java/net/dv8tion/jda/api/entities/SkuSnowflake.java
  src/main/java/net/dv8tion/jda/api/events/interaction/command/GenericCommandInteractionEvent.java
  src/main/java/net/dv8tion/jda/api/events/interaction/component/GenericComponentInteractionCreateEvent.java
  src/main/java/net/dv8tion/jda/api/interactions/Interaction.java
  src/main/java/net/dv8tion/jda/api/interactions/callbacks/IPremiumRequiredReplyCallback.java
  src/main/java/net/dv8tion/jda/api/interactions/components/LayoutComponent.java
  src/main/java/net/dv8tion/jda/api/interactions/components/buttons/Button.java
  src/main/java/net/dv8tion/jda/api/interactions/components/buttons/ButtonStyle.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/interactions/InteractionCallbackAction.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/interactions/PremiumRequiredCallbackAction.java
  src/main/java/net/dv8tion/jda/internal/entities/SkuSnowflakeImpl.java
  src/main/java/net/dv8tion/jda/internal/interactions/component/ButtonImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/ComponentsUtil.java
  src/test/java/net/dv8tion/jda/test/interactions/ButtonTests.java
  src/test/java/net/dv8tion/jda/test/util/ComponentsUtilTest.java
Labels: type: feature

#2726 Add support for Application Emoji
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/entities/emoji/ApplicationEmoji.java
  src/main/java/net/dv8tion/jda/api/entities/emoji/CustomEmoji.java
  src/main/java/net/dv8tion/jda/api/entities/emoji/Emoji.java
  src/main/java/net/dv8tion/jda/api/entities/emoji/EmojiUnion.java
  src/main/java/net/dv8tion/jda/api/managers/ApplicationEmojiManager.java
  src/main/java/net/dv8tion/jda/api/requests/Route.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/emoji/ApplicationEmojiImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/emoji/CustomEmojiImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/emoji/RichCustomEmojiImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/emoji/UnicodeEmojiImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/ApplicationEmojiManagerImpl.java
  src/test/java/net/dv8tion/jda/test/restaction/CreateApplicationEmojiTest.java
Labels: type: feature

#2755 Replace `GatewayIntent#GUILD_EMOJIS_AND_STICKERS` with `GUILD_EXPRESSIONS`
  src/main/java/net/dv8tion/jda/api/events/emoji/EmojiAddedEvent.java
  src/main/java/net/dv8tion/jda/api/events/emoji/EmojiRemovedEvent.java
  src/main/java/net/dv8tion/jda/api/events/emoji/GenericEmojiEvent.java
  src/main/java/net/dv8tion/jda/api/events/emoji/package-info.java
  src/main/java/net/dv8tion/jda/api/events/emoji/update/EmojiUpdateNameEvent.java
  src/main/java/net/dv8tion/jda/api/events/emoji/update/EmojiUpdateRolesEvent.java
  src/main/java/net/dv8tion/jda/api/events/emoji/update/GenericEmojiUpdateEvent.java
  src/main/java/net/dv8tion/jda/api/events/emoji/update/package-info.java
  src/main/java/net/dv8tion/jda/api/events/sticker/GenericGuildStickerEvent.java
  src/main/java/net/dv8tion/jda/api/events/sticker/GuildStickerAddedEvent.java
  src/main/java/net/dv8tion/jda/api/events/sticker/GuildStickerRemovedEvent.java
  src/main/java/net/dv8tion/jda/api/events/sticker/package-info.java
  src/main/java/net/dv8tion/jda/api/events/sticker/update/GenericGuildStickerUpdateEvent.java
  src/main/java/net/dv8tion/jda/api/events/sticker/update/GuildStickerUpdateAvailableEvent.java
  src/main/java/net/dv8tion/jda/api/events/sticker/update/GuildStickerUpdateDescriptionEvent.java
  src/main/java/net/dv8tion/jda/api/events/sticker/update/GuildStickerUpdateNameEvent.java
  src/main/java/net/dv8tion/jda/api/events/sticker/update/GuildStickerUpdateTagsEvent.java
  src/main/java/net/dv8tion/jda/api/events/sticker/update/package-info.java
  src/main/java/net/dv8tion/jda/api/requests/GatewayIntent.java
  src/main/java/net/dv8tion/jda/api/utils/cache/CacheFlag.java
Labels: type: enhancement

#2762 Add some tests for JDABuilder intents and cache flags
  src/main/java/net/dv8tion/jda/api/JDABuilder.java
  src/test/java/net/dv8tion/jda/test/JDABuilderTest.java
  src/test/java/net/dv8tion/jda/test/TestHelper.java
Labels: type: test

#2763 Remove deprecated symbols with deadline 5.1.0
  src/main/java/net/dv8tion/jda/api/Permission.java
  src/main/java/net/dv8tion/jda/api/managers/StageInstanceManager.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/StageInstanceAction.java
  src/main/java/net/dv8tion/jda/internal/managers/StageInstanceManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/StageInstanceActionImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/PermissionUtil.java
Labels: type: breaking

#2764 Add tests for PermissionUtil
  src/main/java/net/dv8tion/jda/internal/utils/PermissionUtil.java
  src/test/java/net/dv8tion/jda/test/util/PermissionUtilTest.java
Labels: type: test

#2765 Fix GuildManager#setSafetyAlertsChannel
  src/main/java/net/dv8tion/jda/internal/managers/GuildManagerImpl.java
  src/test/java/net/dv8tion/jda/test/IntegrationTest.java
  src/test/java/net/dv8tion/jda/test/managers/GuildManagerTest.java
Labels: bug

#2767 Correctly handle disabled intent in setEnabledIntents
  src/main/java/net/dv8tion/jda/api/JDABuilder.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
  src/test/java/net/dv8tion/jda/test/JDABuilderTest.java
Labels: bug

#2768 Fix javadoc typos in MessageRequest
  src/main/java/net/dv8tion/jda/api/utils/messages/MessageRequest.java
Labels: type: documentation

#2771 Ensure label cannot be null in ButtonImpl
  src/main/java/net/dv8tion/jda/api/interactions/components/buttons/Button.java
  src/main/java/net/dv8tion/jda/internal/interactions/component/ButtonImpl.java
  src/test/java/net/dv8tion/jda/test/interactions/ButtonTests.java
Labels: bug

#2769 Handle user in EntityBuilder#createApplicationEmoji as optional
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
Labels: bug

#2772 Fix EntitySelectMenu Doc
  src/main/java/net/dv8tion/jda/api/interactions/components/selections/EntitySelectMenu.java
Labels: type: documentation
