Repository discord-jda/JDA, pull requests merged in 2024-08, with the labels that each got.

#2711 Fix deserialization of interaction components
  src/main/java/net/dv8tion/jda/internal/interactions/component/TextInputImpl.java
  src/main/java/net/dv8tion/jda/internal/interactions/modal/ModalImpl.java
Labels: bug

#2710 Expand list of retried http error codes
  src/main/java/net/dv8tion/jda/internal/requests/Requester.java
Labels: type: enhancement

#2695 Update to Jackson 2.17.2
  settings.gradle.kts
Labels: type: dependencies

#2683 Add `JDA#listenOnce`
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/utils/Once.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
Labels: type: feature

#2580 Add support for profile automod
  src/main/java/net/dv8tion/jda/api/entities/automod/build/AutoModRuleData.java
Labels: type: feature, status: awaiting discord docs pr

#2717 Upgrade to voice gateway v8
  build.gradle.kts
  settings.gradle.kts
  src/main/java/com/iwebpp/crypto/TweetNaclFast.java
  src/main/java/net/dv8tion/jda/api/JDAInfo.java
  src/main/java/net/dv8tion/jda/internal/audio/AudioConnection.java
  src/main/java/net/dv8tion/jda/internal/audio/AudioEncryption.java
  src/main/java/net/dv8tion/jda/internal/audio/AudioPacket.java
  src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java
  src/main/java/net/dv8tion/jda/internal/audio/CryptoAdapter.java
  src/test/java/net/dv8tion/jda/test/audio/CryptoAdapterTest.java
Labels: type: enhancement

#2716 Add new message and embed types
  src/main/java/net/dv8tion/jda/api/entities/EmbedType.java
  src/main/java/net/dv8tion/jda/api/entities/MessageType.java
Labels: type: feature

#2714 Handle guild stickers array as optional in EntityBuilder#createGuild
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
Labels: type: enhancement

#2720 Remove MessageEmbedEvent
  src/main/java/net/dv8tion/jda/api/events/message/MessageEmbedEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/internal/handle/MessageUpdateHandler.java
Labels: type: discord issue, type: breaking

#2721 Remove extension from received audio packets
  src/main/java/net/dv8tion/jda/internal/audio/AudioPacket.java
Labels: bug
