Repository discord-jda/JDA, pull requests merged in 2024-01, with the labels that each got.

#2601 Fix clearing of voice status
  src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/VoiceChannelImpl.java
Labels: bug

#2603 Handle canTalk for private threads in interactions
  src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/ThreadChannelImpl.java
Labels: bug

#2528 Unified channel cache
  build.gradle.kts
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/channel/attribute/ICategorizableChannel.java
  src/main/java/net/dv8tion/jda/api/entities/channel/attribute/IGuildChannelContainer.java
  src/main/java/net/dv8tion/jda/api/entities/channel/attribute/IPositionableChannel.java
  src/main/java/net/dv8tion/jda/api/entities/channel/concrete/Category.java
  src/main/java/net/dv8tion/jda/api/managers/channel/attribute/ICategorizableChannelManager.java
  src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
  src/main/java/net/dv8tion/jda/api/utils/cache/ChannelCacheView.java
  src/main/java/net/dv8tion/jda/api/utils/cache/SortedChannelCacheView.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/NewsChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/StageChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/TextChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/VoiceChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/middleman/AbstractGuildChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/middleman/AbstractStandardGuildChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/ChannelDeleteHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/ChannelUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildMemberRemoveHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/ThreadDeleteHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/ThreadUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/VoiceChannelStatusUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
  src/main/java/net/dv8tion/jda/internal/utils/ChannelUtil.java
  src/main/java/net/dv8tion/jda/internal/utils/Helpers.java
  src/main/java/net/dv8tion/jda/internal/utils/cache/ChannelCacheViewImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/cache/SortedChannelCacheViewImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/cache/UnifiedChannelCacheView.java
  src/test/java/net/dv8tion/jda/entities/channel/ChannelCacheViewTest.java
Labels: type: enhancement, type: proposal

#2607 Return immutable lists when documented
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/StageInstance.java
  src/main/java/net/dv8tion/jda/api/entities/channel/attribute/IPermissionContainer.java
  src/main/java/net/dv8tion/jda/api/entities/channel/attribute/IThreadContainer.java
  src/main/java/net/dv8tion/jda/api/entities/channel/concrete/Category.java
  src/main/java/net/dv8tion/jda/api/interactions/components/LayoutComponent.java
  src/main/java/net/dv8tion/jda/api/interactions/components/selections/StringSelectInteraction.java
  src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
  src/main/java/net/dv8tion/jda/api/utils/messages/MessageEditData.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/ForumChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/MediaChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/NewsChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/TextChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/cache/ChannelCacheViewImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/cache/ShardCacheViewImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/cache/UnifiedCacheViewImpl.java
Labels: type: enhancement

#2605 Added missing properties to ApplicationInfo
  src/main/java/net/dv8tion/jda/api/entities/ApplicationInfo.java
  src/main/java/net/dv8tion/jda/internal/entities/ApplicationInfoImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
Labels: type: feature
