Repository discord-jda/JDA, pull requests merged in 2024-03, with the labels that each got.

#2614 Add support for enforce_nonce
  src/main/java/net/dv8tion/jda/api/requests/restaction/MessageCreateAction.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageCreateActionImpl.java
Labels: type: feature, type: semi-breaking

#2630 Add support for bulk banning users
  src/main/java/net/dv8tion/jda/api/entities/BulkBanResponse.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/requests/ErrorResponse.java
  src/main/java/net/dv8tion/jda/api/requests/Route.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Labels: type: feature

#2636 Fix FlatMapRestAction predicate with complete or submit
  src/main/java/net/dv8tion/jda/internal/requests/restaction/operator/FlatMapRestAction.java
Labels: bug
