Repository discord-jda/JDA, pull requests merged in 2024-10, with the labels that each got.

#2738 Support sending voice messages
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/utils/FileUpload.java
  src/main/java/net/dv8tion/jda/api/utils/messages/MessageCreateBuilder.java
  src/main/java/net/dv8tion/jda/api/utils/messages/MessageCreateData.java
  src/main/java/net/dv8tion/jda/api/utils/messages/MessageCreateRequest.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/internal/utils/message/MessageCreateBuilderMixin.java
  src/test/java/net/dv8tion/jda/test/assertions/restaction/RestActionAssertions.java
  src/test/java/net/dv8tion/jda/test/restaction/MessageCreateActionTest.java
Labels: type: feature

#2743 Fix ScheduledEventManagerImpl::setStatus
  src/main/java/net/dv8tion/jda/internal/managers/ScheduledEventManagerImpl.java
Labels: bug

#2744 Add support for message forwarding
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/MessageReference.java
  src/main/java/net/dv8tion/jda/api/entities/messages/MessageSnapshot.java
  src/main/java/net/dv8tion/jda/api/requests/ErrorResponse.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/MessageCreateAction.java
  src/main/java/net/dv8tion/jda/api/utils/messages/AbstractMessageBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageCreateActionImpl.java
  src/test/java/net/dv8tion/jda/test/restaction/MessageCreateActionTest.java
Labels: type: feature

#2739 Add github action for publishing
  .github/workflows/artifacts.yml
  .github/workflows/docs.yml
  .github/workflows/publish.yml
  .github/workflows/validate.yml
  build.gradle.kts
Labels: type: enhancement

#2725 Added Safety Alerts Channel
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateSafetyAlertsChannelEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/api/managers/GuildManager.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/managers/GuildManagerImpl.java
Labels: type: feature

#2736 Add `ScheduledEvent::getJumpUrl`
  src/main/java/net/dv8tion/jda/api/entities/ScheduledEvent.java
  src/main/java/net/dv8tion/jda/internal/entities/ScheduledEventImpl.java
  src/test/java/net/dv8tion/jda/test/entities/scheduledevent/ScheduledEventTest.java
Labels: type: feature

#2747 Limit compliance tests to public methods
  src/test/java/net/dv8tion/jda/test/compliance/RestActionComplianceTest.java
Labels: type: test

#2749 Fix handling of passing null to setMessageReference
  src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageCreateActionImpl.java
  src/test/java/net/dv8tion/jda/test/restaction/MessageCreateActionTest.java
Labels: bug

#2748 Add more compliance tests
  src/test/java/net/dv8tion/jda/test/compliance/ArchUnitComplianceTest.java
Labels: type: test
