Repository discord-jda/JDA, pull requests merged in 2024-07, with the labels that each got.

#2686 Update and remove deprecated symbols
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/JDABuilder.java
  src/main/java/net/dv8tion/jda/api/audio/hooks/ConnectionListener.java
  src/main/java/net/dv8tion/jda/api/audio/hooks/ListenerProxy.java
  src/main/java/net/dv8tion/jda/api/audit/ActionType.java
  src/main/java/net/dv8tion/jda/api/audit/AuditLogKey.java
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/Member.java
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/MessageEmbed.java
  src/main/java/net/dv8tion/jda/api/entities/StageInstance.java
  src/main/java/net/dv8tion/jda/api/entities/User.java
  src/main/java/net/dv8tion/jda/api/events/self/SelfUpdateDiscriminatorEvent.java
  src/main/java/net/dv8tion/jda/api/events/user/update/UserUpdateDiscriminatorEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/api/interactions/modals/Modal.java
  src/main/java/net/dv8tion/jda/api/managers/AccountManager.java
  src/main/java/net/dv8tion/jda/api/managers/AudioManager.java
  src/main/java/net/dv8tion/jda/api/managers/StageInstanceManager.java
  src/main/java/net/dv8tion/jda/api/requests/GatewayIntent.java
  src/main/java/net/dv8tion/jda/api/requests/RestRateLimiter.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/StageInstanceAction.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/api/utils/SessionController.java
  src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java
  src/main/java/net/dv8tion/jda/internal/entities/UserImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/UserUpdateHandler.java
  src/main/java/net/dv8tion/jda/internal/managers/AccountManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/AudioManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/StageInstanceManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/StageInstanceActionImpl.java
  src/test/java/net/dv8tion/jda/test/compliance/EventConsistencyComplianceTest.java
Labels: type: enhancement, type: breaking, type: documentation

#2704 Fix automatic shutdown for elastic pool
  src/main/java/net/dv8tion/jda/internal/utils/config/ThreadingConfig.java
Labels: bug

#2688 Document `GuildVoiceState#getChannel()` requires the member cache
  src/main/java/net/dv8tion/jda/api/entities/GuildVoiceState.java
Labels: type: documentation

#2703 Add `TeamMember.RoleType`
  src/main/java/net/dv8tion/jda/api/entities/TeamMember.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/TeamMemberImpl.java
Labels: type: feature

#2684 Add abstract `createCopy` method in `SelectMenu`
  src/main/java/net/dv8tion/jda/api/interactions/components/selections/EntitySelectMenu.java
  src/main/java/net/dv8tion/jda/api/interactions/components/selections/SelectMenu.java
  src/main/java/net/dv8tion/jda/api/interactions/components/selections/StringSelectMenu.java
Labels: type: feature
