Repository discord-jda/JDA, pull requests merged in 2024-04, with the labels that each got.

#2642 Handle numeric keys for ETF maps
  src/main/java/net/dv8tion/jda/api/utils/data/etf/ExTermDecoder.java
Labels: bug

#2643 Use typed assertions for RestActions
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/test/java/net/dv8tion/jda/test/Constants.java
  src/test/java/net/dv8tion/jda/test/IntegrationTest.java
  src/test/java/net/dv8tion/jda/test/RestActionAssertions.java
  src/test/java/net/dv8tion/jda/test/entities/guild/AbstractGuildTest.java
  src/test/java/net/dv8tion/jda/test/entities/guild/BulkBanTest.java
  src/test/java/net/dv8tion/jda/test/interactions/EntitlementPaginationTest.java
  src/test/java/net/dv8tion/jda/test/restaction/MessageCreateActionTest.java
Labels: type: enhancement, type: test

#2652 Update dependencies and use version catalog
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle.kts
Labels: type: dependencies

#2654 Update permission enum
  src/main/java/net/dv8tion/jda/api/Permission.java
Labels: type: breaking

#2639 Rewrite JDA readme
  .github/CONTRIBUTING.md
  README.md
Labels: type: documentation

#2653 Refactor nexus publishing logic
  build.gradle.kts
Labels: type: enhancement

#2660 Fix ClassCastException in EntityBuilder#updateMemberCache
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
Labels: bug

#2662 Properly copy poll data in MessageCreateRequest#applyData
  src/main/java/net/dv8tion/jda/api/utils/messages/MessageCreateRequest.java
  src/main/java/net/dv8tion/jda/api/utils/messages/MessagePollBuilder.java
  src/main/java/net/dv8tion/jda/api/utils/messages/MessagePollData.java
  src/test/java/net/dv8tion/jda/test/restaction/MessageCreateActionTest.java
Labels: bug

#2666 Add `IPostContainerManager#setTopic`
  src/main/java/net/dv8tion/jda/api/managers/channel/attribute/IPostContainerManager.java
  src/main/java/net/dv8tion/jda/api/managers/channel/middleman/StandardGuildMessageChannelManager.java
Labels: bug
