Repository discord-jda/JDA, pull requests merged in 2025-04, with the labels that each got.

#2820 Fix `PrivateChannel#getName` returning `null`
  src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/PrivateChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/detached/DetachedPrivateChannelImpl.java
Labels: bug

#2808 Include possible ErrorResponse at Guild#unban Javadoc.
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
Labels: type: documentation

#2801 Manually inherit (copy) deprecation docs
  src/main/java/net/dv8tion/jda/api/events/interaction/command/GenericCommandInteractionEvent.java
  src/main/java/net/dv8tion/jda/api/events/interaction/component/GenericComponentInteractionCreateEvent.java
  src/main/java/net/dv8tion/jda/api/interactions/commands/build/SlashCommandData.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/CommandCreateAction.java
Labels: type: documentation

#2800 Add Guild#retrieveScheduledEvents
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/detached/DetachedGuildImpl.java
  src/main/java/net/dv8tion/jda/internal/utils/Helpers.java
Labels: type: feature

#2698 Fix `FileProxy#withClient` return types
  src/main/java/net/dv8tion/jda/api/utils/AttachmentProxy.java
  src/main/java/net/dv8tion/jda/api/utils/ImageProxy.java
Labels: bug

#2797 Add missing exceptions when attempting to move entities before selecting
  src/main/java/net/dv8tion/jda/internal/requests/restaction/order/OrderActionImpl.java
Labels: bug

#2786 Add a way to retrieve users that used super reaction
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/entities/MessageReaction.java
  src/main/java/net/dv8tion/jda/api/entities/channel/middleman/MessageChannel.java
  src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/ReactionPaginationActionImpl.java
Labels: type: feature

#2577 Add support for guild security incidents
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/guild/SecurityIncidentActions.java
  src/main/java/net/dv8tion/jda/api/entities/guild/SecurityIncidentDetections.java
  src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateSecurityIncidentActionsEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateSecurityIncidentDetectionsEvent.java
  src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
  src/main/java/net/dv8tion/jda/api/requests/Route.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/detached/DetachedGuildImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildUpdateHandler.java
Labels: type: feature

#2798 Add interaction callback response handling
  src/main/java/net/dv8tion/jda/api/interactions/InteractionHook.java
  src/main/java/net/dv8tion/jda/api/interactions/response/InteractionCallbackResponse.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/interactions/InteractionCallbackAction.java
  src/main/java/net/dv8tion/jda/internal/interactions/InteractionHookImpl.java
  src/main/java/net/dv8tion/jda/internal/interactions/response/InteractionCallbackResponseImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/interactions/DeferrableCallbackActionImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/interactions/InteractionCallbackImpl.java
Labels: type: feature

#2830 Document exclusion of tink
  README.md
Labels: type: documentation

#2831 Update dependencies
  build.gradle.kts
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle.kts
Labels: type: dependencies

#2796 Allow \ in invite links
  src/main/java/net/dv8tion/jda/api/entities/Message.java
Labels: bug

#2836 Add basic test for link regex
  src/test/java/net/dv8tion/jda/test/entities/message/MessageRegexTest.java
Labels: type: test

#2837 Fix checks in CommandEditAction
  src/main/java/net/dv8tion/jda/internal/interactions/CommandDataImpl.java
  src/main/java/net/dv8tion/jda/internal/interactions/command/CommandImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/CommandEditActionImpl.java
Labels: bug

#2835 Move voice state cache to guild
  src/main/java/net/dv8tion/jda/api/entities/Guild.java
  src/main/java/net/dv8tion/jda/api/entities/GuildVoiceState.java
  src/main/java/net/dv8tion/jda/api/entities/Member.java
  src/main/java/net/dv8tion/jda/api/events/guild/voice/GenericGuildVoiceEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceDeafenEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceGuildDeafenEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceGuildMuteEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceMuteEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceRequestToSpeakEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceSelfDeafenEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceSelfMuteEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceStreamEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceSuppressEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceUpdateEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceVideoEvent.java
  src/main/java/net/dv8tion/jda/api/events/guild/voice/package-info.java
  src/main/java/net/dv8tion/jda/api/utils/cache/CacheFlag.java
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/GuildVoiceStateImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/MemberImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/StageChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/VoiceChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/detached/DetachedStageChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/detached/DetachedVoiceChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/mixin/middleman/AudioChannelMixin.java
  src/main/java/net/dv8tion/jda/internal/entities/detached/DetachedGuildImpl.java
  src/main/java/net/dv8tion/jda/internal/handle/GuildMemberRemoveHandler.java
  src/main/java/net/dv8tion/jda/internal/handle/VoiceStateUpdateHandler.java
  src/test/java/net/dv8tion/jda/test/IntegrationTest.java
  src/test/java/net/dv8tion/jda/test/entities/guild/GuildLevelCacheTest.java
Labels: type: enhancement, type: semi-breaking

#2782 Add `downloadAsFileUpload` to file proxies
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/utils/AttachmentProxy.java
  src/main/java/net/dv8tion/jda/api/utils/FileProxy.java
  src/main/java/net/dv8tion/jda/api/utils/ImageProxy.java
  src/main/java/net/dv8tion/jda/api/utils/NamedAttachmentProxy.java
Labels: type: feature

#2814 remove wrong ephemeral part from javadocs
  src/main/java/net/dv8tion/jda/api/entities/Message.java
  src/main/java/net/dv8tion/jda/api/interactions/InteractionHook.java
Labels: type: documentation

#2727 Add `ImageProxy#downloadAsIcon`
  src/main/java/net/dv8tion/jda/api/utils/AttachmentProxy.java
  src/main/java/net/dv8tion/jda/api/utils/FileProxy.java
  src/main/java/net/dv8tion/jda/api/utils/ImageProxy.java
Labels: type: feature
