Repository discord-jda/JDA, pull requests merged in 2025-01, with the labels that each got.

#2792 Fix typo in `getButtonById` javadoc.
  src/main/java/net/dv8tion/jda/api/entities/Message.java
Labels: type: documentation

#2790 Fix checking empty embeds
  src/main/java/net/dv8tion/jda/api/EmbedBuilder.java
Labels: bug

#2795 Fix channel cache lock handling
  src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/middleman/AbstractGuildChannelImpl.java
  src/main/java/net/dv8tion/jda/internal/entities/channel/middleman/AbstractStandardGuildChannelImpl.java
  src/test/java/net/dv8tion/jda/test/entities/EntityManagerTest.java
Labels: bug

#2791 Rename `ApplicationEmoji#APPLICATION_EMOJI_CAP` -> `MAX_APPLICATION_EMOJIS`
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/entities/emoji/ApplicationEmoji.java
Labels: type: enhancement, type: documentation
