Repository discord-jda/JDA, pull requests merged in 2025-09, with the labels that each got.

#2905 Update dependencies
  build.gradle.kts
  gradle/libs.versions.toml
Labels: type: dependencies

#2908 Add TextInput#of shortcut
  src/main/java/net/dv8tion/jda/api/components/textinput/TextInput.java
  src/test/java/net/dv8tion/jda/test/components/ComponentTestData.java
  src/test/java/net/dv8tion/jda/test/components/LabelTest.java
Labels: type: feature

#2911 Add `StringSelectMenu.Builder#isRequired()`
  src/main/java/net/dv8tion/jda/api/components/selections/StringSelectMenu.java
Labels: type: enhancement

#2909 Deprecate and replace `TextInput.Builder#setId` with `setCustomId`
  src/main/java/net/dv8tion/jda/api/components/textinput/TextInput.java
Labels: type: enhancement

#2913 Add entity selects and text displays in modals
  src/main/java/net/dv8tion/jda/api/components/Component.java
  src/main/java/net/dv8tion/jda/api/components/ModalTopLevelComponent.java
  src/main/java/net/dv8tion/jda/api/components/ModalTopLevelComponentUnion.java
  src/main/java/net/dv8tion/jda/api/components/label/LabelChildComponent.java
  src/main/java/net/dv8tion/jda/api/components/label/LabelChildComponentUnion.java
  src/main/java/net/dv8tion/jda/api/components/selections/EntitySelectMenu.java
  src/main/java/net/dv8tion/jda/api/components/selections/SelectMenu.java
  src/main/java/net/dv8tion/jda/api/components/selections/StringSelectMenu.java
  src/main/java/net/dv8tion/jda/api/components/textdisplay/TextDisplay.java
  src/main/java/net/dv8tion/jda/api/interactions/modals/ModalMapping.java
  src/main/java/net/dv8tion/jda/internal/components/selections/EntitySelectMenuImpl.java
  src/main/java/net/dv8tion/jda/internal/components/selections/SelectMenuImpl.java
  src/main/java/net/dv8tion/jda/internal/components/selections/StringSelectMenuImpl.java
  src/main/java/net/dv8tion/jda/internal/components/textdisplay/TextDisplayImpl.java
  src/main/java/net/dv8tion/jda/internal/interactions/InteractionImpl.java
  src/main/java/net/dv8tion/jda/internal/interactions/modal/ModalInteractionImpl.java
Labels: type: feature

#2917 Add ComponentSerializer#serialize for convenience
  src/main/java/net/dv8tion/jda/api/components/utils/ComponentSerializer.java
  src/test/java/net/dv8tion/jda/test/components/ComponentSerializerTest.java
Labels: type: enhancement
