Repository discord-jda/JDA, pull requests merged in 2025-07, with the labels that each got.

#2859 Update dependencies
  build.gradle.kts
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: type: dependencies

#2868 Release 6.0.0-rc.1
  build.gradle.kts
  buildSrc/src/main/kotlin/net/dv8tion/jda/tasks/ProjectEnvironmentConfig.kt
  gradle/libs.versions.toml
Labels: release

#2877 Make JDA#getMutualGuilds accept UserSnowflake instead of User objects
  src/main/java/net/dv8tion/jda/api/JDA.java
  src/main/java/net/dv8tion/jda/api/entities/User.java
  src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
  src/main/java/net/dv8tion/jda/internal/JDAImpl.java
Labels: type: enhancement

#2882 Fix compliance test for nullability on varargs
  src/main/java/net/dv8tion/jda/api/managers/AccountManager.java
  src/main/java/net/dv8tion/jda/api/managers/ApplicationEmojiManager.java
  src/main/java/net/dv8tion/jda/api/managers/ApplicationManager.java
  src/main/java/net/dv8tion/jda/api/managers/AutoModRuleManager.java
  src/main/java/net/dv8tion/jda/api/managers/CustomEmojiManager.java
  src/main/java/net/dv8tion/jda/api/managers/GuildManager.java
  src/main/java/net/dv8tion/jda/api/managers/GuildStickerManager.java
  src/main/java/net/dv8tion/jda/api/managers/GuildWelcomeScreenManager.java
  src/main/java/net/dv8tion/jda/api/managers/Manager.java
  src/main/java/net/dv8tion/jda/api/managers/PermOverrideManager.java
  src/main/java/net/dv8tion/jda/api/managers/RoleManager.java
  src/main/java/net/dv8tion/jda/api/managers/ScheduledEventManager.java
  src/main/java/net/dv8tion/jda/api/managers/StageInstanceManager.java
  src/main/java/net/dv8tion/jda/api/managers/TemplateManager.java
  src/main/java/net/dv8tion/jda/api/managers/WebhookManager.java
  src/main/java/net/dv8tion/jda/api/managers/channel/ChannelManager.java
  src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/EntitlementPaginationAction.java
  src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
  src/main/java/net/dv8tion/jda/internal/managers/AccountManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/ApplicationEmojiManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/ApplicationManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/CustomEmojiManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/GuildManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/GuildStickerManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/GuildWelcomeScreenManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/ManagerBase.java
  src/main/java/net/dv8tion/jda/internal/managers/PermOverrideManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/RoleManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/TemplateManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/WebhookManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/managers/channel/ChannelManagerImpl.java
  src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/EntitlementPaginationActionImpl.java
  src/test/java/net/dv8tion/jda/test/compliance/ArchUnitComplianceTest.java
Labels: type: test

#2884 Remove port stripping in VoiceServerUpdateHandler
  src/main/java/net/dv8tion/jda/internal/handle/VoiceServerUpdateHandler.java
Labels: bug
